### ISSUE TITLE
Distortions when adjusting shader texture offset and scale (Windows)

### ISSUE THREAD

**Issue by JackM36** [RenderHeads/UnityPlugin-AVProVideo#104]
I am playing some 360 stereo (T/B) videos in my app. I am not using the "Update Stereo Material" component to do it however. I have two spheres (one for each eye) and I am manually adjusting the texture scale and offset on the materials. Both of the spheres have an "Apply to mesh" component. (I will not get into the reasons of doing it manually, but in my case it is required).

Everything works great when I build for Android. However, the image seems to be distorted when played on Windows (Editor or Build). Seems like the offset and scale does not work correctly.

These are the settings I use on each "eye":
Left
![image](https://user-images.githubusercontent.com/9931176/60599439-bea70d00-9dae-11e9-9050-1af6e831c19b.png)

Right
![image](https://user-images.githubusercontent.com/9931176/60599480-d1b9dd00-9dae-11e9-9d65-c7bcd3038595.png)

This is the result
![image](https://user-images.githubusercontent.com/9931176/60599343-991a0380-9dae-11e9-8ec0-1cfa2c63b255.png)

Again, all of this works great when build for Android without any changes or modifications.

Any idea why this might be happening?

 - Unity version: 2018.3.5f1
 - AVPro Video version: 1.9.17 (same with older versions)
 - Operating system version: Windows
 - Device model: Oculus Rift

**Comment by AndrewRH** [comment]
In the MediaPlayer Visual section, try changing the texture repeat mode to "wrap"/"repeat" instead of clamp.

I suspect it is due to platform differences.  On some platforms we have to flip the texture vertically, and so we do this in the shader via the texture offset+scale values.  We take the initial values that the user supplies in ApplyToMesh (for offset+scale) and then modify those if a vertical flip is required.

I'm not entirely sure of your set up.  Is it possible for you to share your project/scene with us?  If so please email it to unitysupport@renderheads.com

Thanks,

**Comment by JackM36** [comment]
I changed it to **repeat** but the issue still remains.

I adjusted the offset/scale values a bit and I managed to make some stereo videos play correctly, but others are still weirdly wrapped like the previous example I posted. Does the shader behave differently based on the video somehow? What video characteristics could influence this?

I cannot send the project setup but I will fully describe it for you:

- A **MediaPlayer** component is created on _Awake_.
- There are two sphere meshes, each one assigned to a different eye (each has its own layer. Right eye camera only sees right eye sphere layer, and the same for the left eye).
- An **ApplyToMesh** component is created for each sphere
- The texture offset/scale values are set per sphere as seen in the screenshots below
- A video file is loaded in **MediaPlayer**

Left eye/sphere
![image](https://user-images.githubusercontent.com/9931176/61057271-37344c00-a3f5-11e9-965c-35a872809e24.png)

Right eye/sphere
![image](https://user-images.githubusercontent.com/9931176/61057298-4e733980-a3f5-11e9-9f01-8c90fa0ebc13.png)

Result:
![image](https://user-images.githubusercontent.com/9931176/61057323-5af79200-a3f5-11e9-9596-6131b3ffde69.png)

As you can see, the image in the right eye looks weirdly wrapped on the pole. The same happens to the left eye if I look a bit upwards (looks like the weird wrap thing happens in different poles on each eye). Ignore the black patch, that is part of the video and not a weird distortion.

**Comment by AndrewRH** [comment]
Is your video stereo?
It doesn't look stereo from the preview images..I think I know what might be happening.
Our Windows plugin unfortunately doesn't correctly render stereo videos that contain stereo metadata.  Instead it only renders one eye, so applying any offsets to get left/right eye positions won't work.  To fix this you need to remove the stereo metadata from the video file.  We have a number of steps for this in the FAQ section of the PDF documentation.  I think this is the reason because it explains why it only happens with some video files.

**Comment by JackM36** [comment]
I see!

Yes they are all (tested) stereo videos. Not sure how they are rendered differently though.

Does your Android plugin render videos with stereo metadata? Because I have played the exact same video files on our Android build (same setup. Just now adjusted the texture values for windows) without issues. Not sure about metadata to be honest, since we receive the final video files from clients.

**Comment by AndrewRH** [comment]
This issue has been resolved now in 2.0.0-beta1.
Stereo videos containing metadata can now play back correctly in Windows
