### ISSUE TITLE
Black screen issue on Android, iOS

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#1089]
* Unity version: 2019.4.15f1
* AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro 2.3.3
* Operating system version: Android , iOS
* Device model: all devices
* Video specs (resolution, frame-rate, codec, file size):  https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8

In some cases, a black screen is displayed.
It seems to occur when `StartedBuffering` and `ResolutionChanged` events occur at the same time.
How do i fix it?

**Comment by kahnivore** [comment]
Can you please fill out all the details asked for in the template so we can try to reproduce this:

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by dw8869** [comment]
@kahnivore 
Sorry, i edited the comment.

**Comment by kahnivore** [comment]
Does the black screen happen on app start-up, or during playback? Could you provide unfiltered log files please so we can see if there are any errors?

**Comment by ngz82** [comment]
FYI I am seeing possibly a similar thing on iOS  when streaming HLS video, with Looping set to True - when our video finishes playback and restarts due to looping, the ResolutionChanged event fires (this is the only event that fires), upon this event firing we run a function to re-map the texture from `mediaPlayer.TextureProducer.GetTexture(0);` to our materials (which was implemented for adaptive bitrate streams if the resolution changes) , it works fine in editor and seemingly on Android (less testing) however on iOS it seems like around half the time we are getting a plain black texture - no error or nulls. The texture is just black. If we let the video play out again (it's only a short 10 sec looping video) the next time it plays it may or may not  work half the time - its inconsistent. 
Just chiming in as I was about to raise a bug myself and this seemed potentially related.   
We do check if the texture is null however it is not null in this case -  we wait until its not null before applying the texture to the materials.
This logic had been working fine previously on 1.X - we recently upgraded to 2.3.3.

**Comment by MorrisRH** [comment]
@ngz82 that does sound like a different issue, would be great if you could create a separate issue for it. If possible please share the stream you're using and details on how the media player is setup. Thanks!

**Comment by dw8869** [comment]
@kahnivore @MorrisRH 
Log file URL :
https://drive.google.com/file/d/1LKn3N-Ke6-CHUe8RUOk2N2T9jwOuSkzx/view?usp=sharing

**Comment by MorrisRH** [comment]
On iOS, the resolution changed notification is fired when the stream information changes - the actual texture change lags behind it. We will look into getting this fixed. A workaround for now would be to delay handling texture updates until the end of the next frame.

**Comment by RenderHeadsSte** [comment]
Can you?  Do you see the same problem with it enabled?

**Comment by kahnivore** [comment]
Closing to lack of response. Feel free to reopen if the problem persists.

**Comment by dw8869** [comment]
@MorrisRH  @RenderHeadsSte  @kahnivore 
This issue also occurs when the `Use OES Rendering` option is enabled.

**Comment by SecretTonto** [comment]
@kahnivore 
Is this issue not progressing?

This problem is still being reproduced
AVPro 2.4.1

**Comment by SecretTonto** [comment]
@RenderHeadsSte 
I will record the video and share it with you within this week.

**Comment by SecretTonto** [comment]
It is difficult to proceed with the issue because there is a distribution schedule for our app until next Tuesday. I think it will be delivered a little later.
Please excuse me.

**Comment by Chris-RH** [comment]
Hi, I was just wondering if you had any luck with this?

**Comment by SecretTonto** [comment]
@Chris-RH 
I'm sorry. I was too busy to take care of it.
I will share the results within this week.

**Comment by Chris-RH** [comment]
Hi, that's no problem at all. Whenever you have time :)

**Comment by Ste-RH** [comment]
Closing this issue due to a lack of response.  Please do re-open it if you are still seeing the issue and have more information to share.
