### ISSUE TITLE
Issue in playing 360 stereo top/bottom video. The scereo effect frequently on and off

### ISSUE THREAD

**Issue by parandham03** [RenderHeads/UnityPlugin-AVProVideo#1126]
In scene 1 (which contains VR camera), I am downloading AVPRO 360 video playing scene(scene 2) as asset bundle and loading additive.
The scene 2 contain media player with 360 stereoscopic top/bottom URL, apply to material component.

While playing in oculus quest the stereo effect is frequently on and off. Shall I force to play the video in stereo mode always?

Device: Oculus Quest

Video : 360 stereo top/bottom.
Resolution: 5760 x 5760.

System Information:
AVPro Video: v2.2.0 (plugin v2.2.0f1-core)
Target Platform: Android
Unity: v2019.2.13f1 WindowsEditor

**Comment by kahnivore** [comment]
Yeah, have you [set the stereo mode](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-stereo-video.html#manually-specifying)? What do you mean by 'the effect is frequently on and off', could you provide a screenshot? 

Would recommend upgrading your AVPro Video version to the latest (2.4.1) as a lot of changes have been made since 2.2.0.

**Comment by parandham03** [comment]
@kahnivore  "the effect is frequently on and off" means the video is playing as monoscopic video and stereoscopic video.

**Comment by kahnivore** [comment]
Could you send us a sample reproducible project to unitysupport@renderheads.com? Please include the issue number (1126) in the subject line. 

Thanks.

**Comment by parandham03** [comment]
> Does it appear on or off based on direction you are looking?

Yes. 
Now it's fixed. Forget to add UpdateMultiPassStereo script.
