### ISSUE TITLE
Media Foundation sometimes fails to stream multiple instances of the same MP4 URL concurrently

### ISSUE THREAD

**Issue by cprenoveau-illogika** [RenderHeads/UnityPlugin-AVProVideo#1137]
**Describe the issue**
When streaming the same video url on multiple media players, some of them fail to play.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.26
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.4.1-trial
 - Operating system version: Windows 10
 - Device model: PC
 - Video specs (resolution, frame-rate, codec, file size): 1280x720 24fps mp4 150mb

**To Reproduce**
1. Open AVProVideo/Demos/Scenes/Demo_MediaPlayer
2. Select MediaPlayer and set media source to path: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
3. Copy-paste the MediaPlayer 3 or more times
4. Press play and notice that some of them don't play

**Comment by kahnivore** [comment]
Why are you using multiple media players to play the same stream? This will be very heavy on performance. Have you checked your task manager while running to see if you're maxing out your system resources? If you're trying to play the same video you could use multiple display components that all reference the same media player component, instead of duplicating the media player.

**Comment by cprenoveau-illogika** [comment]
We need to stream the same video url multiple times with different timings.
I checked memory, CPU and GPU, none of them come close to being maxed out. I also tried streaming 3 different videos of approximately the same size and it worked as intended. The issue seems to occur specifically when streaming the same video multiple times.

**Comment by robbbbbb** [comment]
I know this issue suggests that streaming 3 different videos isn't a problem, only streaming the same one multiple times. But I'm suspicious that it seems to be reporting a very similar sounding issue to the one I reported in #1136 the other day. I say that because with that issue the problem gets *significantly* worse when playing two different streams from two different media players concurrently @cprenoveau-illogika, are you in a position to log out what the values of these properties is for the players that are failing to play in your example:

- Control.IsPlaying()
- Control.IsSeeking()
- Control.IsBuffering()
- Control.GetBufferedTimes()

I suspect on the ones that aren't playing you'll either see IsSeeking() true for a long time, and/or you'll see GetBufferedTimes() returning a range that is filling up, but incredibly slowly, by just a few bytes a second.

**Comment by cprenoveau-illogika** [comment]
IsPlaying() : true
IsSeeking() : false
IsBuffering() : true
BufferedTimes() : Count = 1, Duration = 39.6 but one has a significantly lower duration of 6.1567383

**Comment by kahnivore** [comment]
@cprenoveau-illogika thanks for sending a project through - if you leave it running for a while on your side, does the third player eventually play?

**Comment by kahnivore** [comment]
I'm wondering if this is server related because for example:

1. If I play the bunny video locally from streaming assets they all start immediately 
2. If I play the bunny video from our AWS bucket, all three play (although each starts a split second apart) 

Do you perhaps have another storage space to stream the videos from to confirm this?

**Comment by cprenoveau-illogika** [comment]
Hello! I tried playing the video from another storage space and I still have the same issue.
https://installers.sandbox.game/BigBuckBunny.mp4

**Comment by Chris-RH** [comment]
Hi @cprenoveau-illogika, No further updates I'm afraid, but we are still working on pinpointing the source of the problem for you.

**Comment by kahnivore** [comment]
Is it a requirement of yours to use ApplyToMesh? Doing a bit of testing and this issue doesn't seem to crop up when using some of the other display components.

**Comment by cprenoveau-illogika** [comment]
I still get the issue using UGUI display.

**Comment by cprenoveau-illogika** [comment]
This:
https://www.amazon.ca/Lenovo-ThinkPad-Extreme-Business-Notebook/dp/B07JJ72SCS

<http://www.illogika.com/>
*Caroline Prenoveau || Programmer*
T. 514.360.3710
M. 514.241.4265
--
-


Le ven. 8 avr. 2022, à 09 h 32, kahnivore ***@***.***> a
écrit :

**Comment by Chris-RH** [comment]
Hi, I just want to check a few things

1. When playing the file that you emailed to us, does the third media player ever start running for you? It varies in my own tests, between starting immediately and after a maximum of about 2 minutes 30 seconds . Obviously this isn't ideal, but I just want to check that we are getting similar results.
2. Is the intention to have these all playing on the same screen or on separate screens?
3. How many instances are you wanting to be playing?

**Comment by cprenoveau-illogika** [comment]
1. It started playing after 9 minutes 23 seconds on my machine. So yes, I was wrong, it does start at some point.
2. Same screen.
3. It's up to the players. I'm guessing there would be some arbitrary limit for performance considerations.

**Comment by Chris-RH** [comment]
Hi, its interesting that the same scene that you sent us seems to take a lot longer on your system. I've got a similar graphics card, but your CPU and RAM are better.
As a temporary work around, would it be possible to have multiple to duplicate the file on the server and have the media players access each duplicate? Or possibly two media players to a duplicate?

**Comment by Fasox** [comment]
Hi @Chris-RH that wouldn't be a feasible workaround for us, duplicate them is not an option due to license and legal reasons. Nor it seems to really solve the problem just kicking it further.

Is there any possibility of having access to the source code so we can debug it and maybe fix it ourselves? This delay of 24 days starts to have an impact on our roadmap.

**Comment by AndrewRH** [comment]
If I change the Video API setting to "WinRT" then it seems to behave much better.  Does that work for you @cprenoveau-illogika @Fasox ?

**Comment by cprenoveau-illogika** [comment]
You're right, it is a lot better. There's still some delay, but it's a few seconds now instead of 9 minutes, so totally acceptable I think.

**Comment by Chris-RH** [comment]
Thanks for the update @cprenoveau-illogika, I'm glad that we have been able to solve this for you.  Have a great day.

**Comment by cprenoveau-illogika** [comment]
@Chris-RH Hi. Unfortunately, it seems 3D audio doesn't work when I switch from Media Foundation to WinRT. Is there anything I missed?

**Comment by Chris-RH** [comment]
Oh no! I'll have a look.

**Comment by Chris-RH** [comment]
thanks
