### ISSUE TITLE
Use MediaPlayer with a Render Texture

### ISSUE THREAD

**Issue by jessekirbs** [RenderHeads/UnityPlugin-AVProVideo#1180]
Hello! Is it possible to use AVPro Media Player with a render texture in Unity? I know you can apply it to a material, but I'm using a plugin that requires a render texture and would love to utilize AVPro for this. Thank you!

**Comment by kahnivore** [comment]
Hi @jessekirbs 

It's not a built-in feature as such, but the Media Player does output a texture that you could cast to a render texture. 

A good reference is in a file called MediaPlayerEditor_Play.cs. We use this code to render the preview player in the inspector. There's a method called RenderPreview(), which shows how to set up materials, render to render texture etc.

Let us know if this helps?

**Comment by jessekirbs** [comment]
Hey @kahnivorem,

Thanks for directing me there. I've been messing with it over the last few days and I can't quite seem to wrap my head around how to get it working. I'm still very new to C#. Would it be possible to get a sample script that just applies the Media Player output to a render texture? Much appreciated!

**Comment by AndrewRH** [comment]
Here's a C# component you can try.  Just add these 2 files to your project.

Copy this one to /Assets/AVProVideo/Runtime/Scripts/Components:
[ResolveToRenderTexture.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/8754114/ResolveToRenderTexture.zip)

Copy this one to /Assets/AVProVideo/Editor/Scripts/Components:
[ResolveToRenderTextureEditor.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/8754105/ResolveToRenderTextureEditor.zip)

Then you will be able to add a ResolveToRenderTexture component to a GameObject.  This component will allow you to specify your own RenderTexture via the Inspector, or via C# scripting using the property ``ExternalTexture``.  Otherwise it will generate an internal RenderTexture which you can get via C# usign the property ``TargetTexture``.

Let us know how that works for you.

Thanks,

**Comment by jessekirbs** [comment]
@AndrewRH You're the best. Thank you very much. This worked perfectly!

**Comment by Chris-RH** [comment]
Awesome! So glad it worked for you :)
