### ISSUE TITLE
[iOS] Play is not finished, but an FinishedPlaying event occurs.

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#1196]
- Unity version: 2020.3.32f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.5.1
 - Operating system version: iOS 15.5
 - Device model: iPhone 13 Pro Max
 - Video URL : https://f58054c8a1fe41578a1ca586b0186763.azureedge.net/008dfd7e-96c8-4f0b-a052-fa52d8837d5e/b418693a-ab92-4a6c-82ba-df352a5c.ism/manifest(audio-only=false,format=m3u8-aapl-v3).m3u8

Play is not finished, but an `FinishedPlaying` event occurs.
It does not occur in iOS 15.3 and appears to occur in iOS 15.4 and later.

`FinishedPlaying` when the time information is as follows.
* `mediaPlayer.Control.GetCurrentTime()` -> 19.987150629
* `mediaPlayer.Info.GetDuration()` -> 20.033

**Comment by MorrisRH** [comment]
I'm afraid that as the issue is clearly caused by something changing between iOS 15.3 and 15.4 there is not much we can do about it. I did spot whilst testing though that your audio track is slightly shorter than the video track and this is what is likely to be causing the FinishedPlaying event to fire slightly early.

The output from ffprobe for the final segment has the following for the video track:
```
start_time=18.066656
duration_ts=183000
duration=2.033333
```
and for the audio track:
```
start_time=18.005333
duration_ts=157440
duration=1.749333
```

**Comment by dw8869** [comment]
@MorrisRH 
Is the event occurs on audio track length or video track length?

**Comment by MorrisRH** [comment]
With HLS it's the audio track length.

**Comment by dw8869** [comment]
Thank you for the information.
