### ISSUE TITLE
NoClassDefFoundError about Lambda

### ISSUE THREAD

**Issue by songhuan** [RenderHeads/UnityPlugin-AVProVideo#1226]
have crash:

E/CrashReport-GameAgent: <LogError> - ReportException: AndroidJavaException java.lang.NoClassDefFoundError: Failed resolution of: Lcom/renderheads/AVPro/Video/-$$Lambda$_14QHG018Z6p13d3hzJuGTWnNeo;
    *********
    java.lang.NoClassDefFoundError. Failed resolution of. Lcom/renderheads/AVPro/Video/-$$Lambda$_14QHG018Z6p13d3hzJuGTWnNeo;
    com.renderheads.AVPro.Video._$$Lambda$_14QHG018Z6p13d3hzJuGTWnNeo.<clinit>(Unknown Source.5)
    com.renderheads.AVPro.Video.Player_ExoPlayer.InitialisePlayer(Unknown Source.137)
    com.renderheads.AVPro.Video.Player_Base.Initialise(Unknown Source.83)
    com.renderheads.AVPro.Video.Manager.CreatePlayer(Unknown Source.85)
    com.unity3d.player.UnityPlayer.nativeRender(Native Method)
    com.unity3d.player.UnityPlayer.access$300(Unknown Source.0)
    com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source.95)
    android.os.Handler.dispatchMessage(Handler.java.102)
    android.os.Looper.loopOnce(Looper.java.210)
    android.os.Looper.loop(Looper.java.299)
    com.unity3d.player.UnityPlayer$e.run(Unknown Source.20)
    Caused by. java.lang.ClassNotFoundException. com.renderheads.AVPro.Video.-$$Lambda$_14QHG018Z6p13d3hzJuGTWnNeo

have guy  fix this ? #

**Comment by Chris-RH** [comment]
Hi @songhuan 
Can you please fill out all the details asked for in the template so we can try to reproduce this:

Describe the issue - A clear and concise description of what the issue is.

Your Setup (please complete the following information):
Unity version:
AVPro Video version (number and edition (trial/core/ultra/enterprise)):
Operating system version:
Device model:
Video specs (resolution, frame-rate, codec, file size):

To Reproduce
1.
2.
3.

Logs
If applicable, add error logs to help explain your problem.

Screenshots
If applicable, add screenshots to help explain your problem.

Videos
If applicable, add a copy of your video or the URL

Scripts
If applicable, add a copy of any custom scripts used.


Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by Ste-RH** [comment]
@songhuan We require, as a very minimum, a full un-filtered logcat output.  Preferably all the information Chris asks for in addition.

**Comment by Chris-RH** [comment]
Hi @songhuan 
We need more information if we are going to be able to help you, please.

**Comment by Chris-RH** [comment]
Closing due to lack of response.  Please reopen if you have further information.
