### ISSUE TITLE
FinishedSeeking not trigger in windows 

### ISSUE THREAD

**Issue by LongMarch7** [RenderHeads/UnityPlugin-AVProVideo#1267]
when i use SeekToFrameRelative/Seek/SeekFast/SeekToFrame function in windows7，FinishedSeeking event always doesn't trigger

**Comment by Chris-RH** [comment]
Hi @LongMarch7 

Can you please fill out all the details asked for in the template so we can try to reproduce this:
Describe the issue
A clear and concise description of what the issue is.
Your Setup (please complete the following information):
Unity version:
AVPro Video version (number and edition (trial/core/ultra/enterprise)):
Operating system version:
Device model:
Video specs (resolution, frame-rate, codec, file size):
To Reproduce
1.
2.
3.
Logs
If applicable, add error logs to help explain your problem.
Screenshots
If applicable, add screenshots to help explain your problem.
Videos
If applicable, add a copy of your video or the URL
Scripts
If applicable, add a copy of any custom scripts used.
Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by LongMarch7** [comment]
hello @Chris-RH  my environment is:
unity version:
2021.2.4f1c1

avpro video version:
AVPro Video - Ultra Edition 2.5.6

Operating system version:
windows 7

not error log.。 when i debugger , the isseeking function always return true;
![image](https://user-images.githubusercontent.com/17683782/186120378-a4ce6a81-12ef-4029-b8af-960a72580d56.png)

**Comment by LongMarch7** [comment]
when i runtime in windows10，isSeeking function can return true

**Comment by Chris-RH** [comment]
You are only seeing this in Windows 7?
