### ISSUE TITLE
Paid iphone version showing red color background 

### ISSUE THREAD

**Issue by syedali1621** [RenderHeads/UnityPlugin-AVProVideo#127]
I recently bought ios version but when i build avpro first time in my iphone video playing okay without logo but when i import any other package and build the same scene and run on my iphone then red color background is visible in video.
i tried many possible ways like only import ios plugin and untick android and other plugins but still this problem exist.

Please help

**Comment by AndrewRH** [comment]
Hi,

I believe this is caused by the option YpCbCr - you can disable this setting in the MediaPlayer component, under the section Platform Specific > iOS

This option is an optimisation that saves memory.  If you use it with our DisplayUGUI, ApplyToMesh/ApplyToMaterial components then it should work fine.   If you use it with your own shader however it will not work as it requires special processing.

Does that helps?  How are you using the video (any special components or shaders)?

**Comment by syedali1621** [comment]
yes thank you ypCbCr creating problem now solved.
i am using vuforia image target feature with avpro player.
