### ISSUE TITLE
How to play video when open media with no white screen show？

### ISSUE THREAD

**Issue by vlisk** [RenderHeads/UnityPlugin-AVProVideo#1272]
**Question**
How to play video when open media with no white screen show？

when OpenMedia Call it will show white scree not the right video frame

**Comment by Chris-RH** [comment]
Hi @vlisk 

Can you please fill out all the details asked for in the template so we can try to reproduce this:
**Describe the issue**
A clear and concise description of what the issue is.
**Your Setup (please complete the following information):**
Unity version:
AVPro Video version (number and edition (trial/core/ultra/enterprise)):
Operating system version:
Device model:
Video specs (resolution, frame-rate, codec, file size):
**Steps To Reproduce**
1.
2.
3.
**Logs**
If applicable, add error logs to help explain your problem.
**Screenshots**
If applicable, add screenshots to help explain your problem.
**Videos**
If applicable, add a copy of your video or the URL
**Scripts**
If applicable, add a copy of any custom scripts used.
**Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE**
Instead email the link to us [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by vlisk** [comment]
Describe the issue
when OpenMedia Call in code, it will show white screen at start，i guess it can not load at one frame first，i want to know any method to play immediatly

Your Setup (please complete the following information):
Unity version:
Unity2020.3.23f1
Operating system version:
Windows10
Video specs (resolution, frame-rate, codec, file size):
Steps To Reproduce
1.add media player and display uGUI
2.attach medie player to display uGUI
3.add a C# script to control play 

Logs
no log
Screenshots

Videos

Scripts
videoPlayer.OpenMedia(videoPlayer.MediaPath, true);

**Comment by vlisk** [comment]
@Chris-RH

**Comment by Chris-RH** [comment]
You want to add this to the end of that:
 autoPlay: true;

**Comment by vlisk** [comment]
i want to use code to control mediaplayer load different path video to play ,so what is the correct code should i write avoid the first frame not is not default show, thanks!! @Chris-RH

**Comment by vlisk** [comment]
![image](https://user-images.githubusercontent.com/38219232/186879438-ec7cf8c8-b077-47bc-8c32-500c14f588f3.png)

default show is like this!!
@Chris-RH

**Comment by Chris-RH** [comment]
Ahh, I think you mean this: _noDefaultDisplay = true;
https://www.renderheads.com/content/docs/AVProVideo/api/RenderHeads.Media.AVProVideo.DisplayUGUI.html#RenderHeads_Media_AVProVideo_DisplayUGUI_NoDefaultDisplay

Or you want to be able to set the default texture:  _defaultTexture;
https://www.renderheads.com/content/docs/AVProVideo/api/RenderHeads.Media.AVProVideo.DisplayUGUI.html?q=defaulttexture#RenderHeads_Media_AVProVideo_DisplayUGUI_DefaultTexture

**Comment by vlisk** [comment]
![image](https://user-images.githubusercontent.com/38219232/186886012-e7fa6f79-1ee5-4472-9c1a-cc1857c408e7.png)
no, i do not mean that,even i set a other image, it will take long time in low performance device like android device before real paly video image;

**Comment by Chris-RH** [comment]
What sort of file are you trying to play and from where?
Do you get a similar result when just using the demo scenes?

**Comment by vlisk** [comment]
i use file type is mp4 load from StreamingAssets folder, size is 17MB, i try default demo it will happen also @Chris-RH

**Comment by vlisk** [comment]
it seem time is waste for openmedia method ，during this time it will show the defalut texture ，at low performance device ，default texture with show long time ，i almost wait about 4 second see the default texture then first frame of video just start in；

**Comment by Chris-RH** [comment]
Have you tried encoding your media with faststart?

**Comment by vlisk** [comment]
you mean unity build in encode like h265 \h264\vp8? otherwise,i would like to know if any method to cache the media , no need to openmedia everytime when i change the media. 

> Have you tried encoding your media with faststart?

**Comment by Chris-RH** [comment]
Unfortunately we can't control caching behaviour in Windows, so that's not really possible.

Fast Start enabled allows video playback to begin before the file has been completely downloaded.  Usually the metadata is stored at the end of the file in atoms. The mdat atom is located before the moov atom.  Fast Start moves the moov atom to the beginning of the file, allowing it to start playing it quicker.

Using ffmpeg: 

ffmpeg -i input.mp4 -c copy -movflags +faststart output.mp4
