### ISSUE TITLE
[Android] `SetPlaybackRate` starts playing video, even if paused

### ISSUE THREAD

**Issue by artoonie** [RenderHeads/UnityPlugin-AVProVideo#1278]
**Describe the issue**
`SetPlaybackRate` starts playing a paused video, but `_controlInterface.IsPlaying()` returns false, so you cannot `Pause` it without `Play`ing first

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.7f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.5.5 Core
 - Operating system version: Android 11
 - Device model: Pixel 2
 - Video specs (resolution, frame-rate, codec, file size): 1080, h264, 600mb

**To Reproduce**
1. Load a video (using `MediaPlayer`, not `ExoPlayer`)
2. Pause
3. Change playback speed
4. Note that the video begins playing, but `_controlInterface.IsPlaying()` returns `false`.

**Workaround**
1. Pause
2. SetPlaybackRate
3. Wait a frame
4. Play(); Pause();

**Comment by Ste-RH** [comment]
Playback rate is essentially an un-pause operation.  This is because a playback rate of zero is paused.

In reproducing this issue I can see there is a difference between Android and the Apple platforms, and Windows is not quite the same as well.  We will look to bring them into line.

That said.  The following two pieces of code should/will result in a playing video at half speed:

			_mediaPlayer.OpenMedia( _mediaReference, true );
			_mediaPlayer.Control.Pause();
			_mediaPlayer.Control.SetPlaybackRate( 0.5f );

and

			_mediaPlayer.OpenMedia( _mediaReference, false );
			_mediaPlayer.Control.Pause();
			_mediaPlayer.Control.SetPlaybackRate( 0.5f );

...and 'IsPaying()' should/will return true.

If you desire the video to be opened, but in a paused state and the playback rate set to half (once play is called on the paused video) then you would want to do this:

			_mediaPlayer.OpenMedia( _mediaReference, false );
			_mediaPlayer.Control.SetPlaybackRate( 0.5f );
			_mediaPlayer.Control.Pause();

Note that this will not work as outlined above until the next release (v2.6.1).

**Comment by Chris-RH** [comment]
Version 2.6.1 has been released. Please let us know if the issue has not been fixed for you.
