### ISSUE TITLE
Can this be used to play images?

### ISSUE THREAD

**Issue by AP432** [RenderHeads/UnityPlugin-AVProVideo#1285]
**Question**
I've recently been given a project to work on that is using AVPro as a media player. 
They've requested to play images through the application and I'm just asking the question on whether it's possible to do so through this or if I need to switch to a different solution when playing images? Currently when playing images they appear warped...
Thank you for any help with this

**Comment by Ste-RH** [comment]
I am not entirely sure what you mean by 'playing images'.  AVPro Video is geared around playing back videos.  You could make a video that is a sequence of images and then play that back, or maybe keyframe every frame and seek/pause on each image as desired.

By 'warping', do you mean the aspect ratio is not correct?  If so, that is likely to be how you are rendering the video frames rather than anything AVPro Video is doing.  That said, there is a currently known issue on Windows with HAP playback where the aspect ratio might be a little out/incorrect.

**Comment by AP432** [comment]
Thanks for the response! @Ste-RH 
Basically it's a 360 video player for rooms that project onto multiple walls. Before we used AVPro, we could use the standard Unity player and pick a jpeg or png and it would display the image (360) that we wanted. 
Was wondering if there was a way around getting the AVPro component to accept these file types and 'play' or show the image. that the user selects.

**Comment by Ste-RH** [comment]
Still not 100% sure what functionality you require.  Can you outline the exact functionality you are looking for?

**Comment by AP432** [comment]
Okay, no worries.
So the application uses AVPro as its chosen video player component. The application itself is used to play videos. 
User opens the application, they are given the option to browse for a file. They pick a video or image file and then the application plays it. 
What we want is the ability to pick an image and for it to show it. I was wondering if this would be possible through AVPro. 

Any more details needed then please let me know

Appreciate the help with this

**Comment by Ste-RH** [comment]
Ahh, right.  With you (I think!).

If you want to do this programmatically then you can use the 'extract frame' functionality (see MediaPlayer_ExtractFrame.cs) to grab a frame from a given video.

**Comment by Ste-RH** [comment]
Do you need any more assistance @AP432? Or can we close this issue?

**Comment by AP432** [comment]
Yes, thank you for your prompt assistance
