### ISSUE TITLE
Memory Leak on iOS

### ISSUE THREAD

**Issue by driftboat** [RenderHeads/UnityPlugin-AVProVideo#1311]
![image](https://user-images.githubusercontent.com/247809/193194051-89a6645d-ca60-4939-8d60-512202e167a6.png)
Unity 2022.1 URP
iOS 15.7

**Comment by Chris-RH** [comment]
Hi @driftboat. I'm going to need a bit more context here please :)

1. What device(s) are you testing on?
2. Which version of AVPro are you using?
3. What are the specs of the video(s) you are playing?
4. What exactly is your app doing when this occurs? It it just playing a video on loop, or are you reloading a video, loading different videos etc? Creating/destroying mediaplayer object?
5. How big is the memory leak? increase over time, or per play? How long a time does this occur over? Does it continue to increase forever or does it start to decrease after some time? 

For more info:  
There’s a texture cache under the hood so that we’re not generating new textures every frame, it’s part of the system so not really under our control.  So if you have had a video paused for 5 minutes then it would show up as a possible leak, even though it should pick up when playback resumes. Does that make sense?

**Comment by driftboat** [comment]
1. Iphone13 Pro  iPad air5 Iphone14 Pro and Iphone 12 pm
2. Version is 2.5
3. Mp4
4. Play a boot vedio, stop when leaving vedio
![image](https://user-images.githubusercontent.com/247809/193274486-0f27dc1b-ff44-449d-80f0-eefe20692214.png)
![image](https://user-images.githubusercontent.com/247809/193274646-502a61f4-a130-4c57-9033-a8d4edf639f9.png)
5.  six  6.6m textures, total 40m

**Comment by MorrisRH** [comment]
Reproduced and fixed. The fill will be in the next release (version 2.6.4)

**Comment by Chris-RH** [comment]
The latest version is out. Please let us know if the issue has not been fixed for you.

**Comment by wqaetly** [comment]
I also encountered this problem. The version is 2.5.0. After reading this issue,
I am going to upgrade to the latest version. After upgrading to the latest version, is it necessary to manually destroy Texture to avoid leakage? Or does TextureProducer automatically clean up after MediaPlayer is Destroyed?

**Comment by MorrisRH** [comment]
The texture is automatically cleaned up when the media player is destroyed.

**Comment by wqaetly** [comment]
> 

thanks
