### ISSUE TITLE
WebGL unable to load HLS stream 

### ISSUE THREAD

**Issue by daudbutt18** [RenderHeads/UnityPlugin-AVProVideo#1381]
Access to XMLHttpRequest at 'https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1669666447/ei/L8KEY96qMqiojQSBiZT4Aw/ip/3.141.166.122/id/cH7VBI4QQzA.2/source/yt_live_broadcast/requiressl/yes/tx/24412678/txs/24412676%2C24412677%2C24412678%2C24412679%2C24412680%2C24412681%2C24412682/hfr/1/playlist_duration/30/manifest_duration/30/maudio/1/vprv/1/go/1/pacing/0/nvgoi/1/keepalive/yes/fexp/24001373%2C24007246/dover/11/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cplaylist_duration%2Cmanifest_duration%2Cmaudio%2Cvprv%2Cgo%2Citag%2Cplaylist_type/sig/AOq0QJ8wRAIgZqO1j1DatamF30YdodxAy0g0zFuzTZG-trs9o2DMA88CIDUkoasJvrceMGQHIs_jRkRjaPUJM8Fyuna3JhA7mHrW/file/index.m3u8' from origin 'http://webglkwiktrust.s3-website.us-east-2.amazonaws.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Chris-RH** [comment]
Hi @daudbutt18,

It is helpful if you fill out the issue template when seeking support.  We don't officially support WebGL, because it does tend to come with a lot of compatability issues across various browsers.  Here is some info about WebGL and streaming that might help: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#webgl
Also:
https://www.renderheads.com/content/docs/AVProVideo/articles/platform-webgl.html
https://www.renderheads.com/content/docs/AVProVideo/articles/supportedmedia.html#webgl

**Comment by CodeArgon** [comment]
Couldn't get it, It fetches URL from server and while playing it in player gives the CORS error on google endpoint due to CORS

**Comment by daudbutt18** [comment]
Couldn't get it, It fetches URL from server and while playing it in player gives the CORS error on google endpoint due to CORS

**Comment by Chris-RH** [comment]
Have you configured CORS on your server?
https://enable-cors.org/
Which browser are you having issues with?

**Comment by daudbutt18** [comment]
My site is hosted on S3 and CORS configurations are intact.
I am having issues with the chrome browser.

**Comment by Chris-RH** [comment]
OK, So info on configuring S3 bucket: https://hlsbook.net/how-to-serve-hls-video-from-an-s3-bucket/

There is also this plugin for chrome browser: https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en

**Comment by Chris-RH** [comment]
closed due to lack of reply
