### ISSUE TITLE
When you build Android, it is created in AndroidManifest.xml file. I want to delete it. Please tell me how.

### ISSUE THREAD

**Issue by darydol** [RenderHeads/UnityPlugin-AVProVideo#142]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by darydol** [comment]
When you build Android, it is created in AndroidManifest.xml file.
I want to delete it. Please tell me how.

**Comment by AndrewRH** [comment]
Isn't that just an option in the Unity Player Settings?  Change the internet permission mode in there..Otherwise it will be another plugin that is setting this.  AVPro Video doesn't set that permission.  Also search your project for old AndroidManifest.xml files in your /Assets folder

Does that help?

**Comment by darydol** [comment]
![1](https://user-images.githubusercontent.com/3705932/62675065-34228080-b9e0-11e9-805e-016e97146ad1.jpg)

**Comment by darydol** [comment]
![2](https://user-images.githubusercontent.com/3705932/62675071-3be22500-b9e0-11e9-8dc1-a67b381f6d45.jpg)

**Comment by darydol** [comment]
I only built 10 times, but there is an internet option in the contents of the AndroidManifest.xml file in the apk.
I want to delete

**Comment by AndrewRH** [comment]
Did you check your Player Settings in Unity?

Did you check inside the /Assets folder in Unity to make sure there isn't a AndroidManifest.xml file?

These are the only two ways I know...

Does that help?

**Comment by darydol** [comment]
There is not.
It is automatically generated even if you do not have it.

**Comment by RenderHeadsSte** [comment]
This is a strange one.  Maybe this issue, posted to the ExoPlayer github, offers some enlightenment:

https://github.com/google/ExoPlayer/issues/6019

We integrate an earlier version of ExoPlayer than the one mentioned here, but I suspect it is still pulling in the permission.  If this is the case, I am not sure we can offer any viable solution we can offer as updating the version of ExoPlayer we use is not on the roadmap for version 1 of AVPro.  It is, however, on the roadmap for version 2.

**Comment by AndrewRH** [comment]
Ahh good find @RenderHeadsSte  that looks like the issue.

@darydol I'm not sure if this will help, but you may be able to get around this if you switch the Video API from ExoPlayer to MediaPlayer (in MediaPlayer component, under Platform Specific > Android section).   It might not work as the manifest might still be generated but it's worth a try.

Otherwise it looks like we'll have to upgrade to ExoPlayer 2.10.2 to get access to that fix.

**Comment by AndrewRH** [comment]
@darydol 
And you checked that the Internet Access setting in Player Settings isn't set to Required?
![image](https://user-images.githubusercontent.com/5418126/65235066-cd5bb100-dacd-11e9-835c-47f71af1d29a.png)

Thanks,

**Comment by AndrewRH** [comment]
Closing as we're now on version 2.x and this issue is no longer related

**Comment by imbible** [comment]
I still see this issue on version 2.4.0 and 2.4.1. Importing AVPro imposes the ACCESS_NETWORK_STATE permission in AndroidMenifest.xml.
