### ISSUE TITLE
Video Tearing in Build

### ISSUE THREAD

**Issue by heritageint** [RenderHeads/UnityPlugin-AVProVideo#1441]
Trying to create a simple dual screen video player, a different video on each screen.  Media plays fine in the Editor, but when built (Windows 64-bit) shows lots of tearing in videos.  Have tried different resolutions and encodes.  Are there specific build settings required in the Player Settings?

**Comment by Chris-RH** [comment]
Could you fill in a full issue template and maybe include some images to demonstrate what you mean, please?

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com
