### ISSUE TITLE
With the disabled log tick is still logging messages

### ISSUE THREAD

**Issue by JuanObiJuan** [RenderHeads/UnityPlugin-AVProVideo#1453]
**Describe the issue**

Ticking the option disable Logging:

![image](https://user-images.githubusercontent.com/1729541/219648794-914b63aa-7626-4c36-a6d9-cfc95ccd1d14.png)

You can see log messages

![image](https://user-images.githubusercontent.com/1729541/219649113-9b48c3d9-2baf-4457-a339-fe641bcc13b7.png)

**MySetup:**
AVPro Video: v2.6.7 (plugin v2.6.7f1-ultra)
Target Platform: Android
Unity: v2020.3.44f1 WindowsEditor
OS: Desktop - MS-7B45 (Micro-Star International Co., Ltd.) - Windows 10  (10.0.19042) 64bit - English
CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz - 12 threads - 16326KB
GPU: NVIDIA GeForce GTX 1080 Ti - NVIDIA - Direct3D 11.0 [level 11.1] - 11127KB - 16384

**Comment by Chris-RH** [comment]
I've tested this on my Windows 10 machine with both 2.6.7 and 2.7.3 and I can't reproduce this I'm afraid. Targeting both Windows and Android.

**Comment by vr4content** [comment]
I have to say I'm really disappointed with the support. This is a top premium plugin regarding price, but this is the only thing is top here. The support is sadly not at the same level, Scripts optimization are neither top quality.
I had another issue, I took my time to send a project, but nothing can be reproduced, while still there is a clear problem on Android OES for others.
I have the feeling that most of the time support is trying just to get rid of the responsability as far as they can instead being constructive to solve problems.
So what are the options? Should I send you my PC by courier?

**Comment by Chris-RH** [comment]
Hi,
I'm very sorry that you feel that way.  

I've tested it several times myself. Window 10 and D3D11.  I've tested it in Unity 2020.3.44 and 2021.3.16. Windows target and Android target.  Trial and Ultra editions.  When I set disable logging there are no AVPro logs.
Is there a particular reason that you don't want the debug logs?
We are planning on improving logging and error reporting in AVPro Video version 3.

Unfortunately it is very difficult to diagnose and fix issues when we cannot reproduce them ourselves.

**Comment by Ste-RH** [comment]
I can only echo Chris’ sentiment that we are very sorry to hear you are not satisfied.

Regarding the logging. Yes, there is some logging in the plug-in that comes through regardless of that flag. We took the option to leave some important logging in so that people reporting issues with log at outputs were actually sending us something we could investigate on. We can certainly remove everything. But as Chris asks: why do you feel you need it removed? It does not harm performance in any measurable way. There is nothing we log that is per-frame.

You make mention of another issue involving OES. Was that via github? If so, what is the issue number? We can certainly look into it again in more depth.
