### ISSUE TITLE
3d sound 

### ISSUE THREAD

**Issue by LordLegionKeygard** [RenderHeads/UnityPlugin-AVProVideo#1456]
- Unity version: 2021.3.2f1 
 - AVPro Video version (AVPro Video - Core Windows Edition): 
 - Operating system version: Windows 10 Pro

3d sound worked on demo scene ( sample videos), but don't work when i load a video from youtube. In Unity, don't any build.

![Безымянный](https://user-images.githubusercontent.com/76789721/220290946-da679719-8b97-4df2-98b8-b266b7fe765b.png)

**Comment by Chris-RH** [comment]
AVPro Video doesn't officially support streaming from Youtube. This is because it is against their terms & conditions, and the streaming URLs are protected by javascript and server obfuscation. We have heard though that some people are using 3rd party tools to extract the streaming URLs. In theory these URLs could be playable in AVPro Video but this is not something we support.

Spatial Audio is a feature of the Ultra Edition, not the Core Edition.  The video files must be using a MKV file container and audio must be using the Opus codec encoded with Facebook Audio 360 tools.  It also needs a bit of setting up, please see the section in the documentation: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-360audio.html
