### ISSUE TITLE
When streaming live video across different regions using WOWZA, the video playback will automatically stop on the iOS system

### ISSUE THREAD

**Issue by XRSpace-Tingwei** [RenderHeads/UnityPlugin-AVProVideo#1528]
Hello, RenderHeads.

Issue & Reproduce :
We have encountered a situation where the live stream has stopped. We were watching the live stream from (US)Oregon's WOWZA server in Taiwan, and we found that the video playback would always stop within 40 seconds to 3 minutes. The video stops around 15:53-15:54. Please refer to the log below.
https://docs.google.com/document/d/1Maz8heEe_QYRVTaOhQa4RCIrYOnNxGQh/edit?usp=share_link&ouid=103467904099959233335&rtpof=true&sd=true

By tracking the log, we found an error in the Native AVPlayer.
`default	15:53:44.124913+0800	mediaserverd	<<<< FigStreamPlayer >>>> fpfs_StopPlayingItem: [0x5d2ebec90|P/AC] <0x5d2019e00|I/XBD.01>: Pausing, err=Error Domain=CoreMediaErrorDomain Code=-12312\`

We found that when this situation occurs, the AVPro status changes from "Stalled" to "Unstalled". From this, it appears that the video has stopped, but the AVPro status is notifying the video to continue playing, and the status of MediaPlayer.Control.IsPlaying() shows that the video is in the "Playing" state.

During our testing, several colleagues experienced video playback stoppage on their iPhones, while Android devices played the video normally.

Therefore, based on the above situation, it seems that this section of AVPro has not properly intercepted the status, which causes the upper layer to be unable to obtain the error condition. We can choose to restore the video or reopen it.

We have made other attempts, such as watching the WOWZA server in Taiwan while being located in Taiwan, which can maintain stable playback. I am not sure if there are other issues that have not been taken into consideration when accessing the live streaming link across different regions. The following is the relevant information:

AVPro Version : 
- AVPro Video - Ultra Edition_v2.7.3

Device information :
- iPad air 5th
- iOS 16.4.1

- iPhone XR
- iOS 14.8

UnityVersion :
- 2021.3.20f

Video : (We will be shutting down this live stream after the company's live event ends, so it may not have much reference value.)
https://cdn3.wowza.com/1/dGh2bllqNEVkc2Zi/OTBaNUc3/hls/live/playlist.m3u8

Video Spec:
- x264
- 1080p
- bitrate : VBR (1~2MB/s)

If anyone knows the reason for this issue, please kindly share with us. Thank you.

XRSPACE Tingwei

**Comment by Chris-RH** [comment]
This does appear to be a common apple problem that is more than likely caused by issues with stream upload/setup and exacerbated by poor connection.  Apple are rigorous when it comes to the specifications so any aberration is a full error.

Specifically from your error logs:

12318 "CoreMediaErrorDomain" "Segment exceeds specified bandwidth for variant"

12312 "CoreMediaErrorDomain" "Media Entry URL not match previous playlist for MEDIA-SEQUENCE 1725: **12142ut1h**/media_1725.ts vs **12143rxi2**/media_1725.ts"

It looks like the underlying root URL has changed.

We have had the above URL streaming for over an hour without problem. We do however have a very good internet connection.

More info on streaming for Apple on WOWZA:
https://www.wowza.com/docs/how-to-configure-apple-hls-packetization-cupertinostreaming
https://www.wowza.com/docs/how-to-improve-playback-of-lower-latency-apple-hls-streams

**Comment by Chris-RH** [comment]
Still working here after 24 hours.
