### ISSUE TITLE
Window size changes not being applied while playing media on Standalone(Windows).

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#1579]
Window size changes not being applied while playing media on Standalone(Windows).

Our project uses the [Unity As a Library](https://docs.unity3d.com/2020.3/Documentation/Manual/UnityasaLibrary.html).
We found that when we build Unity including AVPro and integrate it into our project, it doesn't apply properly when we change the window size.
The issue is not reproduced in AVPro version 2.6.5, issue is being reproduced in version 2.7.x or 2.8.x.

I sent you an email with a guide on how to integrate with the sample project.

Unity Version: 2020.3.32f1
OS: Windows 10

**Comment by Chris-RH** [comment]
Hi, 

I'm not sure, specifically, what you believe AVPro is/isn't doing that is causing this issue?
Are you testing an exact like for like with previous and newer AVPro versions?
Can you pinpoint which version change has resulted in this issue?

**Comment by dw8869** [comment]
> I'm not sure, specifically, what you believe AVPro is/isn't doing that is causing this issue?

Problems are occurring only when playing videos using AVProVideo.
If you don't play the video, the problem won't occur. For that reason, I think there is a problem in AVProVideo.
In addition, it does not occur in the 2.6.5 version, but occurs in the 2.7.x or 2.8.x version.

> Are you testing an exact like for like with previous and newer AVPro versions?

Yes

> Can you pinpoint which version change has resulted in this issue?

Probably caused by major version updates from 2.6 to 2.7.

**Comment by Chris-RH** [comment]
AVPro Video version 2.8.2 has been released.  Please let us know if this is still an issue.

**Comment by dw8869** [comment]
Issue has been solved. Thank you

**Comment by dw8869** [comment]
@Chris-RH 
I don't know if this is a regression for this modification, but if you change the video repeatedly, the video resolution will be fixed intermittently and output. (It is fixed at 1920x1080 unconditionally)

You can update and test the AVProVideo 2.7.4 version in the project I emailed you.

**Comment by Chris-RH** [comment]
Which AVPro version?
What sort of videos?
What do you mean by "repeatedly" Do you mean spamming it or just playing a sequence of different videos?

**Comment by dw8869** [comment]
> Which AVPro version?

Reproduced in version 2.7.4.

> What sort of videos?

URL 1 : https://jumpvrapi-mscdn-api-dev.azureedge.net/blobpublic-dev/space_mbr/2023/06/07/1135941/128527_1_0597_f39a8e2e-abc6-4445-9790-d714ce89a8a7/hls/128527_1_0597.m3u8
URL 2 : https://jumpvrapi-mscdn-api-dev.azureedge.net/blobpublic-dev/space_mbr/2023/06/07/1135941/128527_1_0458_7bf992b0-9b62-4191-95b4-1e6dd0aecf36/hls/128527_1_0458.m3u8


> What do you mean by "repeatedly" Do you mean spamming it or just playing a sequence of different videos?

I tried to play 2 videos alternately with 1 player as shown below.

1. OpenMedia (URL 1)
2. CloseMedia (URL 1)
3. OpenMedia (URL 2)
4. CloseMedia (URL 2)
5. OpenMedia (URL 1)
6. ...

**Comment by Chris-RH** [comment]
Have you tried using the playlist feature?
https://www.renderheads.com/content/docs/AVProVideo/articles/component-playlist-media-player.html

**Comment by dw8869** [comment]
@Chris-RH Maybe, not reproduce.
But we can not use playlist feature.

**Comment by dw8869** [comment]
@Chris-RH any information?

**Comment by companyofpotato** [comment]
@Chris-RH Hello, I'm working on same project, and same issue occured.
When video is loaded, sometimes its texture size is 1920x1080 regardless of video resolution.
I found that when it happens, texture pointers are same even though width and height of each textures are different, but I don't know why.

Here is details.

- Unity version : 2020.3.48f1
- AVPro version : 2.8.5 ultra
- OS : Windows 10
- Video specs : 1054 x 1054
- Video
https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/30142311/96ae248f-58a0-476b-8b53-96223834c620

It doesn't reproduce on demo Scene and Unity Editor. **It only reproduces on Windows version of project.**

Analyzing this issue, I added some log to `UpdateTexture` method of `WindowsMediaPlayer` class.
[WindowsMediaPlayer.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/13376505/WindowsMediaPlayer.txt)

And this is log file.
[2023_1116_1601_Player.Log.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/13376516/2023_1116_1601_Player.Log.txt)

It reproduces on 16:02:06, 16:02:13, 16:02:16.
In each frame, width and height of `_texture` are compared with the width and height of `Native`.
Even though width and height are different, texture is not recreated because pointers of each textures are same.
If situation is same on Unity Editor, pointers are different so that texture is recreated.

Is there any reason why two pointer values are same?
