### ISSUE TITLE
H265 with meta data 3D videos issue

### ISSUE THREAD

**Issue by WayDanny** [RenderHeads/UnityPlugin-AVProVideo#159]
Dear Support,

We wrote you some time ago about a problem with VR videos in H264 codec.
For unknown reason Movies & TV plays only one eye with possibility to move around sceen.
This breaks AVPro VR video renderer, cause it receives texture with only one eye.
This cause some meta data with stereo settings and screen type brought from original movie.
Unfortunately removing this meta only from file headers is not enough. Meta seems to be encoded somewhere deep inside stream. So we had to re encode such videos frame by frame.

After latest Windows update the same problem went to h265 videos aswell. It started to pull meta through h265 stream and now video plays with only one eye. There were no such a problem before latest update.

Here's an example of the video:
<erm, not really suitable for a public forum, please send any links to unitysupport@renderheads.com in the future>

Could you suggest a solution to this problem, please.

We use Unity 2017.4.31 (LTS) and 2018.4.6 (LTS)
AVPro 1.10.0.
Windows 10 Pro.

To reproduce simply open video from above.

Best regards,
Danny.

**Comment by AndrewRH** [comment]
Yes, some videos have per-frame stereo metadata that is more difficult to remove.

Our Windows video player implementation doesn't handle stereo videos with embedded stereo metadata and ends up only decoding one eye.  The videos should be left-right or top-bottom packed but without any stereo metadata to play correctly in Windows when using our player.

Ideally the videos should initially be encoded without any metadata.

If you need to remove the metadata, you can follow some of the steps in our PDF manual documentation.  One of these more extreme methods is to encode the video to FFMPEG's .NUT format and then convert it back again:

Windows - Why isn't my stereo top-bottom or left-right video displaying correctly?

If your stereo video is only decoding one of the views then this is because there is stereo metadata encoded within the video which causes our Media Foundation decoder to interpret incorrectly.  The only way to currently solve this is to remove the metadata from the video.  One way to do this is using FFMPEG:

ffmpeg -i %1 %1-video.nut
ffmpeg -i %1-video.nut -crf 10 %1-stripped.mp4

We have also had reports that this works:

ffmpeg -i in.mp4 -map_metadata -1 -c:v copy -c:a copy out.mp4  

Does that help?

**Comment by tufeixp** [comment]
Wish this can be fixed some day!!

**Comment by AndrewRH** [comment]
This is fixed in 2.0 which we'll start releasing beta versions of soon
