### ISSUE TITLE
360 Video Playback Quality on Pico OS

### ISSUE THREAD

**Issue by DonutVR** [RenderHeads/UnityPlugin-AVProVideo#1615]
We are having issues getting 4k 360 video to playback lag-free in our Unity Project. 

Project Overview: Users sit 'inside' a 3D model of a car and 360 video plays 'outside' the car windows. Users need to look around and spot as many motorcycles as they can to score points. The project is for motorcycle awareness/safety training. Here is a video link to a screen recording of the original project (https://drive.google.com/file/d/1yY8rumCIZkJxdGGQfqbTbBo8cu-XaATS/view?usp=drive_link). 

The project was originally developed for the Oculus GO. Our client has requested we update the project to run on the latest version of the Pico OS. 

Unity version: 2021.3.24f1
Target platform: Pico G2 4K (PUI v4.0.7)
Video: 4096x2048 at 30fps and 40mpbs H.265 

Questions: 
- Would you recommend different video render settings?
- Do you have any suggestions on shaders to run in Unity? 
- Do you have any sample projects that leverage 360 video you can share? 
- Recommended settings for the Mediaplayer component?

**Comment by Chris-RH** [comment]
I would generally follow the Headjack guidelines: https://headjack.io/knowledge-base/best-video-resolution-for-pico-headsets/
Have you tried using H264 instead of H265?
We'd generally recommend starting with our 360 demo scene and moving  on from there.
More info on our shaders here: https://www.renderheads.com/content/docs/AVProVideo/articles/usage-shaders.html
