### ISSUE TITLE
Question about using the cache feature.

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#1630]
Question about using the [Caching](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-caching.html) feature.

1. What happens when I call `AddMediaToCache` when  device storage is low? Will it be a failure? Or will some cache data be deleted?
2. Can you add functions the cached list and cached data size?
3. Can I specify a max cache size?

**Comment by Ste-RH** [comment]
Android:

1) We use the [NoOpCacheEvictor](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/cache/NoOpCacheEvictor.html), you should just receive a failure, nothing should be deleted.  It is up to the developer to manage cached videos, space they take up, available space prior to caching, failure to cache a video due to not enough space.

2) This is something we would have to look into adding.  Currently we store no lists of what is cached, so would have to look at if we can obtain this via the database that is kept by the API.  I think we can easily return the 'space used by cache'.

3) This would only make sense if we used an eviction based system, which we do not currently.  It is up to the developer to specify whether something is allowed to be cached or not - but I guess there is an argument that it would be of use to have 'space used by cache' as mentioned in (2).


iOS:

1) As with Android, a 'no eviction' strategy is implemented.  Caching will just fail when disk space runs out.

2) We do store a list of cached videos, but currently 'size on disk' is not part of that.  We would need to investigate if this is possible.

3) Same as with Android.

**Comment by Ste-RH** [comment]
I have submitted an 'enhancement' issue - #1633

**Comment by dw8869** [comment]
@Ste-RH 
Can I also add the ability to retrieve cached files?

For example, I would like to create a function to delete old cache files using the function of #1633.

**Comment by Ste-RH** [comment]
You want to be looing at 'RemoveMediaFromCache'

The documentation has all the relevant information : https://www.renderheads.com/content/docs/AVProVideo/articles/feature-caching.html

OR do you mean _all_ cached videos?

**Comment by dw8869** [comment]
What I mean is the **all cached videos**.

We cannot determine which videos are currently cached, so we need to implement a separate list management function.

**Comment by Chris-RH** [comment]
Closed due to creation of enhancement.
