### ISSUE TITLE
How to play several videos which taking a lot of storage space with Avpro?

### ISSUE THREAD

**Issue by yq-Liang** [RenderHeads/UnityPlugin-AVProVideo#1657]
Hello,
I'm trying to play several 8K videos over 2GB, and I'd like to know that if there are some ways to manage the videos. I've learned that Avpro supports live stream and can load videos from local path. Except that, I'd like to know what other ways can make Unity play videos with a lot of storage space? For example, I can load the specified video from cloud with some plugins...

**Comment by Chris-RH** [comment]
It depends a lot on what platforms you use and what else is going on in your program.

Hardware has a limit to how much video they can decode simultaneously. It may be able to load 4 1080p videos and decode them, but only 1 4K video. This is especially true on mobile / portable VR platforms. If you use up all the capabilities of the hardware video decoder, then a second video will often not be loadable until you have unloaded the first video.

We have information about streaming to various platforms here: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html
We have notes about how to best encode media here: https://www.renderheads.com/content/docs/AVProVideo/articles/encoding-notes.html

Large videos can be downloaded and played from the persistentDataPath, rather than Streaming Assets: https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html

Otherwise, if you use the Ultra version, it has caching feature available on android and iOS platforms: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-caching.html
