### ISSUE TITLE
Dose  AVPRO   support h264.2-pass?  windows os

### ISSUE THREAD

**Issue by qinlinger1** [RenderHeads/UnityPlugin-AVProVideo#1672]
hello man 
I have a problem     Dose  AVPRO   support h264.2-pass?

thank you

**Comment by Chris-RH** [comment]
Hi @qinlinger1 

Did you mean to post this in AVPro Video github?  As far as I'm aware there shouldn't be any issues decoding H264 2 pass videos.  If in doubt, you can always test your video in our free, watermarked trial version: https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases

As far as encoding h264 2 pass in AVPro Movie Capture, its not something that is currently supported.  It would rely on the underlying platform to support it and for us to then add support for it in the asset.  It  could only be done in offline rendering mode.
Otherwise there is always the possibility to convert files using ffmpeg. https://trac.ffmpeg.org/wiki/Encode/H.264

**Comment by qinlinger1** [comment]
hi Chris-RH:
When i use avpro(display ugui) play video (H264 2 pass) ，the Unity is stuck.
 Dose AVPRO support play h264.2-pass video?

**Comment by Chris-RH** [comment]
Could you send us a video sample please? unitysupport@renderheads.com

**Comment by qinlinger1** [comment]
hi Chris-RH:
I sent it over
thank you

**Comment by Chris-RH** [comment]
I've had a quick look at your video.  The issue is that it uses 4:4:4 chroma sub-sampling profile, which is not supported by Media Foundation or WinRT.  The workaround is to use 4:2:0 8-bit videos only for H.264 on Windows, or use DirectShow API with LAV Filters installed.
