### ISSUE TITLE
Audio out of Sync - 360 Player & Ambisonic MKV file 

### ISSUE THREAD

**Issue by danWorkUK** [RenderHeads/UnityPlugin-AVProVideo#1681]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
When loading and playing an mkv file with spatial audio, the sound is out of sync with the video playback. 

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.0.f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): trial - looking to purchase

**To Reproduce**
1.  Load in mkv file with spatial audio 
2. Enter play mode 

Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi, please could you fill in the entire form.  
It would be helpful if you could also provide the video that you are using to test with.  You can email this to unitysupport@renderheads.com

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Any more info @danWorkUK ?

**Comment by Chris-RH** [comment]
Closed due to lack of response
