### ISSUE TITLE
Most efficient way to stream from a given time

### ISSUE THREAD

**Issue by tomkail** [RenderHeads/UnityPlugin-AVProVideo#1733]
Hi! We want to stream some very short (5s) clips of much longer videos (5 mins) from a given timestamp. We're streaming from video hosted on Firestore/AWS. Once complete we'll stop or loop them at that range. We're trying to find the most load-speed efficient way to do it.

We did some tests and have some questions:

1. It doesn't seem that it's possible to load at a given point via videoPlayer.Load(), and it seems that the video begins buffering from time 0 when Load is called (which we don't want). We did spot videoPlayer.Control.OpenMedia(), which features an "offset" variable, but changing the code to get it to load from a different point didn't seem to do anything.

2. It seems Seek doesn't work until videoPlayer.Control.CanPlay() is true, but Seeking after this point visibly causes the frame to jump from the current to the target time (implying that it's wasted time buffering bits we don't need). If there's any advantage to using SeekFast or similar in this way we'd love to know.

3. There seems to be various bits of code for managing buffering. Can we explicitly tell the player to buffer a certain time range and then play when that's ready?

4. If we load/unload several times and monitor load speeds, they tend decrease each time from the first load until they settle at a significantly lower time. Do you have any idea what might cause this?

5. What will affect load times, generally speaking? Does media length make any difference at all? Anecdotally it doesn't seem to. I'm assuming that bytes-per-second does though. We don't have total control over how the files are encoded, but if there's any good tricks we should make use of we'd love to know.

I've done our tests in editor on OSX, but our target platform is iOS.

**Comment by MorrisRH** [comment]
Are you streaming mp4 of HLS media? If HLS make sure you include an iframe manifest otherwise seeking is going to be significantly slower. Seeking in a streamed mp4 is not going to be great regardless.

1. There is currently no support for starting playback from a specific time. The offset is for file based media only and only supported on Android, it allows a weak form of protection whereby a movie can be embedded in another file.
2. Seek requires that the video has been opened and the ReadyToPlay event has fired. SeekFast will seek to the nearest key frame so reduces the number of frames that need to be decoded in order to show the frame at the time you request. It does sound like SeekFast is what you should be using. As mentioned above, if using HLS make sure you have an iframe manifest.
3. Buffering is handled by the system so we have little control over it.
4. Caching, again this is at a system level so we have little control over it
5. For streamed media it's all down to the server and caching infrastructure you employ. Having a lower bitrate will mean playback can start sooner as less data will be required but this will impact the quality of the media you're playing.

My suggestions would be as follows:
1. Make sure autoplay is false when opening the media
2. Seek when you receive the ReadyToPlay event
3. Wait for the Seek to complete (the FinishedSeeking event) before calling play
