### ISSUE TITLE
[Android] Streaming playback does not work with exo player.

### ISSUE THREAD

**Issue by Blidkail** [RenderHeads/UnityPlugin-AVProVideo#1744]
**Describe the issue**
I am playing a video using URL on the Android platform. However, there is a problem that some specific videos do not play, are frozen on the first screen, and only sound is played. The video API uses Exo Player. I need to use Unity for Audio Output, so I use Exo Player. The problem can be solved by using Media Player, but the problem is that the sound is not recorded when recording because the sound does not come to Unity, so I cannot use it. What should I do?
This is url link: https://asset.nupy.life/video/16025.20240124161347.mp4

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.16f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.9.1 / ultra
 - Operating system version: macOS 14.1(23B74)
 - Device model: Samsung Galaxy S9
 - Video specs (resolution, frame-rate, codec, file size):  813x1280/ ? / MPEG-4 AAC, H.264 / 2.3MB
 
**To Reproduce**
1. Set URL in Media Player
2. Set to autoplay.
3. Use Exo Player on Android platform
4. When playing, the video stops at the first screen, and only sound is left.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
![20240125_1](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/24913368/dc0044a8-dacb-48fe-98d2-4ff62759e8d0)

**Videos**
If applicable, add a copy of your video or the URL

https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/24913368/8f7fb91c-de22-4901-95d8-c3643bf211ae

**Comment by Chris-RH** [comment]
Hi, 

There were two issues with the video supplied:
1. It was not encoded with faststart, so the whole video had to be downloaded before it started playing
2. The video and audio were not interleaved; it is all the video frames followed by all the audio frames, so the decoder either waits for everything to be available or has to jump back and forth.  Some APIs seem to be able to handle this (Android Mediaplayer and Windows DirectShow) while others can't (Exoplayer and Windows MediaFoundation).

We re-encoded the video so that the audio and video are interleaved, and faststart is enabled.  It played fine after this.
Command used:
ffmpeg -i <input video> -c:v h264_videotoolbox -b:v 2M -c:a libfdk_aac -b:a 128k -movflags faststart <output video>
