### ISSUE TITLE
Fix it

### ISSUE THREAD

**Issue by penpenpender** [RenderHeads/UnityPlugin-AVProVideo#1772]
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

I'm having that issue within the VRChat game, and I can't watch the video. FIX IT

**Comment by Chris-RH** [comment]
Hi, 
I'm afraid that we can't help you if you don't supply more details.  Please can you take the time to fill out the full issue form. Thank you.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com
