### ISSUE TITLE
How to play h265 video without installing third party software

### ISSUE THREAD

**Issue by lyg2260123** [RenderHeads/UnityPlugin-AVProVideo#1777]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
We want to use av pro to play h265 video in the project, on the basis that the user does not install third party software. We know that setting up directshow, and then installing the lav decoder, is one way. But this requires prompting the user to install the lav decoder. There are ways out of the box, such as proactively helping users install lav decoders when running our projects, or installing third-party software. Is there any way to achieve this。Tks

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.15
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.5.4 ultra
 - Operating system version: windows 11
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 1920*1080 ，24fps，h265，8MB

**Comment by Chris-RH** [comment]
The issue is that Windows no longer comes with the H265 codec.  We have no idea why they stopped doing so.  Users can install it from the Windows Store, they just need to search for HEVC extension.
We rely on the hardware used to decode.  We try and use as few external products as possible due to potential copyrighting issues.
