### ISSUE TITLE
Playback HLS from local storage

### ISSUE THREAD

**Issue by SteenPetersen** [RenderHeads/UnityPlugin-AVProVideo#178]
**Describe the bug**
I have been asked the post what seems like a possible bug ([ref](https://forum.unity.com/threads/released-avpro-video-complete-video-playback-solution.385611/page-73#post-4963001))

I am building a simple video player for the oculus GO and loading the .m3u8 file along with its .ts files into a folder on the headset. I find the file by accessing the oculus Go's internal storage and finding the location where I placed it. I have done this before for another app on the Oculus Quest with no issue. My debug log says that it does find the video, but it wont play it. Just a black screen, no sound either. Works fine in the editor:

**Your Setup (please complete the following information):**
 - Unity version: **2019.2.0f1**
 - AVPro Video version:**1.10.00**
 - Operating system version: **Windows 10 - Building for Android**
 - Device model: **Oculus Go**

**To Reproduce**

**1.** Take A high resolution .mp4 video and convert it to .m3u8 with FFMPEG using the following command:

`ffmpeg -i inputVideo.mp4 -profile:v baseline -level 3.0 -start_number 0 -hls_time 10 -hls_list_size 0 -f hls nameOfTheHLSvideo.m3u8`

**2.** Load the resultant file into a folder on the oculus headset (In my case Android - data - _Videos)

**3.** Access the file from unity Editor and confirm it plays when finding it on a desktop

```
path = "D:\\SomeFolderOnYourDDrive\\nameOfTheHLSvideo.m3u8";

mediaPlayerVariable.OpenVideoFromFile(
MediaPlayer.FileLocation.AbsolutePathOrURL, 
path, 
true
);
```

**4.** Now try and see if it can be loaded on the oculus Go:

```
if (Application.platform == RuntimePlatform.Android)
   {
      rootPath = Application.persistentDataPath.Substring(
         0, 
         Application.persistentDataPath.IndexOf("Android", StringComparison.Ordinal));
      path = Path.Combine(
          Path.Combine(rootPath, "Android/Data/_Videos"), 
          fileName);
   }

if (!File.Exists(path))
    _debugText.text += "\nFile NOT found!\n\nChecking Path " + path + "\n\n";

mediaPlayerVariable.OpenVideoFromFile(MediaPlayer.FileLocation.AbsolutePathOrURL, path, true);
```

**Result**

The Debug log that should fire saying that it cannot find a video is **NOT** fired meaning that it does in fact find the video but the screen is just black, no sound.

**Comment by SteenPetersen** [comment]
Any news on this?

**Comment by RenderHeadsSte** [comment]
@SteenPetersen Sorry for the slow response.

So you are trying to playback an HLS stream where the manifest and segments are stored locally to the Android device?

**Comment by RenderHeadsSte** [comment]
We shall be closing this bug soon should there be no response forthcoming

**Comment by RemyRM** [comment]
@RenderHeadsSte I am running into the same issue but on generic Android/iOS devices (If you rather have me open up a separate question let me know, decided this issue is close enough to mine to reply instead). 

As for why *I* would like local HLS stream playback  (and assume OP wants something similar): 
In our Unity application we play back quite a lot of different, but not too lengthy videos. To save on mobile data usage we store the last N .ts files (and their appropriate .m3u8 headers) in the persistent data path, so that if the user decides to rewatch that video (granted that it hasn't been recycled away) they do not need to stream it again , but instead play it from the local storage.

Due to also wanting to support low-end devices caching in memory is not an option, having the ability to save HLS streams to the persistentDataPath and playing them back seemed like a good alternative.

My current (working) flow looks like this when a user wants to view a video for the first time:
 - User requests to play Foo.m3u8.
 - I check if Foo.m3u8 exists in the PersistentDataPath (it isn't there)
 - I set the sourcepath to Absolute or URL
 - I direct the request from the mediaplayer to localhost (http://127.0.0.1:port/Foo.m3u8).
 - A background thread has a HTTPListener listening on the above address, and forwards the request to the server
 - The HTTPListener receives Foo.m3u8 from the server
     - The HTTPListener sends Foo.m3u8 to the Response of the mediaplayer's request for immediate playback
     - A new thread gets fired up that saves Foo.m3u8 to the PersistentDataPath
 -  This repeats for the sub .m3u8 and .ts files

Then the flow I would like for when a video exists:
 - User requests to play Foo.m3u8
 - I check if Foo.m3u8 exists (it does)
 - Sourcepath is set to relative to persistent data folder
 - I set the m_VideoPath to /Foo.m3u8
 - Repeat for sub .m3u8 and .ts files

I didn't know about HLS only being able to be played back if the source is HTTP, is this something Apple forces through their implementation? 

Somewhat related is [this feature request](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/25) I put in last year, asking if saving HLS streams to local storage would be possible through AVPro, but I guess that would be a useless feature if it can't be played back due to implementation anyway.

Thank you for your time!

**Comment by RenderHeadsSte** [comment]
Converting this from a bug to an enhancement.

**Comment by fingerx** [comment]
any update news@RenderHeadSte@AndrewRH thanks

**Comment by RenderHeadsSte** [comment]
The ability to playback HLS from local storage was added to Android in v2.0.2.  We are not able to back port this to v1.x.

**Comment by visjack** [comment]
Has this been added in Version 3? I see "Play local, remote and adaptive (HLS/DASH) videos" advertised but I can't find any more specifics about it other than the mention here https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1560#issuecomment-2178863779

**Comment by Ste-RH** [comment]
Yes @visjack.  It persists into v3.x
