### ISSUE TITLE
Video freezes every loop

### ISSUE THREAD

**Issue by damtakon** [RenderHeads/UnityPlugin-AVProVideo#1796]
The video freezes every loop.
My videos last from 2 to 6 seconds, is there any way to optimise Loop to leave it all in the buffer and not reload every time or something like that?
On android there is also often a problem that the video just stops using Exo Player.
Tried to change Audio Mode but it doesn't help, for me the most stable was Unity.
Maybe there is a possibility not to load and play audio at all.

 - Unity version: 2022.3.14f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.9.3 core
 - Operating system version: iOS
 - Device model: iPhone 14 Pro Max
 - Video specs (resolution, frame-rate, codec, file size): 
     - resolution: 1280x1280,
     - frame-rate: 24
     - codec: H264
     - file size: 4,437 KB

1. Set video to play
2. Settup settings 
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/70834708/219ddc05-06e7-4d3e-9970-14ebf386dc6f)
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/70834708/90d142b3-c0c7-44cc-a16a-e64680c323c4)
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/70834708/050550aa-c11b-40c1-b165-4050e6391e7e)
3. Play video at full screen

**Logs**
failed to reserve 8192 bytes in the audio capture buffer (every second repeat)

**Videos**
https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/70834708/679b977e-a43a-4a57-b6fc-3ff804aaf5bc

Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi @damtakon 

"failed to reserve 8192 bytes in the audio capture buffer" - I believe this is caused by not making an audio output component in your scene.

Having looked at the track that you have provided
- It also appears to "freeze" at the end of the loop when played on VLC
- The audio track has the following information:
   - Duration : 3 s 0 ms 
   - Source duration : 3 s 51 ms 
- So if "audio source duration" is being read as the total track duration then it will "freeze" during the difference between video length and audio source duration.  Basically the audio track is finishing while the video track has no updates until it loops.
- As there is no actual sound coming from the audio track, it can be removed from the video and then it will loop properly.  Use the following command:
- ffmpeg -i [input.mp4] -c:v copy -an -movflags faststart [output.mp4]

See here:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/102963025/2a2c2fe8-cabd-40e6-a8fc-6562d736f8e8

If you did need to keep an audio track, then it gets a bit more complicated.  You would need to split the audio and video tracks.  Then you would need to trim the audio track to the correct length and put them back together.

**Comment by damtakon** [comment]
`"failed to reserve 8192 bytes in the audio capture buffer" - I believe this is caused by not making an audio output component in your scene.`

audio output component on the scene is there, maybe this is due to what you described below

Thank you for your reply
