### ISSUE TITLE
How to resolve the Texture to RenderTexture?

### ISSUE THREAD

**Issue by hyuhyua** [RenderHeads/UnityPlugin-AVProVideo#1819]
The Docs said:"In the near future we plan to add a "Resolve" feature which will resolve the textures to a RenderTexture so that our shaders won't be required."
So, If I want to use this feature now, how do I do it?

**Comment by hyuhyua** [comment]
AVPRO_FEATURE_VIDEORESOLVE
Should I open this Define? And then?

**Comment by Chris-RH** [comment]
Hi @hyuhyua 

We have a [resolve to render texture component](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/component-resolve-to-rendertexture.html).  This component will allow you to specify your own RenderTexture via the Inspector, or via C# scripting using the property ExternalTexture. Otherwise it will generate an internal RenderTexture which you can get via C# usign the property TargetTexture.

**Comment by hyuhyua** [comment]
Thank you very much!
