### ISSUE TITLE
QA for tricky timelines

### ISSUE THREAD

**Issue by drew-512** [RenderHeads/UnityPlugin-AVProVideo#1820]
Hi!  Quick question -

Is there link to a stream where the seekable range is a subset of the total duration?  Or where the stream "start time" is non-zero.

This would be helpful at QA-ing our fancy UI that we're looking forward to showcasing!

Thanks,
Drew

**Comment by Chris-RH** [comment]
Hi, no we don't have anything like that.  Its the type of thing that you'd probably need to make yourself for testing.

**Comment by drew-512** [comment]
But then how do you guys QA this?   

The point is, I'm trying to understand the scenarios where the "start time" isn't 0.   My assumption was for partial streams where the initial part is somehow unavailable.

**Comment by Chris-RH** [comment]
The issue is that:

1. External streams can be taken down or changed at any time, so we can't rely on them for consistency.  
2. They can also be poorly encoded, so may cause different problems.
3. The servers can be poorly set up for streaming.

So if you want to test something specific then it makes sense to make your own stream.
