### ISSUE TITLE
smooth playback rate change

### ISSUE THREAD

**Issue by LabStark** [RenderHeads/UnityPlugin-AVProVideo#184]
Is it possible to change the playback rate of a video smoothly? without stop it? 

I need to change it frequently and I'd like a smooth reproduction...

thank you!

 - Unity version: 2017.4.82f1
 - AVPro Video version: 1.10.00
 - Operating system version: 10

**Comment by RenderHeadsSte** [comment]
Apologies for the slow response.

Are you still having this issue?  Could you provide more information (target operating system, video playback API used, video format information, etc)

**Comment by LabStark** [comment]
Target operating system: windows 10
video playback API:  Media Foundation
video format: h.264 1920X1080

But I can change it. Now I'm using HAP video files for changing plaback rate.

I'm looking for the "best" codec for a smooth playback...

**Comment by AndrewRH** [comment]
Changing playback rate dynamically is quite an expensive operation in our implementation, so usually there is some delay.  There are ways to improve this though:

H.264 could be good for smooth playback during rate change - but you have to encode the video so that it is more suitable for this.  Basically this meany need to use more keyfarmes (or all keyframes) in your encoding and also disable a lot of encoding options.  We cover how to do this in the PDF documentation in the section about seeking and playback rate.

Hap is good for this because it is a simple codec and is only keyframes, but you can do this with H.264/H.265 with proper encoding.  I think Hap will always be fastest though as it is designed for this use case.

I hope this is helpful for you.  I will close this ticket now.  

Thanks,
