### ISSUE TITLE
How can i check the support media ?

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#1855]
Test URL
* https://stg.cms.treal.xyz/output/cd89fa770af8622277fe008afe5bfd31/hls/cd89fa770af8622277fe008afe5bfd31.m3u8

I checked [this](https://www.renderheads.com/content/docs/AVProVideo/articles/supportedmedia.html) document, and the video I tested is considered to be a supported video according to the document.

I tested on Windows(Media Foundation), but printed an error logs.

```
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
RenderHeads.Media.AVProVideo.MediaPlayer:Update()
```

How can i check the supoort media ?
Do you have any tools that I can check?

**Comment by Chris-RH** [comment]
The issue is that Windows no longer comes with the H265 codec. We have no idea why they stopped doing so. 
Users can install it from the Windows Store, they just need to search for HEVC extension.
You can also install LAV filters and use the DirectShow API


We rely on the hardware used to decode. We try and use as few external products as possible due to potential copyrighting issues.

**Comment by dw8869** [comment]
Is there a way to put codecs in the project/app?

**Comment by Chris-RH** [comment]
no, there isn't

**Comment by dw8869** [comment]
There is no other way than for the user to install a separate codec. Is that right?
