### ISSUE TITLE
RTMP url fails to open 

### ISSUE THREAD

**Issue by ViVRPlus** [RenderHeads/UnityPlugin-AVProVideo#1859]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

Hi, 

I'm having an issue with playing my OBS studio stream in unity using the trial version
I worked last week, and now regardless of my many tries, it will not an instead displays "Failed to open rtmp://....."

The thing is, when I try and watch the stream through VLC media player for example, it works fine.  Additionnaly, I thought the issue might come from my scene/component's but even when I use the sample scenes I'm getting this issue

Has anyone experienced this issue before and could help me with this? Is it simply because the trial version has some sort of an expiration date? 

I'm really close to the end of my project, and this one feature that used to work fine doesn't work anymore so I would really appreciate any help I can get

Have a great day 

Axel

**Comment by Chris-RH** [comment]
Hi @ViVRPlus 

Please can you fill in a complete issue report form.  Please note that AVPro Video doesn't have strong support for RTMP as live streaming is not the focus of this plugin and most operating systems do not have good native support for them.
More info [here](https://renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html)

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by ViVRPlus** [comment]
Hi, here is the full report : 

I'm having an issue with playing my OBS studio stream in unity using the trial version
**It was working fine last week**, and now regardless of my many tries, it will not an instead displays "Failed to open rtmp://....."

The thing is, when I try and watch the stream through VLC media player for example, it works fine. Additionnaly, I thought the issue might come from my scene/component's but even when I use the sample scenes I'm getting this issue

___________

Your Setup (please complete the following information):

Unity version: 2022.3.27f1
AVPro Video version (number and edition (trial/core/ultra/enterprise)): trial version 3.0.1
Operating system version: windows 11
Device model: asus tuf gaming a17
Video specs (resolution, frame-rate, codec, file size): res : 1920x1080, 30 FPS, codec x264 (I think), and as it's live streaming there is no size i guess..


______ 

to reproduce

1) create a new 3D project, and import the trial plugin

2) install lav filters on computer

3) 

3) add a media player component, select absolute path as the source and use rtmp://127.0.0.1:1935/live/ URL. Use windows in the platform specific tab, and change the video api to direct show. In the direct show API options, type LAV video decoder

4) try loading the video : error message "failed to open url..."

Here is the full log :
 [AVProVideo] Failed to open rtmp://127.0.0.1:1935/live/test
UnityEngine.Debug:LogError (object,UnityEngine.Object)
RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:617)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia (bool) (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:509)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia (RenderHeads.Media.AVProVideo.MediaPathType,string,bool) (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:488)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:OnInspectorGUI_Source () (at Assets/AVProVideo/Editor/Scripts/Components/MediaPlayerEditor_Source.cs:81)
RenderHeads.Media.AVProVideo.Editor.AnimCollapseSection:Invoke () (at Assets/AVProVideo/Editor/Scripts/AnimCollapseSection.cs:51)
RenderHeads.Media.AVProVideo.Editor.AnimCollapseSection:Show (RenderHeads.Media.AVProVideo.Editor.AnimCollapseSection,int) (at Assets/AVProVideo/Editor/Scripts/AnimCollapseSection.cs:146)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:OnInspectorGUI_Settings () (at Assets/AVProVideo/Editor/Scripts/Components/MediaPlayerEditor.cs:436)
RenderHeads.Media.AVProVideo.Editor.AnimCollapseSection:Invoke () (at Assets/AVProVideo/Editor/Scripts/AnimCollapseSection.cs:51)
RenderHeads.Media.AVProVideo.Editor.AnimCollapseSection:Show (RenderHeads.Media.AVProVideo.Editor.AnimCollapseSection,int) (at Assets/AVProVideo/Editor/Scripts/AnimCollapseSection.cs:146)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:OnInspectorGUI () (at Assets/AVProVideo/Editor/Scripts/Components/MediaPlayerEditor.cs:404)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Please do let me know if you need any additional information. I'm not sure what i've changed or did wrong, but again this was working for a moment, and suddenly it doesn't anymore.

**Comment by ViVRPlus** [comment]
i actually figured out what was wrong, ignore this isue

**Comment by burhanuddinlimdiwala** [comment]
how
