### ISSUE TITLE
webgl requirements to play a video in safari browser

### ISSUE THREAD

**Issue by Ulfiii** [RenderHeads/UnityPlugin-AVProVideo#187]
**Describe the bug**
Hi, which video format works for Safari Browser , we use Safari 13.0.1 on macOS 10.14.6 - WebGL works fine with FireFox on Mac, but Safari only shows me the first frame of the video, which is not played then. I tried videos without audio (as described in previous posts), but no change. Is it possible to play a video in Safari with AvProVideo and WebGL? 
I heard about playing videos in safari requires user initiated playback - what exactly means that ?
Thanks, Ulf
MESHED space Team

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.9 (LTS)
 - AVPro Video version: 1.10.1
 - Operating system version: Windows 10 , Version 1903, Build 18362.356
 - Device model (with Unity Editor): Windows Surface Pro 4
 - macOS (Target System): 10.14.6
 - Safari on macOS: 13.0.1
 - Video specs (resolution, frame-rate, codec, file size): original demo file _AVProVideoSamples/BigBuckBunny_720p30.mp4_

**To Reproduce**
1. Import AVProVideo asset from store into empty project
2. Change to webgl and build scene "04_Demo_uGui"
3. Export build files to webserver - i saved it at https://webdemo.meshed.at/avprovideo
4. Runs in firefox on mac, but do not run in safari browser (no video start)

**Comment by MorrisRH** [comment]
Any mp4 with h264 or HEVC encoded video and AAC encoded audio should work just fine.

Unfortunately Apple have made it so that media playback in safari requires user interaction in order to begin. We haven't yet found a way to achieve this with Unity WebGL. The work around is to set “Allow All Auto-Play” in the “Websites” “Auto-Play” page of the preferences as shown below.

![Screenshot 2019-10-03 at 12 30 19](https://user-images.githubusercontent.com/46530460/66123762-af687300-e5da-11e9-9a34-99d704ee11c7.png)

There is currently an issue where the video playback appears stalled until you tab-away and back again. We're hoping to have a fix for this available soon.
