### ISSUE TITLE
Can't activate more Mediaplayers after about 15

### ISSUE THREAD

**Issue by rcwongtk** [RenderHeads/UnityPlugin-AVProVideo#1889]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
I am working on an AR application that overlays videos on images. Each image has it's own mediaplayer, and it works perfectly until about the 17th image. After that, new mediaplayers simply won't start.

Only one mediaplayer is active at a time, so anytime an image is activated the other mediaplayers are deactivated. I am assuming this means that somehow the mediaplayers are still storing some sort of memory that is accumulating over time. 

Any thoughts on how to resolve this?

**Your Setup (please complete the following information):**
 - Unity version: Unity: v2022.1.20f1 WindowsEditor
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): v2.7.3 (plugin v2.7.0f1-core)
 - Operating system version: 
     - OS: Laptop - Windows 11  (10.0.22631) 64bit - English
    - CPU: 12th Gen Intel(R) Core(TM) i9-12900H - 20 threads - 32468KB
    - GPU: NVIDIA GeForce RTX 3080 Ti Laptop GPU - NVIDIA - Direct3D 11.0 [level 11.1] - 16189KB - 16384
 - Device model: Android - Samsung Galaxy S21
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Create 20 Mediaplayers with different videos and associated meshes
2. Turn one on, play the video, turn it off
3. After about 15-18 the next Mediaplayers will not start up.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
Each media player instance will require hardware resources which are limited and will eventually run out which is why you're seeing things stop working. The decoder resources and texture memory required will be based on the resolution and frame rate of the video being decoded so you could look to use smaller videos to try and increase the number of active media players you can use.

If the videos are short (10s or less) then you could look to using the HAP codec (windows only) which doesn't require GPU decoding resources.

**Comment by MorrisRH** [comment]
You can all `mediaPlayer.OpenMedia()` with a new URL, all the existing player set-up will remain in place. Calling `mediaPlayer.Close()` will release resources currently allocated to a player.
