### ISSUE TITLE
Buffering events not called on Android

### ISSUE THREAD

**Issue by RemyRM** [RenderHeads/UnityPlugin-AVProVideo#19]
The events
 - MediaPlayerEvent.EventType.StartedBuffering
 - MediaPlayerEvent.EventType.FinishedBuffering

Seem to not be called on Android devices when using either MediaPlayer or ExoPlayer. No error or warning is displayed either.

<strike>If this isn't implemented yet it would be nice to see it in AVPro video 2.0.</strike>

Playing videos using HLS streams.

edit:
It appears that the buffering events on Android are not called when a playback first starts. When playback stops (e.g when `MediaPlayerEvent.EventType.Stalled` event was raised) it *will* trigger the `MediaPlayerEvent.EventType.StartedBuffering` event.

This behaviour seems to differ from the editor where `MediaPlayerEvent.EventType.StartedBuffering` is raised when playback starts for the first time, and `MediaPlayerEvent.EventType.FinishedBuffering` is raised when all fragments have been downloaded. And the same events being raised after a video has stalled.

Using AVPro 1.9.12

**Comment by RenderHeadsSte** [comment]
Hi. Thanks for reporting this issue. Apologies that it has taken a while to look into the problem.

I have been able to reproduce the issue in both MediPlayer and ExoPlayer API paths.

There will be a fix in for the problem in version >= 1.9.18 for the ExoPlayer API path.

Unfortunately, due to limitations in the Android API, a fix for the MediaPlayer API path is not entirely possible.  There is a callback that reports whether buffering is started/stopped, but this appears to be entirely device dependant.  Some devices report buffering starts/stops nano seconds apart, whilst some devices do not report back that is starts/stops at all.  Our current thinking is to flag that buffering is happening when 'Open a Video' is started, and when the video reports back that it is prepared, we clear the buffering flag.  I will update on this when we have done some more investigation and come to a decision on what, if anything, we decide to implement.

**Comment by elhongo** [comment]
Hey. Having this same issue. Any ETA on the release of 1.9.18?

Thanks.

**Comment by AndrewRH** [comment]
Looking into this at the moment..

**Comment by RenderHeadsSte** [comment]
@elhongo 1.9.18 is currently undergoing testing. Our aim is to release this coming Friday (5th July).
