### ISSUE TITLE
Audio Capture Buffer always flushing

### ISSUE THREAD

**Issue by Days99** [RenderHeads/UnityPlugin-AVProVideo#1931]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Problems playing a video recorded in AV pro capture, with microphone audio

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.32f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.0 ultra
 - Operating system version: IOS
 - Device model: iPhone 11 Pro 
 - Video specs (resolution, frame-rate, codec, file size): 1920x1080, 60, H264

**To Reproduce**
1. Record a realtime webcam texture capture with microphone audio using Av pro Capture during runtime
2. Open that video in Av pro video during the same runtime
3. When the application get unfocused and focuses again it fixes this issue

**Logs**
[AudioCapture] failed to reserve 4096 bytes in the audio capture buffer, flushing

**Comment by Days99** [comment]
Forgot to mention that im using the Unity Audio mode

**Comment by MorrisRH** [comment]
What's Unity's sample rate set to?
What is the sample rate of the video you're trying to play?
Can you reproduce this using any video or is it specifically one with captured microphone audio?

**Comment by Days99** [comment]
The Unity Sample rate is 44100
The sample rate of the video is 48000 but for some reason I can't change it in Av pro capture when using the microphone?
For now I can only reproduce using a video captured with microphone audio and specifically loaded after the original video is recorded

**Comment by MorrisRH** [comment]
The only way I could get this to happen is by not having an "Audio Output" component linked to the media player. When the "Audio Output" component hasn't been set there's nothing to drain the audio buffer and feed it through to Unity so we have to keep flushing it in order to be able to write to it.

Documentation for the "Audio Output" component can be found [here](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/component-audio-output.html).
