### ISSUE TITLE
[Android] 4K video is upside down using OES fast path

### ISSUE THREAD

**Issue by rrenderr** [RenderHeads/UnityPlugin-AVProVideo#1935]
Some 4k videos are upside down. I investigated a little bit and found next: _videoTrackInfo.Length = 0 and _state.selectedVideoTrack = -1. In this case GetAffineTransform() returns { 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f }. If I change a resolution to another, everything works well. It reproduces only for Android.
I logged matrices. For 4K resolution:
1.00000	0.00000	0.00000	0.00000
0.00000	1.00000	0.00000	0.00000
0.00000	0.00000	1.00000	0.00000
0.00000	0.00000	0.00000	1.00000

For other:
1.00000	0.00000	0.00000	0.00000
0.00000	-1.00000 0.00000 1.00000
0.00000	0.00000	1.00000	0.00000
0.00000	0.00000	0.00000	1.00000

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.15f1
 - AVPro Video version: 3.0.6 ultra (reproduced for 3.0.3-3.0.5)
 - Operating system version: Android
 - Device model: Meta Quest 3
 - Video specs : 4k

**To Reproduce**
1. Open 4k video - https://deovr.com/ht16vm

**Logs**
[FullLog.log](https://github.com/user-attachments/files/16131056/FullLog.log)

**Videos**
https://deovr.com/ht16vm

**Comment by Chris-RH** [comment]
We don't subscribe to DeoVR, so can't access the files.  Can you provide another video in which this occurs please, either here or to unitysupport@renderheads.com

**Comment by rrenderr** [comment]
@Chris-RH I've sent 2 videos via email. Please check it out.

**Comment by MorrisRH** [comment]
Reproduced only when using OES fast path texture mode.

**Comment by rrenderr** [comment]
Can we wait for a fix and when?

**Comment by MorrisRH** [comment]
Unfortunately the video_bugged_4096p.mp4 video exceeds the reported capabilities of the video codec and as a result the media player is flagging the video track as unsupported. This in turn is resulting in the code paths required for correctly handling the produced textures not being executed.

The maximum supported resolution reported by the codec is 7680x4320@60fps (8K). When the video is re-encoded at this resolution it plays back correctly. I was able to push the resolution of your video to 8000x4000@60fps (due to not needing a 16:9 aspect). You could also consider dropping the frame rate to 30fps if you absolutely want to keep the 8192x4096 resolution.

Because we rely on the underlying codec to accurately provide information about what it is capable of decoding we're unable to support resolutions higher than those reported. We're currently investigating how we can better handle this situation however we're unlikely to be able to support it unless the underlying hardware reports that it is capable.

**Comment by rrenderr** [comment]
Intresting.
But in this case video plays. Also, this video plays well with AVPro version 2.7.x. I didn't observe upside down issue.

**Comment by rrenderr** [comment]
@MorrisRH 
According to the Meta documentation, our devices should support  8192x4096 60 fps.
https://creator.oculus.com/getting-started/media-production-specifications-for-delivery-to-meta-quest-2-headsets/

**Comment by Anton111111** [comment]
About my closed issue. I've copy my comment here. Why my video works in AVPro v2 in all conditions? And why this video works in AVPro v3 if i disable Low Overhead Mode (GLES) ? I see problem with this video only if i use OES shader and enable Low Overhead Mode (GLES).

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.7 has been released.  Please let us know if it has not fixed your issue.

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.7 has been released.  Please let us know if it has not fixed your issue.

**Comment by Anton111111** [comment]
> AVPro Video version 3.0.7 has been released. Please let us know if it has not fixed your issue.

No changes

[odh_logs_2024-07-16 14.54.25.527.txt](https://github.com/user-attachments/files/16251634/odh_logs_2024-07-16.14.54.25.527.txt)

**Comment by rrenderr** [comment]
Hi 
I've deleted the old version and installed a new one from Sctratch, and it seems to work well for me!
