### ISSUE TITLE
AVPro Video v3 has problem(screen kept flickering) on (2017.4.23f1 & 2018.4.31f1)

### ISSUE THREAD

**Issue by hackhuang** [RenderHeads/UnityPlugin-AVProVideo#1936]
Avpro Version:AVPro Video v3 - Ultra Edition v3.0.5 or v3.0.6
Unity Version:2017.4.23f1 & 2018.4.31f1
Platform:Android

**Comment by Chris-RH** [comment]
Hi, please can you fill out a full issue form

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Can you provide a full, unfiltered logcat in txt form please
What device are you testing on?

**Comment by Chris-RH** [comment]
Can you provide a full, unfiltered logcat in txt form please
What device are you testing on?
