### ISSUE TITLE
[Unity/Windows] When reverse play a video, the progress bar is playing, but the display rate drop 0, and the texture is not update in UIs

### ISSUE THREAD

**Issue by yeeneng** [RenderHeads/UnityPlugin-AVProVideo#1948]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.27f1 Personal
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): v1.11.6 (script 1.11.7) 
 - Operating system version: Window 11 Home
 - Device model: Asus
 - Video specs (resolution, frame-rate, codec, file size): 2000x724, 25fps, 435mb(60sec duration)

**To Reproduce**
1. Setup basic media player and a raw image as displayGUI.
2. Play a video normally to any frame, then reverse.
3. The raw image show the normal mode fine and perfect, but when reverse, the raw image texture didnt update/play, stuck at the beginning frame of reverse.

**Logs**
If applicable, add error logs to help explain your problem.
-Didnt popup red errors....

**Screenshots**
![when normal play video](https://github.com/user-attachments/assets/9ce9a44f-2924-470a-9804-b5ff1f9cb5b1)
![when reversing video](https://github.com/user-attachments/assets/8518bb92-b3ac-4958-83d4-b48ec1bc558e)

**Videos**
If applicable, add a copy of your video or the URL
https://drive.google.com/file/d/1JivBCsC9RX8a2X4NsRQ1i5XlZYUOGTw2/view?usp=sharing

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
AVPro Video version 1 has been depreciated and is no longer being supported.
The issue is that when encoding videos, they are designed for forward prediction so are never going to be as good going in reverse.  What you could try is to re-encode your video with something like this:

ffmpeg -i input.mp4 -c:v libx264 -g 12 -bf 2 -c:a copy output.mp4

The -g specifies how often to insert an i-frame, the -bf says how many b-frames to insert between p-frames.  b-frames are important for reverse playback as they work in both directions, p-frames are only forward.
