### ISSUE TITLE
Colour Banding on Vulkan Builds

### ISSUE THREAD

**Issue by edward-jones-wi** [RenderHeads/UnityPlugin-AVProVideo#1956]
Hello, I am seeing colour banding / video compression artefacts on videos when building with AVPro 3 and Vulkan that are not visible on the real video. The issue isn't present on OpenGL builds and is not present in the editor (DX11).

 - Unity version: 2022.3.39f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Video v3 - Core Mobile Edition 3.0.8 
 - Device model: Nokia G42, Pixel 6, S23 Ultra
 - Video specs (resolution, frame-rate, codec, file size): 1920 x 1080, H264 - MPEG-4 AVC (part 10) (avc1), Frame rate: 30

**To Reproduce**
1. Create blank project and import AVPro 3 Mobile 3.0.8 with demo scenes.
2. Ensure graphics API is Vulkan.
3. Add the attached video into the AVPro 3 Demo_Playlist scene.
4. Build and run on android device.

**Screenshots**
Example of banding:
![banding_image](https://github.com/user-attachments/assets/6a5ac526-769a-492d-9937-dc03de96e4a4)

Example of no banding:
![no_banding](https://github.com/user-attachments/assets/d67b870e-7619-447c-99da-d024a367cfc7)

**Videos**
Here is the video being used:
https://github.com/user-attachments/assets/1dd0d65f-f812-407e-ad1a-f382b9b20baa

The banding is not seen in editor or when using OpenGL.

Thank you.

**Comment by MorrisRH** [comment]
There's an issue when converting the video output to linear colour space. This has now been fixed and will make it into the next release.

**Comment by tejasXR** [comment]
Thank you very much for fixing this. My team and I are looking forward to using the new version with this banding problem solved.

**Comment by edward-jones-wi** [comment]
Thank you! I'll look out for the new release.

**Comment by TrippingDan** [comment]
Is it at all possible for us to fix this issue in some way before this release? We are just prepping a major release for next week and it includes the new av pro sdk? Please let us know if any methods exist? We won't be able to wait for this sdk version to release our build so we need some sort of fix in advance.

**Comment by Ste-RH** [comment]
@TrippingDan 

The fix for this issue is at plugin level, so there is no way you can apply it without us compiling up and packaging a new asset release package.

We only have a mechanism for providing interim version packages for Enterprise license holders.  If you are from a company that holds an Enterprise license then simply ask the main point of contact from your company to drop us an email and we will sort out a build containing the fix asap.  If you are not, then I am afraid you will have to wait for the next update - which we have penciled in for the end of this week.

Apologies, but if we provided custom versions for every license holder we would never have time to fix bugs and add features!

**Comment by Ste-RH** [comment]
AVPro Video v3.0.10 has now been released.  Do let us know if this fixes the issue for you.

**Comment by TrippingDan** [comment]
This was fixed thank you!!

**Comment by Ste-RH** [comment]
That for letting us know @TrippingDan .  If you have 5 minutes free, it would really help us out if you could leave an honest review of the asset (and support) on the Unity Asset Store.  Thanks!

**Comment by cauberthonda** [comment]
Just ran into the same banding problem on VisionOS

**Comment by Chris-RH** [comment]
Hi @cauberthonda 
Please can you open a new issue for this.
