### ISSUE TITLE
Related to 1824: iOS xcode build faild ld: Undefined symbols: __swift_FORCE_LOAD_$_swiftXPC - UCB does not yet support xcode 15.3

### ISSUE THREAD

**Issue by genereddick** [RenderHeads/UnityPlugin-AVProVideo#1985]
This is the same issue mentioned here and closed: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1824

We also do not see this issue with Xcode 15.3+. However, we are using Unity Cloud Build which currently only supports up to Xcode 15.2.

Are there any work arounds for this?

**Comment by Chris-RH** [comment]
I'm afraid that there isn't a work around.  Our problem is that the plugin is built with 15.3.  Its unlikely that we can fix it due to backward-compatibility issues with swift libs.  From looking on Unity Discussions, it does appear that UCB are working on 15.3 support.  I'm hoping that it gets sorted quickly on their end.  Xcode 16 is in beta already.

**Comment by genereddick** [comment]
OK, thanks for the update.

**Comment by MorrisRH** [comment]
Version 3.1.0 will have the iOS and tvOS plugins built with Xcode 15.2
