### ISSUE TITLE
Android Crash

### ISSUE THREAD

**Issue by cuinc** [RenderHeads/UnityPlugin-AVProVideo#2011]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Firebase report avpro crash rate 1%

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.40f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.8
 - Operating system version: Android 11
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
None

**Logs**
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.setOnPreparedListener(android.media.MediaPlayer$OnPreparedListener)' on a null object reference
       at com.renderheads.AVPro.Video.Player_MediaPlayer$2.run(:643)
       at java.lang.Thread.run(Thread.java:923)

**Screenshots**
None

**Videos**
None

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
1. Before you do anything else, please can you update to the latest version of AVPro Video (3.0.11) and retest.
2. Is this reproducible in a new project running only the AVPro Video demo scenes?
3. What sort of media are you playing? (local/streaming, codec, resolution, FPS, bitrate etc)
4. What devices are you having issues with and which ones are working as expected?
5. Please can you supply a full logcat in txt format.

If you don't want to put the information here, please send it to unitysupport@renderheads.com with #2011 in the subject line

**Comment by Ste-RH** [comment]
@cuinc We will be closing this issue soon due to a lack of response

**Comment by artoonie** [comment]
Hi, Crashlytics is reporting this as a new bug for me. I have just begun deploying my app with AVProVideo 3.2.2 (upgraded from 2.x), so the issue is new to 3.x. Unfortunately, I don't have reproducible steps yet, all I know is that it occurs when first playing a video.

I have two of these crashes showing up:
- Android 10 and 14
- Tecno Spark 20 Pro+ and Galaxy Note9
- I'm on Unity 6000.1.5f1 and OP is on Unity 2022.x, so it seem independent of Unity version
- On my end, the crash appears at `com.renderheads.AVPro.Video.Player_MediaPlayer$2.run (Unknown Source:833)`

I am upgrading to the latest version (3.2.7) to see if it continues to occur there, but in the meantime, I wanted to re-open as it's currently the top (only) crash on my progressive deployment.

Please let me know if there's any debug information I can print on my next deployment to help get to the bottom of this. It's nondeterministic, I haven't reproduced myself, and haven't significantly changed the way I use the library.
