### ISSUE TITLE
[macOS 15][iOS 18] Issue with playback of HLS

### ISSUE THREAD

**Issue by novavision** [RenderHeads/UnityPlugin-AVProVideo#2034]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Streaming url .m3u8 is not played in Mac Unity Editor and iOS devices despite of we using supported codecs (from AVPro website page). We tried HEVC / H.265 and H.264

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.28 
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Trial 3.0.11
 - Operating system version: MacOS
 - Device model: iPhone 13 Pro Max
 - Video specs (resolution, frame-rate, codec, file size): #EXT-X-STREAM-INF:BANDWIDTH=2921659,AVERAGE-BANDWIDTH=1459235,CODECS="hvc1.1.6.L120.90,mp4a.40.2",RESOLUTION=1920x1080,AUDIO="AUDIO",FRAME-RATE=25.0
video_0.m3u8

**To Reproduce**
1. Can't share the video url because of NDA but the fact is that tried all iOS/Mac supported streaming codec in m3u8 file format and none of them works. I always get the error: Tried on Mac Unity Editor and iOS devices.

**Logs**
```
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
```

**Comment by Chris-RH** [comment]
1. Is it reproducible in a new project, using only the AVPro Video demo scene and running your URL?
2. Does it work with this stream: https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8

**Comment by MorrisRH** [comment]
Without access to the media we're unlikely to be able to help diagnose the issue. Apple does provide tools which are very useful to diagnosing issues with HLS, information about them is available [here](https://developer.apple.com/documentation/http-live-streaming/using-apple-s-http-live-streaming-hls-tools) and you can download them from [here](https://download.developer.apple.com/QuickTime/http_live_streaming_tools/HTTPLiveStreamingTools1.23.14b.dmg).

**Comment by novavision** [comment]
> 1. Is it reproducible in a new project, using only the AVPro Video demo scene and running your URL?
> 2. Does it work with this stream: https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8

Tried in Demo_MediaPlayer scene using my url and your provided url - same result. 
<img width="719" alt="img" src="https://github.com/user-attachments/assets/8df54986-3757-482e-a395-d5ace73c18e3">
I will send you the link by email, but if even your url doesn't works, seems the problem is somewhere else. I am on Macbook Pro M3 btw

**Comment by wcampospro** [comment]
Hello,

I'm havingt exactly the same issue. This is extremely important for us since we use this with customers in Launch events (only happen once)
It does not work on iOS devices or even testing on WebGL when setting up an iOS simulated device:

This is the URL: (but many other urls, that are also coming from vimeo do not work)
https://player.vimeo.com/external/1018383319.m3u8?s=41897b6cb6e4bec712d78b1dd0555bbecf9e90ad

Details:

- Unity Version: 2022.3.41f1
- AVPro Video: version 1.11.4 (Released 2020-07-29) <has been working flawlessly until recently>
- I also tried with an old build that used to work flawlessly with the same video stream url, and now it simply doesn't work.

Errors:
```
Error: video not supported (errorcode=4) color:red; MediaError {code: 4, message: 'DEMUXER_ERROR_COULD_NOT_OPEN: FFmpegDemuxer: open context failed'}code: 4message: "DEMUXER_ERROR_COULD_NOT_OPEN: FFmpegDemuxer: open context failed"[[Prototype]]: MediaErrorMEDIA_ERR_ABORTED: 1MEDIA_ERR_DECODE: 3MEDIA_ERR_NETWORK: 2MEDIA_ERR_SRC_NOT_SUPPORTED: 4code: (...)message: (...)constructor: ƒ MediaError()Symbol(Symbol.toStringTag): "MediaError"get code: ƒ code()get message: ƒ message()[[Prototype]]: Object

[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources. 
```

Please help with this ASAP, this is directly affecting our business with customers.

**Comment by Chris-RH** [comment]
Hi @wcampospro,

We've been working with the OP via email and have worked out that newer versions of macOS (15+) and iOS were not accepting a small discrepancy in the audio format of the HLS (most likely caused by the process used to create the HLS), which older versions of the OS seemed to play fine. 

This may or may not be the case with yours, but it would probably be better if you opened a new issue for yourself and included as much information in it as you can.

**Comment by novavision** [comment]
I may confirm that audio playlist issue fix solved the problem and I could play HLS streamed videos on iOS device and Unity MacOS editor

**Comment by Chris-RH** [comment]
Thanks @novavision, I'm glad its sorted now :)

**Comment by MorrisRH** [comment]
Unfortunately the issue is caused by a change in Apple's CoreMedia framework related to how URIs in manifest files are handled. It would appear that certain characters that are not URL safe can no longer be used and require replacing with their percent encoded equivalents. In the OP's case one of their manifest files had paths containing '{' and '}' which required converting to %7b and %7d respectively.

As this is happening at OS level there is nothing we can do about this. Hopefully Apple will resolve this issue in a future OS update.
