### ISSUE TITLE
Can an MP4 have more than one video tracks? 

### ISSUE THREAD

**Issue by noman5412** [RenderHeads/UnityPlugin-AVProVideo#2055]
How to add multiple video tracks in one MP4 container. Do we need to have any tool like premier pro etc. for this or it can only be done by some sort of programming?

**Comment by Chris-RH** [comment]
Hi.  An mp4 can have multiple video tracks.  I can't recommend software in particular, but I'm sure that video editing software would have that option.  You'd have to investigate individual software yourself.  
Otherwise you could use a commandline tool such as ffmpeg, but some users find that more complicated.
