### ISSUE TITLE
[WebGL] HLS streaming no longer works on meta quest 2 browser

### ISSUE THREAD

**Issue by joecat88** [RenderHeads/UnityPlugin-AVProVideo#2059]
### Unity version

2021.3.45

### Unity editor platform

Windows

### AVPro Video edition

Trial

### AVPro Video version

3.0.10

### Device hardware

Meta Quest 2

### Which browser are you using?

Chromium (Quest 2)

### Which version of the browser are you using?

128.0.6613.186

### Graphics API

WebGL 1

### Which output component(s) are you using?

Apply to Mesh

### The issue

Hello, I'm a software developer at a software company. Last month, I tested the free trial version of AVPro Core Edition in a Unity WebGL build to verify the functionality of the HLS streaming protocol, following the guidelines outlined on this page (https://www.renderheads.com/content/docs/AVProVideo-v3/articles/supportedmedia.html).

I tested it in both Chrome and the Meta Quest 2's Chromium-based browser, and it worked in both cases. Based on this positive outcome, my company agreed with a client to add this feature to our Unity WebGL application. As a result, we planned to purchase the full paid version.

However, the Meta Quest 2 received a system and browser update, and AVPro no longer plays HLS streams, displaying a black screen instead. Do you have any possible solutions for this issue? Thank you.

**Comment by Chris-RH** [comment]
Hi, 

We don't actually [support WebGL](https://renderheads.com/content/docs/AVProVideo-v3/articles/platform-webgl.html).  Its most likely to be a CORS issue.  Have you tried posting on the Meta forum?

**Comment by MorrisRH** [comment]
Unable to reproduce this issue here. Testing using the following:
- Chromium Browser (128.0.06613.186) on Quest 3
- Unity 2021.3.45f1
- AVPro Video v3.1.2
- HLS.js v1.5.17
- Demo_MediaPlayer scene

Both WebGL 1 and WebGL 2 graphics APIs worked.

If you could grab log output from the browser then we might be able to help further.

**Comment by joecat88** [comment]
Hi, thanks for support; i tried 4 more times and 2 times it worked. The build and the streaming video are always the same, so I cannot understand where is the problem. Checking the browser console, the error is 

"[AVProVideo] Error: Decode failed.  Possible codec not supported, video resolution/bit-depth too high, or insufficient system resources"

Il'll try to change some video parameters, but like i said, two times worked with the same context and environment. On Quest 2, only browser was opened, and only the webgl tab, so probably it's not related to "insufficient system resources".

**Comment by joecat88** [comment]
About log, i'll do some changes/filer because in test environment there're some private information.
The streaming source i'm currenlty using is this free demo: https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8

**Comment by MorrisRH** [comment]
I've reproduced this on a Quest 2 (browser version as above).

The problem is with the lowest bitrate variant of the HLS (the other variants playback fine). I've no idea why as it works fine with the Quest 3 and on other platforms but on the Quest 2 it throws a decoding failed error.

This does fit with what you're seeing as when it successfully plays for you it's been able to skip to a higher bitrate variant before starting to decode video frames.

Because this is happening at the browser/system level there is nothing we can do about it. If it worked previously then it might be worth opening an issue with meta about it.

**Comment by joecat88** [comment]
Ok, thanks anyway for the help, really appreciated
