### ISSUE TITLE
[iOS] Audio Media Pauses on app Pause

### ISSUE THREAD

**Issue by memidgety** [RenderHeads/UnityPlugin-AVProVideo#2067]
### Unity version

Unity  6.0.14f1

### Unity editor platform

Windows

### AVPro Video edition

Core

### AVPro Video version

3.0.11

### Device hardware

iPhone 12

### Which iOS version are you using?

17.6

### Texture format

BGRA

### Audio output

System Direct

### Any other Media Player component configuration required to reproduce the issue.

Make sure Pause Media on App Pause is unchecked. We are also streaming an mp3.

### The issue

Issue: iOS does not play audio when phone is put to sleep via button or screen timeout.
Expected Outcome: Audio to continue when phone goes to sleep via timeout or button press.

### Media information

Streaming asset sent via email.

**Comment by memidgety** [comment]
We have tried implementing solutions from [1243](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1243) and [1449](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1449) with no success.

**Comment by MorrisRH** [comment]
You need to make sure the audio session category is set to playback. One way of achieving this is to edit `UnityAppController.mm` in the build Xcode project and insert the following around line 135:
```objc
	// [AVProVideo] Set the audio session category to playback to allow for background audio
	NSError *error = nil;
	BOOL success = [audioSession setCategory:AVAudioSessionCategoryPlayback error:&error];
	if (success == NO)
	{
		NSLog(@"Failed to set audio session category, error: %@", error.localizedDescription);
	}
```
If the line numbering changes in the future then the code above should immediately follow after this line:
```objc
    AVAudioSession* audioSession = [AVAudioSession sharedInstance];
```

**Comment by daveb-tactic** [comment]
This fix worked for me when I tried it.
I think the issue was, in the previous solution it was recommended to change a specific line of code "AVAudioSessionCategoryAmbient" to "AVAudioSessionCategoryPlayback". However, in Unity 6, that line of code is bracketed by an if statement that seems to fail (at least on some projects) so it never gets called.
Adding the line outside the if statement around line 135 (as recommended) fixed the issue. I ended up adding a custom AppController and overrided the startUnity call in which I first call the base class [super] startUnity, then the block with the "AVAudioSessionCategoryPlayback" change. That works just as well, and has the benefit that UnityAppController.mm doesn't need to be modified by a post-build process.
