### ISSUE TITLE
Video Tearing when is played in AVPro

### ISSUE THREAD

**Issue by feiou** [RenderHeads/UnityPlugin-AVProVideo#207]
We are using the component on UI to play from the video player in unity and using a camera to look at it to play 4K video. All 4k videos are tearing. We tried to turn on Vsync and played with Vsync settings but it did not fix it. All video are in 23.99 fps and we've played with multiple game framerate and display framerate like set them all to 30 fps but it didn't now solve it.

I am desperate now, please let me know. Thanks you so much!!

**Comment by RenderHeadsSte** [comment]
What platform/OS are your targeting?

**Comment by feiou** [comment]
Hi, thanks for the reply, we are targeting PC (win 10).

Ste Butcher <notifications@github.com> 于 2019年11月8日周五 上午5:12写道：

**Comment by AndrewRH** [comment]
This sounds very strange...we have never seen tearing....
Is it only tearing in the video playback area, or the whole app?  Or could be a driver level (eg Nvidia Control Panel) override for vsync setting which would override Unity's settings.

Since this thread is old now, we will close it if there is no more activity as we haven't been able to replicate this issue.

Thanks,

**Comment by FlyingFlambe** [comment]
Hi @AndrewRH , I'm having a similar issue with 4k video tearing in AVPro. There was no tearing until I set render quality to Beautiful in Unity 2019 LTS (not using URP, HDRP, or LWRP). Built to Windows UWP appxbundle.

**Comment by FlyingFlambe** [comment]
Nvm fixed it by changing the settings in Quality > Other to use the same settings as Fastest. Not sure why but that seemed to do it (don't need to use bones/skinning for current project so its not a big issue for this particular case).

![image](https://user-images.githubusercontent.com/22328598/128561946-734da488-f7e1-4719-a235-9ebaf9ac2a59.png)
