### ISSUE TITLE
[Android] When using Android OES textures an incorrect texture is obtained and swapped at the output

### ISSUE THREAD

**Issue by SlavomirDev** [RenderHeads/UnityPlugin-AVProVideo#2105]
### Unity version

2022.3.54f1

### Unity editor platform

Windows

### AVPro Video edition

Ultra

### AVPro Video version

3.1.3

### Device hardware

Samsung Galaxy S21 FE, Meta Quest 3

### Which Android OS version are you using?

14

### Unity Graphics API

OpenGLES 3

### Video API

media3/ExoPlayer

### Texture format

Y Cb Cr 420_OES

### Audio output

Unity

### Which output component(s) are you using?

Resolve to RenderTexture

### The issue

When using Android OES textures (textureFormat = YCbCr420_OES), an incorrect texture is obtained at the output. It seems as if the texture is rotated 90 degrees or the X and Y axes are swapped up. It should also be noted that the texture size itself remains the same and retains its proportions

There is also a suspicion that the player gives the usual BGRA texture instead of OES, since we were able to render it with a regular shader

### Media information

Any video

**Comment by Chris-RH** [comment]
We've not been able to reproduce that here.  Are you able to send us a copy of the video you are using please?  unitysupport@renderheads.com

**Comment by Ste-RH** [comment]
We have tried to reproduce this here using the 'RenderHeads-1080p30-H264.mp4' video supplied with the asset, but we get an output exactly as we would expect.

Our hunch is there is something different in the video(s) you are testing with?  Maybe they have a rotation?  Could you supply a video please so we might try to reproduce the issue.  You can send it to unitysupport@renderheads.com if you wish to keep it private.

RE: "There is also a suspicion that the player gives the usual BGRA texture instead of OES".  When you say 'player' you mean when obtaining it in script from the MediPlayer class?  That should be returning a handle to the OES texture directly.  If you mean from the 'Resolve To RenderTexture', then that will be resolving down to a regular BGRA texture as that is essentially it's job.

**Comment by SlavomirDev** [comment]
We found this problem. We had a conflict with a third-party library that was in a different SDK.
I will close this issue, as I no longer need help. Thank you for your cooperation

**Comment by Chris-RH** [comment]
Ah, brilliant, thanks for letting us know :)
