### ISSUE TITLE
Why is the log always out

### ISSUE THREAD

**Issue by sam8890** [RenderHeads/UnityPlugin-AVProVideo#224]
**Describe the bug**
scenes in build : [03_Demo_VideoControls]
building a project using IL2CPP
why is the log always out 
Log message :[ using playback path : unkown(0x0@0.00) ]

**Your Setup (please complete the following information):**
 - Unity version: Unity 2018.4.0f1 (64-bit)
 - AVPro Video version:  (script v1.10.0 plugin v1.9.17) 
 - Operating system version: on NVIDIA GeForce GTX 1060 3GB/Direct3D 11.0 [level 11.1]  Windows 10  (10.0.0) 64bit

![error](https://user-images.githubusercontent.com/37574821/69707313-7826c600-1134-11ea-8d24-56952e0c5415.png)

**Comment by sam8890** [comment]
I observed that if the player is stopped, the log will always be output

**Comment by RenderHeadsSte** [comment]
Is this with an unaltered demo scene/video?

Is the target platform Windows?

**Comment by RenderHeadsSte** [comment]
Oki, I have gotten to the bottom of why this happens.  It is basically because of this Unity issue:

https://issuetracker.unity3d.com/issues/il2cpp-plugin-function-returning-incorrect-unhdefined-bool

There is a define that gets around this when building IL2CPP at the top of WindowsMediaPlayer.cs ...

#define AVPROVIDEO_MARSHAL_RETURN_BOOL

If you ensure this is defined in when doing IL2CPP builds, then that problem, and possible others(!) will vanish.  We will look into a fix for the next release.

Thanks for reporting this one!
