### ISSUE TITLE
Info.GetVideoFrameRate() and GetTextureTimeStamp() not working on Android

### ISSUE THREAD

**Issue by pdemello13** [RenderHeads/UnityPlugin-AVProVideo#245]
**Describe the bug**
Basically I'm just playing a video in a media player and trying to return the frame rate / current time using Info.GetVideoFrameRate() and GetTextureTimeStamp().

Video play back works fine, but when I print the video frame rate it returns -1,
also the current time seems to increase over time but starts at around 30,000.
I've tried a few videos and it's always the same.

Both of these methods work as they should on my Windows build, it's just on my build to the Quest where they don't work.

**Your Setup (please complete the following information):**
 - Unity version: 2019.1.8f1
 - AVPro Video version: 1.10.1
 - Operating system version: user-434260.5710.0 (latest update as of 09/01/2020)
 - Device model: Oculus Quest
 - Video specs (resolution, frame-rate, codec, file size): specs for one video I tried:
4096x2048, 29.97 fps, h264(high), yuv420p, 717mb

**To Reproduce**
1. Play a video on a MediaPlayer
2. use MediaPlayer.Info.GetVideoFrameRate() and MediaPlayer.TextureProducer.GetTextureTimeStamp() to get the frame rate and current time stamp.
3. Build and Run on Oculus Quest / print frame rate and time stamp every frame.

If you need any further information let me know :)

Thanks,
Paulo

**Comment by RenderHeadsSte** [comment]
What video API are you using?

I am afraid the video frame rate metadata is not always available.  I have seen vary according to Android implementation and file format.

**Comment by pdemello13** [comment]
Hey,
I was using Exo player, but now I've switched over to Media Player and the GetVideoFrameRate() works! 
Thanks :)
But the Texture Time Stamp is definitely off still?

**Comment by RenderHeadsSte** [comment]
We return back this value:

https://developer.android.com/reference/android/graphics/SurfaceTexture.html#getTimestamp()

...but we convert to hector nanoseconds.  So that is the number you are getting back  (getTimestamp() / 100)

**Comment by pdemello13** [comment]
Sorry I made a mistake in my previous comment,
I calculate the current video time by dividing the texture time stamp by 1e7.

So:
`float currentTime = videoPlayer.TextureProducer.GetTextureTimeStamp() / 1e7f;`

The currentTime returned starts of at 30k on Android, but is correct on Windows builds.

**Comment by RenderHeadsSte** [comment]
'Current video time' ?  You mean 'how far into the video is playback' ?  If so, you are using the wrong function  :)

**Comment by pdemello13** [comment]
Ah thank you so much!
It worked fine on Windows but I guess that's just a coincidence.

I'm using `GetCurrentTimeMs()` now :)

**Comment by HaimBendanan** [comment]
I have the same issue - `videoPlayer.TextureProducer.GetTextureTimeStamp()` returns wrong values on Android.
I do need this over `GetCurrentTimeMs()`, because it seems that `GetCurrentTimeMs()` is not accurate enough.
I am doing frame by frame tracking and overlay effects on top of the video, so they need to be in perfect sync with the current time of the video.
The syncing on windows works perfectly on windows when using `GetTextureTimeStamp()`, and I would like to use it on Android too - but as @pdemello13 stated, it is off by a random value which constantly change.

Here is an example of the difference between the two while playing the videoon Windows, note that it is not a constant difference:
_mediaPlayer.Control.GetCurrentTimeMs():**2445**, (_mediaPlayer.TextureProducer.GetTextureTimeStamp() / 10000): **2444**
 _mediaPlayer.Control.GetCurrentTimeMs():**2547**, (_mediaPlayer.TextureProducer.GetTextureTimeStamp() / 10000): **2546**
 _mediaPlayer.Control.GetCurrentTimeMs():**615.2079**, (_mediaPlayer.TextureProducer.GetTextureTimeStamp() / 10000): **599**
 _mediaPlayer.Control.GetCurrentTimeMs():**640.8537**, (_mediaPlayer.TextureProducer.GetTextureTimeStamp() / 10000): **633**
 _mediaPlayer.Control.GetCurrentTimeMs():**641.9162**, (_mediaPlayer.TextureProducer.GetTextureTimeStamp() / 10000): **633**

Do you have a suggestion on how to overcome this? Really stuck here :(
