### ISSUE TITLE
GetVideoFrameRate() always -1

### ISSUE THREAD

**Issue by nsmith1024** [RenderHeads/UnityPlugin-AVProVideo#247]
**Describe the bug**
 if (_mediaPlayer.Info.GetVideoFrameRate() > 0) {

}
else {
}
frame rate always -1

**Your Setup (please complete the following information):**
 - Unity version: 2018.3
 - AVPro Video version: unknown (latest)
 - Operating system version: Running on Android
 - Device model:  Android 7
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Play a video then try to get the frame rate

**Comment by nsmith1024** [comment]
Oh maybe it should be MediaPlayer.Control.GetPlaybackRate()? 

im calling the wrong function maybe

**Comment by nsmith1024** [comment]
MediaPlayer.Control.GetPlaybackRate() is the correct one, the other one always returns -1

**Comment by Adrian-Cook** [comment]
Same issue for me. My video is paused and I am trying to step through it frame by frame. I believe that MediaPlayer.Control.GetPlaybackRate() returns the frames per second being displayed, so is dependent on playback speed of device whereas the GetVideoFrameRate should return the metadata info on the video file.

**Comment by blevok** [comment]
GetPlaybackRate is not related to frame rate, it's the like the speed multiplier. It returns 1 because that's normal speed, aka 100%, where 1 minute of video takes 1 minute to play.
I just went crazy with this the other day, experimenting all day and searching for answers, because i'm also having the -1 issue on GetVideoFrameRate.
But unfortunately it seems it's not going to work currently. Somewhere buried deep in the thread on the unity forum, @AndrewRH stated that GetVideoFrameRate is available everywhere except android. I assume that means it's a platform limitation or not yet implemented in the plugin.

**Comment by Adrian-Cook** [comment]
Thanks Blevok, that is really handy info. Much appreciated.
Without knowing the framerate I don't see how I can seek to a frame accurate position, are there routes to do this I don't know about?

**Comment by blevok** [comment]
Well i do have an idea, but i suspect you're not gonna like it...

Lets say you have a video that's 30 frames per second. That means that 1 frame stays on screen for about 33.333ms. You probably see where i'm going with this now.

If you want to advance by 17 frames, you could do something like this:
`int framesToAdvance = 17; // or user inputted value?`
`int msToAdvance = (framesToAdvance * (1000 / 30));`
`mediaplayer.Control.Seek((mediaplayer.Control.GetCurrentTimeMs() + msToAdvance));`

Of course this would only work with videos that you include with the app, because you know the frame rate. If the user is providing the video, then there's no way that i can think of right now to figure out how long each frame stays on screen, unless you ask them to input the frame rate first.

Also, depending on where exactly you are in a frame, you might end up being off by one frame due to rounding.

**Comment by Adrian-Cook** [comment]
Thanks Blevok,
The videos are being loaded from the devices camera gallery so I will not be able to know the frames per second. But I had implemented exactly what you have said to at least allow some semblance of use in the shorter term.
My next approach will be to look at the native gallery code that may allow me access to the video metadata when the user selects the video. The Gallery plugin comes with full source so there may be a way I can amend that. Thank so much for your posts.

**Comment by Adrian-Cook** [comment]
For what it is worth I have written an Android native plugin to return the Frames Per Second from the Video URL or file. It seems to be working correctly. If there is any interest I can post it.

**Comment by RenderHeadsSte** [comment]
As information...

GetVideoFrameRate() on Android works when using the MediPlayer API path.  ExoPlayer gives very mixed results, unfortunately usually returning back 'no result' in the metadata.

I believe FrameExtract.cs shows how to frame accurately seek.  To increase speed, keyframing your video every frame might help, thought this will naturally increase your video size.

**Comment by RenderHeadsSte** [comment]
A bit of additional information.  It appears ExoPlayer offer some limited support for this in a newer version that we are using in AVPro Video.  Our path to updating to a newer version of ExoPlayer is currently blocked.  This is something we are investigating a solution for.

**Comment by AndrewRH** [comment]
I believe this will be working much better in AVPro Video 2.0 on Android - perhaps  @RenderHeadsSte could check this

**Comment by RenderHeadsSte** [comment]
I can confirm that this works a lot more reliably in version 2.0 when using the ExoPlayer API path.  The MediPlayer API path remains unchanged and will likely never be reliable unless there is an update within the Android API.
