### ISSUE TITLE
Loading Video using Absolute Path on Oculus Go

### ISSUE THREAD

**Issue by Mic542** [RenderHeads/UnityPlugin-AVProVideo#252]
ExtractFrame on Oculus Go using Absolute Path is not working. I tried to make a thumbnail for video gallery apps using the ExtractFrame function. I created Movies folder on the same location as Android folder on Oculus Go and already tried using "/mnt/sdcard/Movies/" or "/storage/emulated/0/Movies/" path but nothing works. 
I am sure the code is working as I tried in Editor on iMac and the thumbnail appear without any problem. Do anyone have any idea how to correctly load video from anywhere in Oculus Go using absolute path?

Thanks.

**Setup:**
 - Unity version: 2019.2.11f1
 - AVPro Video version: 1.10
 - Operating system version: Android
 - Device model: Oculus Go
 - Video specs (resolution, frame-rate, codec, file size): 360 video, 4k, mp4, >300 mb

**Comment by Mic542** [comment]
Anyone can help? I am stuck here for days..

**Comment by RenderHeadsSte** [comment]
I can almost guarantee you this will be because your path is not correct.  Also ensure you have the correct write permissions enabled in your 'Player Settings.->Other Settings'.

There are unity functions to discover the correctly mounted paths for storage, although I have seen theses produce hit and miss results depending on OS implementations.  In the past, for a fail safe result, I have used a filemanage applications to get correct paths.  Something like 'ES File Explorer'.
