### ISSUE TITLE
Build failed for iOS project exported from Unity

### ISSUE THREAD

**Issue by kennethc-olivex** [RenderHeads/UnityPlugin-AVProVideo#259]
We purchased the unity plugin and exported a Unity Project to an iOS project and tried to build it, but encountered the following error. Is it related to the podfile or some linker settings?

`duplicate symbol '_IUnityGraphicsMetal_GUID' in:

    /Users/kennethc/Projects/olivexmirrorcli/OliveXMirror/iOS/Libraries/Plugins/iOS/libAVProVideoiOS.a(AVPPlayerMetalWatermarkedTextureDelegate.o)

    /Users/kennethc/Projects/olivexmirrorcli/OliveXMirror/iOS/Libraries/Plugins/iOS/libAVProVideoiOS.a(AVPPlayerMetalTextureDelegate.o)

duplicate symbol '_IUnityGraphicsMetalV1_GUID' in:

    /Users/kennethc/Projects/olivexmirrorcli/OliveXMirror/iOS/Libraries/Plugins/iOS/libAVProVideoiOS.a(AVPPlayerMetalWatermarkedTextureDelegate.o)

    /Users/kennethc/Projects/olivexmirrorcli/OliveXMirror/iOS/Libraries/Plugins/iOS/libAVProVideoiOS.a(AVPPlayerMetalTextureDelegate.o)

ld: 2 duplicate symbols for architecture arm64

clang: error: linker command failed with exit code 1 (use -v to see invocation)`

 - Unity version: 2019_3.0a8
 - AVPro Video version: (script v1.10.0 plugin v1.9.18t)
 - Operating system version: building it at macOS 10.14.6 (18G103)

**Comment by MorrisRH** [comment]
The duplicate symbol issue should only be a warning and is only present in the trial version of the plugin. The full version does not have this issue. I suggest tweaking your setup so that duplicate symbols are permitted whilst linking.
You say you purchased the plugin so it looks like the full version failed to install correctly. It is also not the latest which at version 1.10.1 (both script and plugin) for iOS.

**Comment by kennethc-olivex** [comment]
thanks, seems it is the installation problem.
