### ISSUE TITLE
Windows watermark does not get removed

### ISSUE THREAD

**Issue by JackM36** [RenderHeads/UnityPlugin-AVProVideo#277]
I purchased the Windows version of AVPro (I had the Android one for quite some time if that makes a difference). However, the watermark is still not removed when I build for Windows.

I already tried deleting the dlls from the plugin folder, restarting Unity and then reimporting them. Any ideas what should I do?

 - Unity version: 2018.3.5f1
 - AVPro Video version: 1.10.1

**Comment by AndrewRH** [comment]
Hi,

That sounds strange...  
If you have the package "AVPro Video (Android)" then you will not have the watermark on Android, but you would still see it in the editor because it's running on the Windows platform.

If you have the package "AVPro Video (Windows)" then you should not have the watermark in Windows, but you may see it on Android (unless you followed the instructions in the PDF documentation that explains how to install 2 packages over each other to get multi platform support)...

But it sounds strange that you're seeing a watermark after installing the Windows package....

The things you have tried are the usual things I would suggest...  Unity does lock the DLL files, so make sure to close Unity completely, then open it and immediately install the package without touching anything / playing the scene etc...

I hope it works...It should :)

Let me know how it goes.

**Comment by JackM36** [comment]
> If you have the package "AVPro Video (Android)" then you will not have the watermark on Android, but you would still see it in the editor because it's running on the Windows platform.

That was the case until a few days ago. Then I purchased the Windows one too and imported, but the watermark is still there.

I tried it again, following exactly what is written in the PDF (starting Unity, deleting previous Android and Windows plugins, closing Unity, opening Unity, importing plugins) but it still does not work.

What else can I do?

**Comment by RenderHeadsSte** [comment]
What order are you importing the plugins in?

**Comment by AndrewRH** [comment]
@JackM36 this is strange...nobody else has reported this issue and that version has been live for several months now.  Perhaps you could try on a different machine or something else?

**Comment by RenderHeadsSte** [comment]
We shall be closing this bug shortly due to lack of response.
