### ISSUE TITLE
360 Video is playing with vertical split, but need to force horizontal

### ISSUE THREAD

**Issue by brightleydeveloped** [RenderHeads/UnityPlugin-AVProVideo#305]
Problem description:

While trying to play a 4000x4000 mp4 (h.264, 30fps), the player is splitting the view with
a vertical split.  Is there a way to force the horizontal split?

Device (which devices are you having the issue with - model, OS version number):

Oculus Quest, Oculus Rift

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

System Information:

AVPro Video: plugin v1.10.1 scripts v1.10.1
Target Platform: Standalone
Unity: v2018.4.8f1 WindowsEditor
OS: Desktop - GS75 Stealth 8SF (Micro-Star International Co., Ltd.) - Windows 10  (10.0.0) 64bit - English
CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 12 threads - 16225KB
GPU: NVIDIA GeForce RTX 2070 with Max-Q Design - NVIDIA - Direct3D 11.0 [level 11.1] - 8031KB - 16384

**Comment by AndrewRH** [comment]
Hi,
I'm not sure I understand what the issue is.   Is the video stereo?  Is it packed top-bottom or left-right?  If it is stereo did you set the stereo packing mode?

Do you know whether the video contains stereo metadata?   If so - you need to remove this metadata.  AVPro Video doesn't support playback of stereo videos that contain metadata on Windows (other platforms are supported fine). 

Thanks,

**Comment by AndrewRH** [comment]
Hi,

@brightleydeveloped did my suggestion help, or do you have any more information to provide?  

Thanks,

**Comment by brightleydeveloped** [comment]
@AndrewRH Sorry, just saw your response.  The video is stereo.  The video is packed top-bottom.  I didn't know about the stereo metadata - I've tried a number of different conversion settings in Adobe Premiere, and was able to get it to work today by simply removing the "Video is VR" checkbox when exporting.  It seems like you're correct about removing the metadata helping, if the checkbox adds the metadata.
