### ISSUE TITLE
Need to click a panel and open a video from my local file with avpro media player but its not working.

### ISSUE THREAD

**Issue by ManiInvr** [RenderHeads/UnityPlugin-AVProVideo#311]
I have a query ,since i have created a folder in my local path with different format mkv and mp4..videos and want to play one by one automatically without giving myvideo.mp4 or mycideo.mkv.i want to get the videos from the local path automatically and play it and how can i do it?

**Comment by RenderHeadsSte** [comment]
I am not sure your question refers to an AVPro Video feature.

Are you asking how to scan a folder to find what video files are present, in order to play one of them?

If that is the case, this link shows you how to scan files in a folder: [https://answers.unity.com/questions/16433/get-list-of-all-files-in-a-directory.html](url)

**Comment by AndrewRH** [comment]
This is beyond the scope of the plugin and this issue is very old.  Closing.
