### ISSUE TITLE
live m3u8 not streaming on webgl

### ISSUE THREAD

**Issue by serversdz** [RenderHeads/UnityPlugin-AVProVideo#327]
**Describe the bug**
hello
I 've just purchased the asset
when I try to play a live URL on WebGL, it does not work
I get this error
Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources.
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
thanks in advance
**Your Setup (please complete the following information):**
 - Unity version: 2019.3.11f1
 - AVPro Video version: 1.10.3 
 - Operating system version: webgl google chrome
 - Device model: desktop
 - Video specs: m3u8 live stream

**Logs**
Error: video not supported (errorcode=4) color:red;

411bcac5-8f6c-455f-be17-538e9e3c4796:8 [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources. 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

**Comment by AndrewRH** [comment]
Hi,

Please see our PDF documentation (section 4.3.4 for information about streaming using WebGL), here is a snippet:

HLS and MPEG-DASH are not natively supported by all browsers.  We have added hooks to include third-party javascript libraries to handle these formats.  Under the “Platform Specific > WebGL” section you can select “External Library”.  This will force the MediaPlayer to use either hls.js or dash.js.  You can also select “custom” if you wish to add support for your own javascript library.

To add support for hls.js:

- In the MediaPlayer component set Platform Specific > WebGL > External Library to hls.js
- Build for WebGL
- Download the latest hls.js release (we tested with 0.10.1):
- https://github.com/video-dev/hls.js/releases
- Once your build is made, copy “hls.min.js” to the TemplateData folder
- Edit the index.html to add <script src="TemplateData/hls.min.js"></script> before the UnityLoader.js script is loaded.  Ideally you would add this to a new WebGL template so that you don’t have to make these changes for each build.

Thanks,

**Comment by serversdz** [comment]
Thanks a lot 
working like a charm
this asset is amazing
