### ISSUE TITLE
Avpro doesn't play 8k video, so ask

### ISSUE THREAD

**Issue by ToddJo** [RenderHeads/UnityPlugin-AVProVideo#335]
**Describe the bug**

I am using a 1660 ti graphics card and I tried downloading Trial version and playing 5760X2880 .mp4 video.

[AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources.

It does not proceed with the above error

I need a solution.

Thank you

**Your Setup (please complete the following information):**
 - Unity version: 2019.2.12f1
 - AVPro Video version: 1.10.3
 - Operating system version:  Windows10
 - Device model:  Desktop
 - Video specs (resolution, frame-rate, codec, file size):  5760X2880,  29.97frame/second  ,mp4,  332MB

**To Reproduce**
1.  Unity Editor Open 
2.  Demo Scene  "08_Demo_360SphereVideo" Open
3.  path Edit And Play

**Logs**
[AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources.

**Videos**
https://afbasecamp.s3.ap-northeast-2.amazonaws.com/Test/evo2.mp4

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi,

I believe this issue is caused by the video being in the HEVC codec.  Microsoft Windows no longer includes this codec by default, so you have to install it manually.  You can find it here:
https://www.microsoft.com/en-us/p/hevc-video-extensions-from-device-manufacturer/9n4wgh0z6vhq?activetab=pivot:overviewtab

After that it should work.

I notice your video also contains stereo metadata.  On Windows our plugin will only decode a single eye.  To get stereo support you should remove the stereo metadata.  Other platforms don't have this issue.

If you intend to stream your video from a server then you should also encode with the FastStart option for better streaming.

I hope this information helps?

Thanks,

**Comment by ToddJo** [comment]
Thank you!

It is playing normally after installing HEVC code.

However, there is a phenomenon in which playback does not work smoothly and
hangs.

I tried using the FastStart option you mentioned.

However, there is still the same phenomenon.

Is there a solution?

please answer about my question!

Thank you


[image: 124.PNG]

2020년 4월 29일 (수) 오후 7:32, Andrew <notifications@github.com>님이 작성:

**Comment by AndrewRH** [comment]
Hi,

"However, there is a phenomenon in which playback does not work smoothly and
hangs."

Hmm....I'm afraid this doesn't give us much information to go on.   I noticed that your video is authored at 29.97 fps.  Usually it's best to have your video at multiple of the display device frame rate, so 30fps should give you smoother playback.

I'm not sure if the hangs you're having are due to network issues, or just system bottlenecks.  Perhaps you could look at the Performance tab in Task Manager to see how the usage is for the GPU and CPU?

Thanks,
