### ISSUE TITLE
Issue: video player stopped after pause 

### ISSUE THREAD

**Issue by HalynskyiDigicode** [RenderHeads/UnityPlugin-AVProVideo#349]
Problem description:

We start playing video from url. Playing is very well. But if we make pause video we have no possibilty to resume playing (on some devices)
MediaPlayer.Play(), MediaPlayer.Pause(), MediaPlayer.Play()

Here short log:
2020-05-07 16:45:36.313 18740-18788/com.LaMark.DisneyStorytime I/Unity: [AVProVideo] Using playback path: ExoPlayer NonOES (854x480@-1.00)
2020-05-07 16:45:36.323 18740-18788/com.LaMark.DisneyStorytime I/Unity: [AVProVideo] Texture ID: 41
2020-05-07 16:45:36.333 18740-18788/com.LaMark.DisneyStorytime I/Unity: Video frame ready
2020-05-07 16:45:47.764 18740-18788/com.LaMark.DisneyStorytime I/Unity: [MediaPlayer] Stalled with error: None
2020-05-07 16:45:58.418 18740-18788/com.LaMark.DisneyStorytime I/Unity: [AVProVideo] Opening https://stage.cvm-k.com/21.6.B/disneystorytime-pt/video/TS4_PT_Part1_T.mp4 (offset 0) with API ExoPlayer

Device (which devices are you having the issue with - model, OS version number):

OnePlus 6, OnePlus 6T, Samsung Galaxy Note 10 Plus, Samsung Galaxy S9

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):
https://stage.cvm-k.com/21.6.B/disneystorytime-pt/video/TS4_PT_Part1_T.mp4

**Comment by viktor-timchenko** [comment]
To add more details about the issue below:

- OS version number: ANDROID 10.x only (on ANDROID 6, 7, 8 & 9 this issue is not reproducible).
- Media link is https://stage.cvm-k.com/base/disneystorytime-pt/video/TS4_PT_Part1_T.mp4
- steps to reproduce: the issue is reproducible each time when pause is taken for more than 7 seconds

**Comment by AndrewRH** [comment]
Hi @viktor-timchenko 

If you switch the Video API from ExoPlayer to MediaPlayer does that have any effect on this issue?

Thanks,

**Comment by MalyshkinAleksandr** [comment]
Hi @AndrewRH 

At the Android 10 work only ExoPlayer.

**Comment by RenderHeadsSte** [comment]
@MalyshkinAleksandr that is very interesting in itself!  Could you maybe post a logcat snippet of what is spat out when trying with the MediaPlayer API?

I will hopefully be able to get an Android 10 device later this week.  I am hoping it is Android 10 specific rather than Samsung + Android 10

**Comment by MalyshkinAleksandr** [comment]
@RenderHeadsSte 

List of devices that the bug reproduces in:
	
OnePlus 6
OnePlus 6T
Samsung Galaxy Note 10
Samsung Galaxy Note 10+
Samsung Galaxy S9
Samsung Galaxy J6
Samsung Galaxy A71

**Comment by MalyshkinAleksandr** [comment]
Also, I found comments regarding stopping the video. Maybe it's information can help you.

[https://www.gitmemory.com/issue/RenderHeads/UnityPlugin-AVProVideo/19/504072013](url)

**Comment by RenderHeadsSte** [comment]
What version of AVPro Video are you using? (gets printed out to logcat)

**Comment by AndrewRH** [comment]
hi @MalyshkinAleksandr , @HalynskyiDigicode , @viktor-timchenko 

We're looking into this issue - but if you could provide us with the following it could really help:

1) The exact version of AVPro Videos (it is printed in the Unity editor console window, but it's best to get it from the Android log cat itself just to be sure what is running on Android)
2) Could you send us the full Android log cat please?  It could include the time around when you pause the video and then try to play it again so we can see if there is anything in the log.  Note that it should be the full log, not just limited to Unity messages
3) Could you show us what code / methods you're using to Pause and Resume the playback?
4) Could you confirm what happens if you switch from ExoPlayer to MediaPlayer video API (this can be done on the MediaPlayer component, under the Platform Specific > Android section)

On our side we're working to try to replicate the issue so we can fix it.

Thanks,

**Comment by RenderHeadsSte** [comment]
This issue will be closed soon due to a lack of response

**Comment by MalyshkinAleksandr** [comment]
@RenderHeadsSte today we will give you the response

**Comment by MalyshkinAleksandr** [comment]
1. AVProVideo] Initialising AVPro Video (script v1.10.1 plugin v1.10.1)
2.[https://drive.google.com/file/d/13V19bkKdZ-Rk9C9_KHWKt6gBhVozqT3e/view?usp=sharing](url)
3. Call from class MediaPlayer  - Pause() [https://drive.google.com/file/d/1jHHyr_-6o_o4uZzHWxtpc2wTV0yCDGKU/view?usp=sharing](url)
4.  earlier we have a logic:
    -  Stopped video with Exo/Media player
    -  Call API method Stop()
    -  Change video player (Exo/Media) and call API method Play()

but it's an idea not worked.

Thanks for the feedback and we wait for fixes from your side
