### ISSUE TITLE
In WebGL build, first video plays again instead of second video playing

### ISSUE THREAD

**Issue by jlscurran** [RenderHeads/UnityPlugin-AVProVideo#357]
Problem description:

We are trying to play one video on a mesh renderer, then close it, load a second video and play that.
Unfortunately the first video just plays again. We don't see this issue in the editor.

Device (which devices are you having the issue with - model, OS version number):

Firefox

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

2 videos, h.264. Videos are in StreamingAssets. First video is 720p; second is 1080p

System Information:

AVPro Video: plugin v1.11.0 scripts v1.11.0
Target Platform: WebGL
Unity: v2019.2.0f1 WindowsEditor
OS: Desktop - HP ZBook 17 G6 (HP) - Windows 10  (10.0.0) 64bit - English
CPU: Intel(R) Xeon(R) E-2286M CPU @ 2.40GHz - 16 threads - 65382KB
GPU: NVIDIA Quadro RTX 5000 - NVIDIA - Direct3D 11.0 [level 11.1] - 16170KB - 16384

**Comment by AndrewRH** [comment]
Hi,

What code are you using to play the second video?

Thanks,

**Comment by jlscurran** [comment]
Hi Andrew,
The code we are using is
```
m_videoPlaying.m_VideoPath = m_Clip2;
        m_videoPlaying.OpenVideoFromFile(MediaPlayer.FileLocation.RelativeToStreamingAssetsFolder, m_Clip2, true);
```
In case it is important, this code is part of a coroutine.
In the past we have also tried opening the video in a different MediaPlayer object, but had the same result.

**Comment by AndrewRH** [comment]
Hmm..that's strange...  That code looks fine.
Did you check the browser console window to see if there are any clues there?
I will do some tests on this end and let you know what we find.

**Comment by jlscurran** [comment]
Nothing unusual in the browser console unfortunately.

**Comment by AndrewRH** [comment]
Hi, I can't replicate the issue you describe.  I'm using the same Unity version as you, and I've tried in both Firefox and Chrome.

Here's the code I'm using to test:
`using UnityEngine;
using RenderHeads.Media.AVProVideo;

//-----------------------------------------------------------------------------
// Copyright 2015-2020 RenderHeads Ltd.  All rights reserved.
//-----------------------------------------------------------------------------

namespace RenderHeads.Media.AVProVideo.Demos
{
	/// <summary>
	/// A demo that shows how to use scripting to load videos
	/// </summary>
	public class ChangeVideoExample : MonoBehaviour
	{
		[SerializeField]
		private MediaPlayer _mediaPlayer = null;

		void Start()
		{
			StartCoroutine(Routine());
		}

		public void LoadVideo(string filePath)
		{
			_mediaPlayer.m_VideoPath = filePath;
			_mediaPlayer.OpenVideoFromFile(MediaPlayer.FileLocation.RelativeToStreamingAssetsFolder, filePath, true);
		}

		System.Collections.IEnumerator Routine()
		{
			while (true)
			{
				yield return new WaitForSeconds(5f);
				LoadVideo("AVProVideoSamples/SampleSphere.mp4");
				yield return new WaitForSeconds(5f);
				LoadVideo("AVProVideoSamples/SampleCube.mp4");
			}
		}
	}
}`

Perhaps you could try to see if this works for you?
Otherwise, check you have latest browser versions and also latest GPU driver versions (both Intel and Nvidia).

A few more questions:
1) If you use our sample videos instead of your videos, does that help?
2) If you force your GPU to be either Intel or Nvidia (via Nvdia Control Panel) does that help?
3) Have you tested on other systems?  Do you get the same results?

Otherwise please send us your project so we can take a look.

Does that help?

Thanks,

**Comment by jlscurran** [comment]
Hi Andrew,
Thank you for the time you have spent on this. After a change in our Scene structure we are no longer having this issue.
