### ISSUE TITLE
Visible seam in 360 video sphere prefab (WebGL build)

### ISSUE THREAD

**Issue by jlscurran** [RenderHeads/UnityPlugin-AVProVideo#358]
- Unity version: 2019.2.0f1
 - AVPro Video version: plugin v1.11.0 scripts v1.11.0
 - Operating system version: Windows 10  (10.0.0) 64bit - English
 - Device model: HP ZBook 17 G6
 - Video specs: 1920x1080; 30fps; h.264; 73.6MB (mono)

**To Reproduce**
1. Add the 360SphereVideo prefab to the scene
2. Place the video in StreamingAssets and set the relative path in the MediaPlayer component
3. Build the project for WebGL

We have tried with a custom sphere setup and had the same issue so the issue is most likely with the video.

Screenshots: to be emailed

**Comment by AndrewRH** [comment]
I think you will have to post the screenshot via GitHub website, as emails don't seem to come through with screenshots.

Do you also see the seam in the Unity editor?
Have you tried playing with the texture filtering options in the "visual" section of the MediaPlayer component?

**Comment by AndrewRH** [comment]
Ok thanks we received the image via email

**Comment by jlscurran** [comment]
Hi Andrew,
We don't see the seam in the editor; only the build. None of our changes to the texture filtering options made any difference.

**Comment by jlscurran** [comment]
We looked into it a bit more and realised we only have this problem with mono videos. Top-bottom stereo works fine in the editor and in builds.

**Comment by AndrewRH** [comment]
Hmm that's strange about the seam...  I have a few questions:
1) Which browser are you using?  Have you tested in other browsers?
2) Are you using any special WebGL build settings (eg development mode, stripping etc?)
3) What happens if you use our 1920x1080@30 sample video (SampleSphere.mp4)?
4) Is it possible you could send us your video file?
5) And/or could you send us the detailed MediaInfo about the file?  I'm starting to think it coudl be something to do with display/source aspect ratio being non-square...

Thanks,

**Comment by jlscurran** [comment]
Hi Andrew,
Thank you, but after using a new video file we are no longer having this issue.
