### ISSUE TITLE
HLS videos not reproducing

### ISSUE THREAD

**Issue by joanmitjansamuse** [RenderHeads/UnityPlugin-AVProVideo#361]
**Problem description:**

When I select an HLS video and  click play on the editor, it freezes for some time. 
After loading, an error message appears: 

```
[AVProVideo] Failed to open https://cdn.mini-mango.com/47/292/hls/index_b44c7882-f81d-4f0e-9d92-34f73ff52e93.m3u8
UnityEngine.Debug:LogError(Object, Object)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenVideoFromFile() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:1213)
RenderHeads.Media.AVProVideo.MediaPlayer:Start() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:828)
```

Loading from streaming assets .mp4 works fine (your example videos). 
On a builded version, the HLS video doesn't play either. 

Also, I bought the Android version of the plugin, but for some reason the watermark doesn't disappear (but this might be another issue, I will send you an email for that one). 

I tested in your example scenes to make sure the bug was not triggered by anything else. I also checked the HLS links were available. 

I used to work at home and it worked fine, but at the office it doesn't work on my PC. I will check later at home if it works on my other computer. 

Unity Version: 2019.3.7f1
Plugin Version: 1.11.0

![avpro_bug](https://user-images.githubusercontent.com/60705665/82313783-22d3bf00-99c9-11ea-86a2-7bc1cd1e313f.png)

Thank you very much for your attention, 

minimango team 
joan.m@amusenetwork.com

**Device (which devices are you having the issue with - model, OS version number):**

Unity Editor Windows, All Android devices tested (Galaxy S7, for example) 

**Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):**

video example: 
https://cdn.mini-mango.com/47/292/hls/index_b44c7882-f81d-4f0e-9d92-34f73ff52e93.m3u8

**System Information:**

AVPro Video: plugin v1.9.17t scripts v1.11.0
Target Platform: Android
Unity: v2019.3.7f1 WindowsEditor
OS: Desktop - HP Z240 Tower Workstation (HP) - Windows 7  (6.1.0) 64bit - French
CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz - 8 threads - 32688KB
GPU: NVIDIA Quadro M2000 - NVIDIA - Direct3D 11.0 [level 11.0] - 4010KB - 16384

**Comment by AndrewRH** [comment]
Hi,
Thanks for reporting your issue.  
The first thing I can see is that your Windows plugin version doesn't correspond to the script version.  This can easily happen if you upgrade after the plugin files have loaded, which causes them to become locked and they can't be upgraded.  To fix this:
1) Close Unity
2) Open Unity
3) Upgrade to the latest AVPro Video version without clicking on anything else or running your project etc.
4) Then your plugin version should match or be much closer to your script version.
This will also mean you will get many of the improvements and benefits we have added since 1.9.17.

The reason for HLS not working may be because you're using Windows 7.  I believe Windows only started supporting HLS from Windows 10 onwards...  To add support on Windows 7 you can install [LAV Filters](https://github.com/Nevcairiel/LAVFilters/releases) and then in the MediaPlayer component, set the Video API to DirectShow.

Does that help?

**Comment by joanmitjansamuse** [comment]
It is now working. Thank you very much for the fast support!
