### ISSUE TITLE
Problems playing a video file with 1920x1080 resolution

### ISSUE THREAD

**Issue by MixerKim** [RenderHeads/UnityPlugin-AVProVideo#382]
**Describe the bug**
I have a video file. this is 1920x1200 , 30fps, and encoded AVC1.
when it play in AVPro Media Player, it occurs a follow message.

*[AVProVideo] If video fails to play then it may be due to the resolution being higher than 1920x1080 which is the limitation of the Microsoft DirectShow H.264 decoder.
To resolve this you can either use Windows 8 or above (and disable 'Force DirectShow' option), resize your video, use a different codec (such as Hap or DivX), or install a 3rd party H.264 decoder such as LAV Filters.*

and nothing happen.

but, I have other video file. this is 4096x2048, 30fps, and encoded AVC1.
it plays well.

I think it is bug.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.12f
 - AVPro Video version: 1.11.0
 - Operating system version: Windows10 Home  64bit  1909
 - Device model: i7-4790, 32GB, GTX1060 6GB
 - Video specs (resolution, frame-rate, codec, file size): 1920x1200, 30fps, AVC1, 653MB, 05:57
 - **use 'Direct Show' and 'Lavfilter 0.74.1'**
 - **If change Direct Show to Media Foundation, it works. but I need 3rd party codec. therefore I cant use Media Foundation**

**Comment by AndrewRH** [comment]
Hi,

I actually suspect that it's the audio in the file that's causing the problem.  Could you try to remove the audio track and try again?  Ideally it should be encoded with AAC-LC.

Otherwise, could you send us the video file (or ideally a snippet of it) that is failing to play?

Thanks,

**Comment by MixerKim** [comment]
Both files are encoded in AAC, 48000 Hz, 16 bit, 317.37 kbps.

and.. Because they are Commercial video, I cant send you them.

I removed the audio track and try again, but it occurs, too

**Comment by AndrewRH** [comment]
Ahh well I'm not sure what the issue could be then.  Any chance you could snip the video and send it to us?  unitysupport@renderheads.com

Otherwise could you run [MediaInfo ](https://mediaarea.net/en/MediaInfo) on the file (in the View > Text menu) and show us the output? This will give us details on the exact encoding.

Here is what it typically looks like:

```General
Complete name                            : C:\Users\Andrew\Videos\Captures\AVProVideo - Microsoft Visual Studio 2020-04-28 16-07-22.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (mp41/isom)
File size                                : 2.51 MiB
Duration                                 : 16 s 180 ms
Overall bit rate                         : 1 300 kb/s
Movie name                               : AVProVideo - Microsoft Visual Studio
Performer                                : Microsoft Game DVR
Encoded date                             : UTC 2020-04-28 15:07:38
Tagged date                              : UTC 2020-04-28 15:07:38
Xtra                                     : {0CEF7D53-FA64-11D1-A203-0000F81FEDEE} 4

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L4.1
Format settings                          : CABAC / 1 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 1 frame
Format settings, GOP                     : M=1, N=29
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 16 s 180 ms
Bit rate                                 : 777 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 044 pixels
Display aspect ratio                     : 1.85:1
Frame rate mode                          : Variable
Frame rate                               : 26.391 FPS
Minimum frame rate                       : 14.993 FPS
Maximum frame rate                       : 62.112 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.015
Stream size                              : 1.50 MiB (60%)
Encoded date                             : UTC 2020-04-28 15:07:38
Tagged date                              : UTC 2020-04-28 15:07:38
Codec configuration box                  : avcC

```

Thanks,

**Comment by AndrewRH** [comment]
Thanks for sending through the video.  I think I have replicated the issue - it does seem be a be a bug.  I will let you know once we have looked further and hopefully have a fix it for.  The bug seems to be caused because the video height is 1200 which is above the 1088 maximum height of the DirectShow H.264 decoder, and causes the visuals not to be displayed.

There are two workarounds that you could try for now:
1) If you have "LAV Filters" installed, then you can force it to use this instead of the default one, you just need to enter "LAV Video Decoder" into the DirectShow Preferred Filters section:
![image](https://user-images.githubusercontent.com/5418126/84421861-13d0dd00-ac14-11ea-8c1b-72f254aaa9b7.png)

2) Alternatively you can just use Media Foundation API.  I'm not sure why you aren't using this, but want to use DirectShow instead.   Media Foundation can play back this video without installing any 3rd party codecs.  

I hope this helps you.  I will get back to you once we have more information about the issue.

Thanks,

**Comment by MixerKim** [comment]
fd

**Comment by MixerKim** [comment]
I didn't know if I could force the filter in DirectShow Options.

As mentioned in No. 1, it played properly.

When using Media Foundation, it seems that external codecs cannot be used. Besides , I have to play multiple videos, but other videos cannot be loaded when using Media Foundation.

Anyway, it was solved. Thank you.

**Comment by AndrewRH** [comment]
Okay glad that you have it solved.  We will release the next version with that loading issue fixed for DirectShow.   Thanks,
