### ISSUE TITLE
mp4 video distorted in Unity editor

### ISSUE THREAD

**Issue by IcyPoint** [RenderHeads/UnityPlugin-AVProVideo#383]
**Describe the bug**
.mp4 video was distorted in the Unity editor(see blow), it is much better when I play it with a windows desktop video player;

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.21f1
 - AVPro Video version: script v1.10.0 plugin v1.9.17
 - Operating system version: win10 1909
 - Device model: in editor
 - Video specs (resolution, frame-rate, codec, file size): 
2208x1142;
 30; 
Media Foundation with Hardware Decoding checked;
3.92M;

**To Reproduce**

**Logs**

**Screenshots**
![TIM截图20200612163042](https://user-images.githubusercontent.com/6270910/84483537-0d05a100-accc-11ea-8a95-bd3105acff11.png)

**Comment by IcyPoint** [comment]
And if a video without striking contrast, it will be fine.

**Comment by IcyPoint** [comment]
Edit : Media Foundation WITHOUT Hardware Decoding checked, solved this problem. - -!

**Comment by AndrewRH** [comment]
Hi @IcyPoint 

Thanks for reporting your issue.

I have a few requests:
1) Could you try with the latest version of AVPro Video please?  We have fixed some related issues with Linear Colourspace (which I believe may be causing your issue here).  When you upgrade to the latest version you should do soe from a freshly opened Unity, so that the DLL files are not locked and can upgrade correctly.

2) If that doesn't solve it, could you send another screenshot showing how it should look?

3) Perhaps you could also consider sending us your video (private files can be sent via unitysupport@renderheads.com) - or maybe just testing with our sample videos (in StreamingAssets folder) and letting us know whether you have the same issue with those or not.

Thanks,

**Comment by AndrewRH** [comment]
Hi @IcyPoint  any update on those questions?

Thanks,

**Comment by IcyPoint** [comment]
Hi Andrew:
Year, finally we figured it out that we have a Linear color space setting in Unity, so we called GammaToLinear in shader, it's gone.
Thanks.
