### ISSUE TITLE
avpro video1.11.0 and 111.2 can not open URL video on Android.

### ISSUE THREAD

**Issue by 1932161324** [RenderHeads/UnityPlugin-AVProVideo#385]
avpro video1.11.0 and 111.2 can not open URL video on Android.
url:http://toyota1-1258556682.cos.ap-guangzhou.myqcloud.com/afvideo/bd198d28-803b-4529-9c1d-bdf95dce5565.mp4
Unity：2019.3.8f1
jdk：1.8.0_251
sdk：29
Gradle：6.4
playerSetting is default.

**Comment by 1932161324** [comment]
Unity editor and build ios successfully opened the url.

**Comment by AndrewRH** [comment]
Hi,

I believe on Android 9 and above HTTP streaming is not supported by default.  You have to use HTTPS url, or you have to enable 'cleartext' in the AndroidManifest.xml.

https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6

This may be the issue you're having.

Otherwise please supply here the adb log cat from the device, so we can look for the reason why it's failing to open the URL.

Does that help solve it?

Thanks,

**Comment by 1932161324** [comment]
Ok, thanks a lot
