### ISSUE TITLE
How do I preload video to get a smooth experience at first time playing?

### ISSUE THREAD

**Issue by ProgramForFun** [RenderHeads/UnityPlugin-AVProVideo#392]
I tried to preload the video via OpenVideoFromFile while scene loading, but it seems that it doesn't load the video actually because I still get a short freezing before first time the video start playing. Did I do something wrong?
Thanks.

**Comment by AndrewRH** [comment]
We don't provide any preloading features.  You could perhaps try to load the video without autoplay enabled, and then after a second or two manually play the video.  Does that help?

Also some videos are just more complex due to their heavy encoding, and they can take a while to start.  So you could encode your videos in a simpler way to make them faster play back.

Otherwise, perhaps you could provide the video file to us so we can take a look.

Thanks,

**Comment by AndrewRH** [comment]
It would at least be useful to know which platform this is on, and the specs of your video file.

Thanks,

**Comment by MorrisRH** [comment]
Closing due it inactivity
