### ISSUE TITLE
Crash consuming an URL Matroska stream

### ISSUE THREAD

**Issue by PinoEire** [RenderHeads/UnityPlugin-AVProVideo#393]
**Describe the bug**
The plugin appears not to recognise the Matroska stream from the local test server. I'm using this Matroska server: https://nxs.re/2017/05/11/matroska-server.html Its output works fine with VLC player, so I suppose the issue is with this asset.

**Your Setup (please complete the following information):**
 - Unity version: 2019 LTS (2019.4.1f1)
 - AVPro Video version: 2 Beta 1
 - Operating system version: UWP
 - Device model: dev device: Win 10 PC - target device: Hololens 2
 - Video specs (resolution, frame-rate, codec, file size): URI streamed from Matroska Server

**To Reproduce**
1.  Build the Matroska server from the repo at https://gitlab.com/nitroxis/matroskaserver 
2. run it as-is. then stream in a loop one of the Azure Kinect test files with the following command:
ffmpeg -stream_loop -1 -re -i THEFILEHERE.MKV  -f matroska -live 1 -map 0 "https://localhost:5001/m.mkv"
3. In the demo scene replace the source with http://localhost:5000/m.mkv
4. Run the scene: it will not work. Loading it in the editor will crash Unity.
5. You can see that using the VLC player the URI http://localhost:5000/m.mkv will play as expected

**Logs**
Nothing meaningful

**Screenshots**
n/a

**Videos**
Too big to attach here

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi @PinoEire 

Thanks for reporting this.

I suspect the issue may not be related to the streaming MKV, but rather the format of the video tracks contained within.  I'm guessing this because the other videos you sent us from the Kinect Azure didn't play due to this issue.
If it's a different file/format then perhaps you could send that to us for analysis?
Otherwise I will link this to the issue of the gray10le pixel format (#396) as I believe it's related.

Thanks,

**Comment by AndrewRH** [comment]
I'm closing this issue and we can keep track of everthing in the main thread: #396
