### ISSUE TITLE
New methods GetVideoTrackCount() and SetVideoTrack(trackNumber) not doing anything at all

### ISSUE THREAD

**Issue by PinoEire** [RenderHeads/UnityPlugin-AVProVideo#395]
**Describe the bug**
- The method mediaPlayer.Info.**GetVideoTrackCount()** always returns zero, no matter how many video tracks are in the container.
- The method mediaPlayer.Control.**SetVideoTrack(trackNumber)** does nothing, no matter what value I set in trackNumber

**Your Setup (please complete the following information):**
 - Unity version: 2019 LTS (2019.4.1f1)
 - AVPro Video version: 2 Beta 1
 - Operating system version: UWP
 - Device model: dev device: Win 10 PC - target device: Hololens 2
 - Video specs (resolution, frame-rate, codec, file size): 1280x720, 30FPS. It's an Azure Kinect Matroska container with 3 video tracks in it (colour, depth and IR) produced by Microsoft using their Kinect Recorder.

**To Reproduce**
Try to get and set the number of video tracks.
**Logs**
no logs, the methods just do nothing

**Comment by AndrewRH** [comment]
Ok I think this is all the same issue - all related to pixel formats of the MKV that Kinect Azure produces.

If you want to play these videos in AVPro Video then you would have to transcode those tracks into something more standard such as yuv420 pixel format.  A tool like FFMPEG can be used to do this.  The Azure MKV contains very uncommon pixel formats in the Depth and IR tracks.

I'm linking in your other issues here #393 #396 

Here is a reference to the file spec
https://docs.microsoft.com/en-us/azure/kinect-dk/record-file-format

I'm closing this issue and we can keep track of everthing in the main thread: #396 

Thanks,

**Comment by PinoEire** [comment]
It appears that URL streaming doesn't work. I'm streaming a Matroska file locally. The file contains two tracks. If I load the file from the streaming asset folders both tracks work. From the HTTP stream, it recognises the two tracks but doesn't play, giving the usual error. I can see both tracks using a client such as VLC or SMPlayer.

The file I'l streaming locally over HTTP is this one: https://drive.google.com/file/d/1RdxKJamEciAbEPQLybLDucViMFGhDGrp/view?usp=sharing 

This is from VLC (both tracks) 
![image](https://user-images.githubusercontent.com/460651/86105022-b9aa9580-bab6-11ea-84a0-20251ac9f5ff.png)

In Unity:
![image](https://user-images.githubusercontent.com/460651/86105167-e8c10700-bab6-11ea-9c74-b0ebad4a7bfc.png)

**Comment by AndrewRH** [comment]
hi,

I uploaded the video to a server and streamed it from the URL.   It seemed to play back fine.  I could select either track and they would both display:

![image](https://user-images.githubusercontent.com/5418126/86278061-aa6b3b00-bbcf-11ea-99e5-02e4de6e89f2.png)
![image](https://user-images.githubusercontent.com/5418126/86278014-958ea780-bbcf-11ea-8b4f-2e1f9ce716ec.png)

I'm not getting any error messages...
I wonder why it's not working with your setup...

1) Which version of Windows are you using?  (I'm on Windows 10 version 1909, we rely on Windows runtime so this could be a factor)
2) Which GPU are you using (I'm on Geforce 1060, support for decoding certain formats can be GPU dependent)

Beta 2 of the plugin should be out soon, and we have improved support for video tracks, so perhaps you could try that.  Otherwise I wonder if it would make a different if both tracks were encoded as H.264?

Thanks,
