### ISSUE TITLE
Issue with Oculus Go video playback.

### ISSUE THREAD

**Issue by tavac** [RenderHeads/UnityPlugin-AVProVideo#416]
Problem description:

When trying to launch videos from the oculus go, they refuse to load resulting in a black sphere. When the project was based around Unity's OpenVR architecture, the plugin worked flawlessly, and was able to stream the videos using a URL, however, when the project was re-arched to used Oculus integration, it partially ceased working. While the videos do play when executed from the editor and from a windows strandalone build, no playback ocurrs on the GO. This is happening on Unity 2019.2.4f1 with the OpenGLES3 API, AVPro Video version 1.10.2 (scripts v1.10.3), and an Oculus Go running the latest firmware.

Device (which devices are you having the issue with - model, OS version number):

Oculus Go, version 18.0

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

http://ahutraining.com/TrainingScenarios/Lobby.mp4,  Oculus Go log file: https://pastebin.com/afKaGdiG

System Information:

AVPro Video: plugin v1.10.2 scripts v1.10.3
Target Platform: Android
Unity: v2019.2.4f1 WindowsEditor
OS: Desktop - To be filled by O.E.M. (Gigabyte Technology Co., Ltd.) - Windows 10  (10.0.0) 64bit - English
CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 8 threads - 16263KB
GPU: NVIDIA GeForce GTX 1070 - NVIDIA - Direct3D 11.0 [level 11.1] - 8088KB - 16384

**Comment by RenderHeadsSte** [comment]
I have tested your video here on a GO using one of our demo test scenes and playback works perfectly.  I notice you have Multithreaded Rendering disabled, so I tried that here also...playback was still fine.

We have seen the Oculus libraries refuse to mesh with AVPro due to their use of the ExoPlayer package (something we how to have addressed in version 2.0).  Could you try switching the API Path from 'ExoPlayer' to 'MediaPlayer'?

The log you sent gives almost no hint of what might be the root of the cause.  Is it complete and unfiltered?

Finally, you are running a slightly out-of-date version of AVPro Video.  Updating is always advisable.  Maybe you could try that?

**Comment by tavac** [comment]
Hello! Thanks for taking the time to respond.

I have updated AVPro Video to the latest version (1.11.3) and switched from ExoPlayer to MediaPlayer, sadly to no avail. It appears I sent a filtered log, [this one](https://pastebin.com/wcP7VWKM) contains all of the logs from startup until a little bit after the application is supposed to start loading the video.

I have attached pictures of what my media player settings currently are, as well as android build settings. Let me know if you need any more information.

Thanks again for your help.


![Annotation 2020-07-17 174447](https://user-images.githubusercontent.com/44653771/87833001-3ed2d000-c855-11ea-8ad2-5f55fc9e74dc.png)

![Annotation 2020-07-17 174100](https://user-images.githubusercontent.com/44653771/87832787-b9e7b680-c854-11ea-851c-d9778a930fba.png)

**Comment by RenderHeadsSte** [comment]
Can you confirm your video plays back for you in one of our demo scenes on your GO?  If it does, then I would need a copy of your project sent to unitysupport@renderheads.com in order to investigate further, as it plays back just fine here for me on a GO.
