### ISSUE TITLE
Skybox inverted

### ISSUE THREAD

**Issue by SpecularTheoryBen** [RenderHeads/UnityPlugin-AVProVideo#42]
I am trying to use a 360 video for a skybox but it keeps showing up upside down. I have a Skybox/Panoramic material, latlong layout, 360 image type. I have looked at the ApplyToMaterial script and tried inverting the y scale, but it has no effect.

**Comment by RenderHeadsSte** [comment]
Please provide the following information:

- Unity version:
- AVPro Video version:
- Operating system version:
- Device model:
- Video specs (resolution, frame-rate, codec, file size):

**Comment by RenderHeadsSte** [comment]
Closing issue due to lack of response.

**Comment by visjack** [comment]
I've had the same problem as reported, probably a setting that I've not applied or something. The video being projected to the skybox material appears to be inverted, upside down and back to front, almost looks like it has been projected to the outside of the skybox rather than the inside. The preview within Media Player is correct but the skybox material preview is inverted.

Unity version: 2019.1.1f1
AVPro Video version: 1.10.1
Operating system version: Win10
Device model: Built for Android OculusGo but experienced in preview in Unity
Video specs (resolution, frame-rate, codec, file size): 4096x2048, 59.94fps, .MKV made from FB360Encoder
