### ISSUE TITLE
Video Wont Play on MAC or IOS

### ISSUE THREAD

**Issue by nsmith1024** [RenderHeads/UnityPlugin-AVProVideo#420]
**Describe the bug**

Video at a URL plays on PC and Android, same link given on MAC and IOS does not play

**Your Setup (please complete the following information):**
 - Unity version:  2018.3.14
 - AVPro Video version: 1.10.1
 - Operating system version: MAC Catalina
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Give Video player this URL https://apps.basereality.tv:8443/stream.php?k=DD397f%3b2C%40cBe6%3d49f%3eaG%3dcaCbUGH2aal%60%60_fgUIFC%3dl%3a%3e286D%5e%600g4%60degbfg52g7e62c4fb2d6_d4he272%60%5d%3eAc

2. It doesnt play on MAC or IOS, but same URN plays on Android and PC
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

https://apps.basereality.tv:8443/stream.php?k=DD397f%3b2C%40cBe6%3d49f%3eaG%3dcaCbUGH2aal%60%60_fgUIFC%3dl%3a%3e286D%5e%600g4%60degbfg52g7e62c4fb2d6_d4he272%60%5d%3eAc

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
The URL you provided requires a captcha to be completed in order to open the video. AVPro Video is unable to proceed due to this as the response from the server is a 403: Forbidden.

Using Safari, I was able to pass the captcha, however the video will not play. This is usually a good indicator as to whether or not it will play in AVPro Video. From the looks of it the video is just an mp4 but as the path in the url has the extension php the system is unable to recognise it as an mp4 (even though the content type in the response header is correct). If the path was stream.mp4 I would expect it to playback fine. This is a system level issue and as such not something we can fix.

**Comment by nsmith1024** [comment]
If i use Chrome and click on that same ink, the video plays on my computer, no captcha appears.

**Comment by nsmith1024** [comment]
I removed the captcha, that was a bug on my part bug its fixed now, but it still doesnt play on MAC or IOS, can you please check it now since i removed the Captcha bug? 

The link plays fine on PC and Android using your player without the mp4 at the end, why would it need mp4 just for Max or IOS if its the same player? If i click on link using firefox, or edge browser it plays fine as well.

**Comment by MorrisRH** [comment]
The macOS and iOS plugins are built using Apple's video playback API: AVFoundation. Unfortunately AVFoundation requires that the file extension be correct in order for it to be able to recognise the file type, in this case it needs to be mp4 in order for the video to play back. Chrome and Firefox provide their own video playback mechanisms which is why it works for them.

We do appreciate that this is a nuisance, but at this time there is nothing we can do about it as the problem is external to AVPro Video.
