### ISSUE TITLE
Unity crashes when calling SetPlaybackRate function

### ISSUE THREAD

**Issue by Sungki-Hong** [RenderHeads/UnityPlugin-AVProVideo#422]
Problem description:

Unity Version : 2017.1.2f.1
AVPro Video version : 1.11.3
NGUI : 3.9.7

I'm trying to call setPlaybackRate after OpenVideoFromFile.

bool isOpenFromFile = mMediaPlayer.OpenVideoFromFile(MediaPlayer.FileLocation.AbsolutePathOrURL, mMediaPlayer.m_VideoPath, true);
if (true == isOpenFromFile)
{
    DebugLog("Function:OpenVideo = PlayRate[" + playRate + "]");

     mMediaPlayer.Control.SetPlaybackRate(playRate);
}

DebugLog("Blah Blah Blah..");

There is no issue almost time but rarely occured an issue what Unity player freezing.

The last log was "Function:OpenVideo = PlayRate[" + playRate + "]" in my log file.

If you want my video file or another informations, 

send me an email skhong83@namedstudio.com

I'll hope your answer, 

Thank you

Device (which devices are you having the issue with - model, OS version number):

Window7

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

Video : H264(24 bit), 480x640p, FPS:70, bitRate: 18111kbsp, yuv420p

System Information:

AVPro Video: plugin v1.11.1 scripts v1.11.3
Target Platform: Standalone
Unity: v2017.1.2f1 WindowsEditor
OS: Desktop - To Be Filled By O.E.M. (To Be Filled By O.E.M.) - Windows 10  (10.0.0) 64bit - Korean
CPU: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz - 6 threads - 16301KB
GPU: NVIDIA GeForce GTX 1660 - NVIDIA - Direct3D 11.0 [level 11.1] - 5991KB - 16384

**Comment by AndrewRH** [comment]
Thanks for submitting this bug report.

Since you're using Windows 7, our player will be using the DirectShow API.  The problem with DirectShow is that it could be using any 3rd party filters/decoder installed on your system, and those could contain bugs.

Are you able to replicate this crash on another system?

Are you perhaps able to see whether you have any 3rd party codecs installed, such as Shark, K-Lite or LAV Filters?  If so you could try to upgrade those to a newer version or removing them.

You could also try setting the playback rate like this:

mMediaPlayer.m_PlaybackRate = playRate;
mMediaPlayer.OpenVideoFromFile(MediaPlayer.FileLocation.AbsolutePathOrURL, mMediaPlayer.m_VideoPath, true);

Also, when it crashes, Unity should produce a crash log.  Perhaps you could attach that here?

Does that help?

**Comment by Sungki-Hong** [comment]
I've changed my code as you said and see.

In my case when it crashes, Unity was just freezing and no response.

I figure out it specific 3rd party codec in the document. I'm gonna try to set preferred filters.

is this right way with preferred filters?

Thanks for your help.
