### ISSUE TITLE
Long time loading video

### ISSUE THREAD

**Issue by mpn7** [RenderHeads/UnityPlugin-AVProVideo#432]
**Describe the bug**
I'm trying to show a video via HLS m3u8, and the video shows but it takes 2 seconds in a blackscreen and after that it shows the video in a really low quality during 3/4 seconds. And if Iseek the video to the beginning It shows the video in a terrible quality again.

I've tried pausing the video in the beginning, waiting 1 sec and then play but it doesn't seem to have an effect.

Is there a way to wait until the quality is "ok"? 
Why does it have to load the video again when I seek to the beginning?

**Your Setup :**
 - Unity version: 2019.2.11f
 - AVPro Video version: 1.11.4t

**Videos**
https://player.vimeo.com/external/444183981.m3u8?s=fcfef692baece302eb39470e5d950c88e9149057

**Comment by AndrewRH** [comment]
Which platform is this on?

If it's Windows - then yes it always starts with the lowest quality and then slowly ramps up at it detects the bandwidth available.  We currently don't offer any control over this, but in version 2.0 of the plugin which we're working on now, there will be control exposed, so that you can start at the highest quality, or a specific quality level.

As for the 2 seconds - that doesn't sound unreasonable for HLS.  It has to download a number of chunks first, so it depends how large each chunk is...

There's nothig we can do about these issues in version 1.x, which is why we're working on 2.0 now.

Thanks,

**Comment by mpn7** [comment]
I have now tested on android, it just stays black until the max quality is loaded... for most of my videos it's like more than 5 seconds.. Is there at least a way to know when the video actually starts so I can put a loading instead of just a black screen?

Thank You for your answer!
