### ISSUE TITLE
video player package questions

### ISSUE THREAD

**Issue by domino33** [RenderHeads/UnityPlugin-AVProVideo#434]
Good day.
We want to purchase your video player package
https://assetstore.unity.com/packages/tools/video/avpro-video-windows-57969
Questions:
1) is it possible to use Youtobe live broadcasts on your video  player?
2) is it possible to work through http-proxy?
3) will there be problems when using versions 2019.xxx and 2020.xxx?

**Comment by AndrewRH** [comment]
Hi,

1) We're not sure, but in theory it should work.  We haven't tested it because it's against the usage terms of YouTube I believe, but in theory if you can get hold of a HLS/DASH manifest then it should play

2) I'm not sure.

3) Yes, this will work - the plugin supports Unity from version 4.6 to 2020

For the proxy question, you can always test it yourself using the trial version of the plugin:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases/tag/1.11.4

Does that answer your question?

Thanks,
