### ISSUE TITLE
Videos at 24FPS and 6 audio channels aren't playing on Windows Enterprise systems

### ISSUE THREAD

**Issue by DavidFerroImproving** [RenderHeads/UnityPlugin-AVProVideo#439]
**Describe the bug**
When using AVProVideo on 1920x1080 MP4 videos that are 24fps or 4096x968 MP4 videos that have 6 channels of audio and 30fps on Windows 10 Enterprise LTSC 1809 and Windows 10 Enterprise 1909, we get the error:
[AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources.
Videos that are 1920x1080 MP4 at 30fps and 4096x968 MP4 at 30fps with 2 channels of audio do work.

However, on Windows 10 Home 1903 and on Windows 10 Enterprise LTSB 1607 all of the above video file formats work without any errors.

**Your Setup (please complete the following information):**
 - Unity version: 2019.2.17f1
 - AVPro Video version: 1.10.1
 - Operating system version: The listed not working videos do not work on Windows 10 Enterprise LTSC 1809, Windows 10 Enterprise 1909
All the videos work on Windows 10 Home 1903 and Windows 10 Enterprise LTSB 1607

 - Device model: The listed not working videos do not work on HP Z2 Tower G4 Workstation
All the videos work on Lenovo 81TE, Falcon Tiki
 - Video specs (resolution, frame-rate, codec, file size): 
Does not work 1920x1080, 24fps, MP4, any size
Does not work 4096x968, 30fps, MP4, any size, 6 audio channels

Does work 1920x1080, 30fps, MP4, anysize
Does work 4096x968, 30fps, MP4, any size, 2 audio channels

**To Reproduce**
1. Build Windows Standalone app with AVProVideo
2. Play video file from script or directly
3. When meets criteria stated above, loads and plays or doesn't load or play.  

**Logs**
If applicable, add error logs to help explain your problem.
[AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources.

**Screenshots**
Blank screen, video doesn't play.
**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi,

It sounds to me like it may be a couple of issues.

As you know LTSC is a much more limited form of Windows, so it may be missing some features.

First it seems like there an a playback issue on your system for 24fps videos.  This may be a limitation of the GPU.  What GPU is in the system?  Are it's drivers up-to-date?  Have you tried changing the GPU to figure out whether it's caused by the GPU or the operating system.

Also what codecs are these videos using?  'MP4' isn't enough information for us - we need to know the video and audio codecs used to properly diagnose whether that could be a problem.  A tool like MediaInfo can help with this.

Second there seems to be an issue with playing back videos with 6 channels of audio on your one system.  Is the system set up for 6 channels of audio in the audio drivers?   What format is the audio in?

Also are you building a 64-bit or 32-bit app?  Building a 64-bit app generally has better compatibility these days with modern systems, as a lot of 32-bit dependencies are less well maintained, or sometimes not even available - so I definitely would recommend 64-bit builds.

In general I would also recommend upgrading to the latest version (1.11.4) of AVPro Video as we have fixed a number of issues since 1.10.1.

I hope that's helpful - if you could get back to me with more details then I'll can see what next steps to recommend.

Thanks,

**Comment by DavidFerroImproving** [comment]
Hi Andrew,

For all of the videos, the codec is H264 - MPEG-4 AVC (part 10) (avc 1).  For the six-channel audio videos, the audio codec is A52 Audio (aka AC3) (ac-3) and the channels are 3F2M/LFE at a sample rate of 48000 Hz and 32 Bits per sample.

Also, the app is a 64-bit app already.

I'm waiting to hear back from my team on the GPU and audio systems information as the machines were taken offline, but hopefully that gives you a start.

Thanks,
