### ISSUE TITLE
Hard crash in 2019

### ISSUE THREAD

**Issue by SpecularTheoryBen** [RenderHeads/UnityPlugin-AVProVideo#45]
When trying the demo scene in Unity 2019 using HDRP I am getting a hard crash.
The end of the Editor Log says the following
(Filename: Assets/AVProVideo/Scripts/Internal/Interfaces.cs Line: 605)
Unsupported D3D format 0x58
(Filename: C:\buildslave\unity\build\Runtime/GfxDevice/d3d11/TranslateD3D11.cpp Line: 252)
* Assertion at ..\mono\metadata\threads.c:1792, condition `internal' not met

**Comment by elhongo** [comment]
Same issue here. Looking forward to a fix asap. Thanks!

**Comment by pascal-teooh** [comment]
Similar issue on OSX. Playing a scene or selecting a game object with an AVPro component causes an editor crash. (2019.1.0f2)

**Comment by EarMaster** [comment]
Can confirm. The editor crashes as soon as a Media Player component comes into action.

**Comment by elhongo** [comment]
Any ETA on this fix?

**Comment by AndrewRH** [comment]
For Windows - seems that Unity has changed that way it supports externally created textures...I'm not sure if this is on purpose or a regression bug...there is nothing in the release notes about the change.  We are working on a workaround fix for this.

For macOS crash, we will investigate further.

**Comment by AndrewRH** [comment]
Thanks for your patience.

Just to let you know that we're releasing a new version of AVPro Video today (version 1.9.14) which includes support for Unity 2019.  You should be able to find it on the Asset Store for upgrade later today.  If you're using the trial version then 1.9.14 should already be available to download from our website.

When upgrading to the new version please make sure to follow these steps, otherwise the native plugin file can be locked by Unity which will prevent the upgrade from completing properly:

1) Close Unity
2) Open Unity
3) Don't click on any components or items in your scene, go directly to Step 4
4) Import the .unitypackage / update via the Asset Store

Do let us know if you have any problems or questions.
