### ISSUE TITLE
Frame corruption on 180FPS video when changing playback rate

### ISSUE THREAD

**Issue by pravinyadav** [RenderHeads/UnityPlugin-AVProVideo#458]
**Describe the bug**
Whenever I change the speed of video it renders black frames and then gets back to normal. For lower speed  (0.01 to 0.5) it takes longer time and when I increase it (bet 1 to 3) takes less time. But certainly it takes a while to get back to normal. 

**Your Setup (please complete the following information):**
 - Unity version:  Unity 2019.4.3f1
 - AVPro Video version: 1.11.2
 - Operating system version: Windows
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 
Res: 1920x1080,  H264  MPEG-4 (part10) (avc1) , Filesize : 1.91 GB

**To Reproduce**
1. Load a large video 
2. Change the  play back speed 
3. You will see few black frames

**Logs**
If applicable, add error logs to help explain your problem.
There are no errors

**Screenshots**
If applicable, add screenshots to help explain your [problem.]

![BlackFrameIssueWhileChangingPlaybackSpeed](https://user-images.githubusercontent.com/1094168/91687999-9bc4e400-eb7e-11ea-821e-614935361b26.jpg)

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by pravinyadav** [comment]
I have just uploaded the video for reference on OneDrive. It might help to debug the issue.

**Comment by AndrewRH** [comment]
Thanks for the video.

I believe the problem is that the video is authored at 180 frames per second!  

This is an unusual frame rate and it takes a lot of system resources to decode this video.

That said - I dont' get the black frames you're seeing, but if I make the speed faster than I do get corruption.  I suspect it is the GPU drivers that is causing the black frames - so perhaps try to update your drivers, or try on another system.  Playing back a 180fps video (especially at 3x speed) is certainly an edge case, so there is a change the different GPU video decoding drivers won't handle it correctly.  

Playing at a faster speed has a higher demand on the system resources - so you should check Task Manager > Performance tab to see if there is any bottleneck here.  It also depends on the specs of your system, so perhaps you could share those?

I would recommend some of the following:
1) Transcode your video to 30 or 60fps
2) You should insert more keyframes into your video - this will make it much easier for the decoder to play back at a higher rate.  Right now it's corrupting until it is able to decode the next keyframe
3) If you want to achieve different playback rates, perhaps instead of playing the video you should pause it and scrub through the timeline instead.  This wont' work well with the way your video is currently encoded, but if you re-encode it with a lot more keyframes then this will be possible.
4) Also make sure that you don't have the 'low latency' option enabled in the MediaPlayer component under Platform Specific > Windows section.

Thanks,

**Comment by pravinyadav** [comment]
Thanks for your quick reply.
As per your guidelines I tested it on better graphics card RTX 2080  and it worked.
Thanks a lot for your guidance and support!
