### ISSUE TITLE
DisplayUGUI under a Mask has distored colors on iOS

### ISSUE THREAD

**Issue by Estecka** [RenderHeads/UnityPlugin-AVProVideo#46]
**Describe the bug**
The bug happens only on iOS devices or iOS simulators. This is not reproducible in the editor.

If a DisplayUGUI is a child of a `Mask` component, its colors will be heavily distorded.
(`Rect2DMask` however are safe)

**Your Setup :**
 - Unity version: 2018.3.3f1, 2018.3.9f1, 2018.3.12f1
 - AVPro Video version: 1.9.12
 - Operating system version: iOS 12.2
 - Device model: IphoneXs (both a real one and a simulated one)

**To Reproduce**
- Create a new scene.
- Add a `Mask`, `Image`, and `MediaPlayer` components to the canvas root.
- Add a child to the canvas, attach a `DisplayUGUI` component to the child.
- Assign the media player to the DisplayUGUI.  Set the media player to autoplay.
- Build the scene onto an iOS device or iOS simulator. Run the app.

**Screenshots**
On the left, the DispalyUGUI as it should appear. On the right, the DisplayUGUI under a Mask component.
![Sans titre2](https://user-images.githubusercontent.com/39855800/56047852-9e832700-5d46-11e9-9861-da122605b94e.png)

**Videos**
This is reproduced with the examples videos provided with AvPro.

**Comment by MorrisRH** [comment]
Not sure what is going on there but will investigate. My initial though is that the mask doesn't play nicely with the YpCbCr texture output from the player.
If you uncheck the Use YpCbCr option in the iOS media player settings it should behave correctly.

**Comment by MorrisRH** [comment]
A fix for this will be in the next release

**Comment by midworld** [comment]
Same situation with NGUI textures. What is the problem?

**Comment by MorrisRH** [comment]
We use a YUV biplanar texture format by default on iOS as this uses approx. 50% less memory than the standard 32bit BGRA texture. Trouble is the Unity components don't know what to do with it so you end up with messed up colours.

The solution is to uncheck the YpCbCr420 option in the iOS media player settings which switches the player to using a standard 32bit BGRA texture.

With NGUI being a recent addition we haven't added any code to handle this automatically.

**Comment by samizzo** [comment]
@MorrisRH sorry for resurrecting a closed issue, but I think the real problem is that `DisplayUGUI` is using `material` when it should be using `materialForRendering` instead. If you look at the (bugged) frame in the frame debugger, you can see that the `_YpCbCrTransform` shader var is identity instead of the correct YUV transform. This is because when a mask is in use, the `materialForRendering` is actually a copy of the original `material`. So when `DisplayUGUI.LateUpdate` sets the YUV transform it's actually setting it on the wrong material instance.

I changed `LateUpdate` to use `materialForRendering` when setting the YUV properties in my project and it now works with masks. I haven't debugged further to ensure that this is safe for all other code paths, but looking at the docs it does seem like `materialForRendering` is the right way to go.

Cheers,
Sam

**Comment by AndrewRH** [comment]
Hey Sam, thanks for your effort to report back on this.  Morris is away right now, but we'll look into this in the meantime.

Thanks,

**Comment by MorrisRH** [comment]
A long time coming but this issue is now fixed and will be available in the next release (2.1.6).

**Comment by AndrewRH** [comment]
2.1.6 has been released with this fix - please let us know if you have any further issues
