### ISSUE TITLE
Video won't play in WebGL player

### ISSUE THREAD

**Issue by prisonerjohn** [RenderHeads/UnityPlugin-AVProVideo#473]
**Describe the bug**
Trying to load and play a video on the WebGL player and it's not working. I'm getting an error `Error: video not supported (errorcode=4) color:red;` but I am not sure what that means... The video plays correctly on Windows Standalone and in the Editor.

**Your Setup (please complete the following information):**
 - Unity version: 2020.1.4f1
 - AVPro Video version: 1.10.2
 - Operating system version: Windows 10 Pro 2004
 - Device model: Chrome 85.0.4183.121 or Firefox 80.0.1
 - Video specs (resolution, frame-rate, codec, file size): 1920x1080, 30 fps, H264 / AVC, 16 MB

**To Reproduce**
1. Put the video in `StreamingAssets`
1. Set the path in the `MediaPlayer` at runtime using `MediaPlayer.OpenVideoFromFile(MediaPlayer.FileLocation.RelativeToStreamingAssetsFolder, videoFile, false)`
1. Get the error `Error: video not supported (errorcode=4) color:red;`
1. Cry

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

https://drive.google.com/file/d/1Wrutg9agXPHMllIYszm94FwIlurdWChK/view?usp=sharing

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

THANKS!!!

**Comment by AndrewRH** [comment]
Yes I've seen browsers log that error before, but usually after that log the videos will play.

Have you tried building our demo scenes to WebGL?

On some browsers the video will not actually start to play unless  there is some mouse interaction, and some browsers will not auto-play videos that contain an audio track.

You should also upgrade to the latest version of AVPro Video as your version is quite old and the problem may have been fixed in a later version which has better WebGL support.

Does that help?

Thanks,

**Comment by prisonerjohn** [comment]
Thanks @AndrewRH I just tried your demo scene with my video and it is indeed working. I guess it's something on my end.
