### ISSUE TITLE
More Info on RTSP Support

### ISSUE THREAD

**Issue by jazzy348** [RenderHeads/UnityPlugin-AVProVideo#481]
Hi,

I can't seem to find much info on RTSP support other than "it might work" I know it works over TCP sometimes, but 9/10 AAC audio doesn't decode correctly and I end up with a glitchy mess, see video for example: https://www.youtube.com/watch?v=92MrgCSONGY the stream works fine in VLC. Is there something specific AVPro needs to play AAC over RTSP?

AVPro version: Version 1.11.4
Unity version: 2018.4.20f1

Kind regards,
~Jazzy

**Comment by AndrewRH** [comment]
Which platform are you trying to have RTSP support on - just Windows?

On Windows RTSP is supported but we don't really advertise this fact because it isn't well supported, and many RTSP streams that we have tested didn't work.  We are using Microsoft's RTSP parse which is documented here:
https://docs.microsoft.com/en-us/windows/win32/medfound/supported-protocols

I'm not sure why the audio isn't working.  Do you know what sample rate and codec the audio in the media is using?

Does the audio play back correctly if you just set the audio output to System Direct instead of Unity?

I would also recommend disabling 'low latency' option in Media Foundation settings, see if that helps.

Thanks,

**Comment by jazzy348** [comment]
Hi Andrew,

Thanks for responding. I am using FFMPEG's AAC codec with a sample rate of 48000 (the new default in OBS)

Using System direct doesn't output audio and disabling low latency doesn't help either.

Kind regards,
~Jazzy
