### ISSUE TITLE
AvPro exoplayer Conflict issue in Unity

### ISSUE THREAD

**Issue by AnithaSawood** [RenderHeads/UnityPlugin-AVProVideo#485]
While taking build in unity ,i am getting duplicate class exoplayer issue,we are using different plugins as firebase,facebook and admob

**Your Setup (please complete the following information):**
 - Unity version:  2020.1.7f1
 - AVPro Video version: Version 1.11.5
 - Operating system version: Windows 10 Pro
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

If applicable, add error logs to help explain your problem.
[Exoplayer conflict log.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/5347618/Exoplayer.conflict.log.txt)

**Comment by RenderHeadsSte** [comment]
This is happening because another library/plugin is also using ExoPlayer and there is a version miss-match.  There is something we have addressed in v2, but there is unfortunately no way we can backport it.  You only have three options to address the problem.,,

1) Change your API path on Android from 'ExoPlayer' to 'MediaPlayer' and delete all the ExoPlayer library files in the plugins folder (I can provide a list if required).

2) Remove the usage (and therefore libraries) that are using ExoPlayer - from your log it looks like 'jetified' ?

3) Wait until version 2 of AVPro Video is released and upgrade to use that.  This _should_ be within the next few months and you can implement using the trial beta packages available until then.

Sorry there is no 'magic bullet' solution for this one...other developers are just as much to blame as we are...and at least we have made efforts to fix this going forward :)

**Comment by AnithaSawood** [comment]
Hi, Thanks for your replay.

We have tried the option 1. But the problem is in some phones vedio is not working.

In second option ,We couldn't find out the libraries which are using ExoPlayer.

**Comment by nadheem03** [comment]
Same issue here! @RenderHeadsSte Could you please advise on how can we find those libraries that are using Exo Player!

**Comment by AnithaSawood** [comment]
@RenderHeadsSte Please tell me how can we find those libraries that are using Exo Player!

**Comment by RenderHeadsSte** [comment]
> @RenderHeadsSte Please tell me how can we find those libraries that are using Exo Player!

I am unsure if there is any other way than trial and error...delete a plugin, run, does the log complain about duplicate ExoPlayer libraries.

I am interested in hearing more about what devices will not play which videos when using the MediaPlayer API path.

**Comment by RenderHeadsSte** [comment]
> Same issue here! @RenderHeadsSte Could you please advise on how can we find those libraries that are using Exo Player!

@nadheem03 Sure thing...delete these files and ensure you are only using MediaPlayer components that use the 'MediaPlayer' API path...

From the Plugins/Android/ folder:
- audio360.jar
- audio360-exo28.jar
- exoplayer2.jar
- exoplayer2-dash.jar
- exoplayer2-hls.jar
- exoplayer2-smoothstreaming.jar

From ALL of the achitecture folders (arm64-v8a, armeabi-v7a, x86)
- libAudio360.so
- libAudio360-JNI.so
- libopus.so
- libopusJNI.so

Do let me know if you hit a problem.

**Comment by RenderHeadsSte** [comment]
We shall be closing this issue shortly due to inactivity
