### ISSUE TITLE
after 4-5 seconds when video starts playing

### ISSUE THREAD

**Issue by SevenAntares** [RenderHeads/UnityPlugin-AVProVideo#5]
Hi, I'm building an application on iOS. 
I am streaming a video from my own server(http). 
I want to implement progressive streaming, so that after 4-5 seconds when video starts playing once it plays continuously. The internet is good.

There is some form of fine-grain control over how much of the video buffers before playback?

I will really appreciate the help.

**Comment by MorrisRH** [comment]
Hey!
I'm afraid there isn't much by way of fine grain control available but there are a couple of things you can try.
1. Make sure you pass '-movflags faststart' into ffmpeg.
2. On your MediaPlayer instance call m_Control.SetPlayWithoutBuffering(true). This will start playback as soon as there is enough downloaded. The default behaviour is to download enough such that playback won't stall due to network conditions.

**Comment by AndrewRH** [comment]
I'm closing this ticket, feel free to post another or reopen this ticket.
