### ISSUE TITLE
Crash when URL contains invalid characters

### ISSUE THREAD

**Issue by OldCat9527** [RenderHeads/UnityPlugin-AVProVideo#515]
[Process    .pdf](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/5504466/Process.pdf)

When I use URL mode to play video on IOS，unity just crashed。 I've debugged it many times，The discovery was caused by “ _mediaPlayer.OpenVideoFromFile(_location, _mediaPlayer.m_VideoPath, true)”; What is the reason。

My AVProVideo version is 1.11.5
unity version 2020.1.8

my video url  is    ".m3u8"

**Comment by AndrewRH** [comment]
@OldCat9527 

1) if you play our local sample media - does it work?  
2) If you use this URL does it work? https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

Thanks,

**Comment by OldCat9527** [comment]
1.play our local sample media  is OK。
2.Use the URL you gave me to run。      
Why is that?

The URL I used is：http://wh.zdzxtech.com:9071/upload/zdzxpt-hnpy\mp4\201912\4\1f188157d1124fed99bbf9b6b1414ba0/1f188157d1124fed99bbf9b6b1414ba0/1f188157d1124fed99bbf9b6b1414ba0.m3u8

Hope to get your answer
Thanks

**Comment by MorrisRH** [comment]
Thanks for providing the URL that fails. We have reproduced the issue and a fix will be provided in the next release.
The problem is that your URL contains back-slash characters ('\') which are not valid and prevent the URL from being parsed correctly. You can either replace them with forward-slash character ('/') or use percent escapes to encode them (%5C).

**Comment by OldCat9527** [comment]
Thank you for your help,   My video is ready to play。
