### ISSUE TITLE
Windows7- Video without Fast Start encoding takes a long time to begin and blocks the app

### ISSUE THREAD

**Issue by nhasson76** [RenderHeads/UnityPlugin-AVProVideo#517]
**Describe the bug**

On Windows7, when playing a video from HTTPS URL, the call for OpenVideoFromFile causes the app to stall for approximately 20-60 seconds. The exact point I was able to trace is at WindowsMediaPlayer.cs at the Native.OpenSource call.
It happens only the first time accessing the given URL.
In my case, we're generating pre-signed URLs from Amazon S3 so it happens every time.
It looks like some sort of caching that happens in the first time and stalls the entire Unity Editor / Released Product.

Device (which devices are you having the issue with - model, OS version number):

Windows7

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

1 Video, 640x480, mp4, 24 FPS, https://spivi-cdn.s3.amazonaws.com/vod/1632/1444579/audio_video_640x480_2020-11-06_09-30-46_AHF3U.mp4

System Information:

AVPro Video: plugin v1.11.5 scripts v1.11.5
Target Platform: Standalone
Unity: v2019.4.13f1 WindowsEditor
OS: Desktop - MS-7817 (MSI) - Windows 7  (6.1.0) 64bit - Hebrew
CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz - 8 threads - 16312KB
GPU: NVIDIA GeForce GTX 1050 Ti - NVIDIA - Direct3D 11.0 [level 11.0] - 3998KB - 16384

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.13f1
 - AVPro Video version: 1.11.5
 - Operating system version: Windows7
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Create a new project on Windows7
2. Add the FullscreenVideo prefab and set its URL to a new URL of media that hasn't been opened on the device and disable auto open.
3. Go to play mode.
4. Press the load button to open the URL.
5. The editor will freeze for 20-60 seconds.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi,
Thanks for the detailed report!
I replicated the issue you're having, and actually it seems to be waiting to download the entire video before playback starts.  I think this is because the video hasn't been encoded for 'fast start'.  

Our Windows 7 (DirectShow) player isn't asynchronous, so the main thread is blocked when calls are made and it needs to download the entire video as the metadata is located at the end of the file.

This isn't an issue on Windows 8 and above as it uses the Media Foundation API which is synchronous, and it also better handles videos without 'fast start'.

The best way to solve this is to encode your video with 'fast start' to make it suitable for streaming.

I hope this helps you,

**Comment by nhasson76** [comment]
Hi Andrew,

Thanks for your prompt response!
I can confirm the adding the Fast Start resolved this issue.

**Comment by AndrewRH** [comment]
Great news! I'll close this issue then.
Cheers,
