### ISSUE TITLE
On iOS the video player is playing videos all in red color

### ISSUE THREAD

**Issue by sanaullah48** [RenderHeads/UnityPlugin-AVProVideo#536]
I have been using AVpro since 29 Nov 2020. Was done with testing on Android and it were working absolutely fine. Now when I build it for iOS, I saw that all of my videos suddenly turned into RED color

**Comment by AndrewRH** [comment]
One way to fix this is to got o Platform Specific > iOS and change the pixel format mode from YCbCr to RGBA.

This will have a slight extra memory overhead, but it will solve your problem.

The reason this happens is because it seems like you may not be using our shaders/components.  Ideally if you use our components like DisplayUGUI, ApplyToMesh etc, and you use our AVPro shaders then it will handle the conversion for you.

I hope that makes sense.  Does that help?

Thanks,
