### ISSUE TITLE
Transparency with Webm

### ISSUE THREAD

**Issue by yMiecie** [RenderHeads/UnityPlugin-AVProVideo#541]
**Is your feature request related to a problem? Please describe.**
AVPro does a great job playing webm videos but it seems to ignore the alpha channel. I would like to play webm video with transparency as is possible with Unity Video Player

**Describe the solution you'd like**
Support the alpha channel in webm video like it does with HAP-A.

**Describe alternatives you've considered**
I can use Unity video player but it's not as smooth as AVpro.

It would be great to hear from you, if this is possible.
Thanks!

**Comment by AndrewRH** [comment]
Thanks for the suggestion.  We would love to support transparency in webm, but unfortunately none of the OS decoders support it.  We would have to write a custom decoder, and i'm not even sure it would be able to decode on the GPU.
We have some alternative methods in the documentation (such as packing) which could by used with codecs like H.264 and HEVC.
I'll keep this feature request open but I'm afraid it's very low down the priority list for us.
Thanks,

**Comment by cyliax** [comment]
Hi, we started to use your great plugin as a replacement to Unity internal videoplayer. Now we are at the some point. We used webm videos with alpha channel to get better resolutions with less file size than using a side by side (packed) alpha channel. Unfortunately your plugin isn't supporting it, right? Or are there any news since 2.0? Is there a chance to integrate a fallback to software decoding when the mediasource is a webm transparency file? It would be a shame if this missing feature prevented us from using your otherwise extremely helpful plugin.

**Comment by oxidizer05** [comment]
Yes it would be very useful

**Comment by shealan** [comment]
Really sad to discover this feature doesn't exist. Any update now there's been a few years of development since the last post?

**Comment by krisrok** [comment]
*sad webm noises*

**Comment by MorrisRH** [comment]
Closing this issue as until there is support at a native platform level we will not be able to provide this.
