### ISSUE TITLE
Crash or no playback when using Nvidia's VRSS (Variable Rate Super Sampling) VR option

### ISSUE THREAD

**Issue by nosjo** [RenderHeads/UnityPlugin-AVProVideo#563]
**Is your feature request related to a problem? Please describe.**
Alot of video play back issues/crashes with "virtual reality - variable rate super sampling" turned on in nvidia driver since avpro cant get the resolution properly

**Describe the solution you'd like**
A fix that can detect vrss and do stuff properly instead of not playing video or crashing

**Describe alternatives you've considered**
Fix the crashing and have some information that it couldent play back since vrss is on

**Comment by AndrewRH** [comment]
I believe this may be more an issue with this feature than our plugin...  We will investigate though.  We're simply playing videos, and I'm not sure how Nvidia are changing the rendering internally.  It sounds like it might be running out of memory because it's allocation too many resources - even trying to do VRSS on the video textures.  I'm not sure there will be a way to stop it doing this, but we will investigate.

Thanks,
