### ISSUE TITLE
Unity WebGL support  with New Version

### ISSUE THREAD

**Issue by anindya1234** [RenderHeads/UnityPlugin-AVProVideo#601]
We produce AI-based Saas training teaching presentations skills worldwide. https://pitchvantage.com/ We have been a loyal user of AVPro video for video playback for Unity WebGL for our training software on Chrome and Firefox. We use it in video playback for user videos in Unity.

However, we upgraded to V2.0 and we see you have no support for WebGL. 
This is a big setback to us and makes us very cautious about using your product in future. We just purchased V2.0 as 1.0 is deprecated and saw this. We decided to keep using V1.0 for now though we see it has issues with Firefox 85. Video playback on Windows/Firefox is jittery and Mac/firefox has a Bright Tint on the video.None of this happened in 5 years of using your product.
Do you have any plans of supporting Unity WebGL for Chrome and Firefox , seems that is the basic requirement for us. I understand safari and edge are tough to support but chrome/firefox you guys did pretty well , not sure why you decided to scrap it. So many games use WebGL. If you do not have plans for supporting, please let us know so we can plan accordingly.
Appreciate your support and consideration!

**Comment by RenderHeadsSte** [comment]
Thanks for your support of the asset.  We completely hear what you are saying re WebGL support.  As I am sure you are aware, we still include the WebGL platform in version 2 and have not dropped it completely.  The reason is was officially dropped is because, as you point out, support is almost entirely based on each browser on each operating system.  We have no control over changes to browser implementations and so offering official/binding support was proving impossible in a lot of cases.  That said, we are considering investing some more time in the platform and opening up official support for Firefox and Chrome in version 2 of the asset.

Version 2 performance of WebGL should be at least on a par with version 1.11.7, and should obviously benefit form the universal feature set improvements that version 2 has over version 1.x.  If you are seeing that version 2 WebGL is not the same as that found in v1.x then we would certainly like to look at why that is, and hopefully offer improvements to bring it back up to spec.  So if you have compared like-for-like v1.x to v2 then we would appreciate opening a github issue with all the usual requested details.

**Comment by PVanandgupta** [comment]
Hi reopening this issue and we have updated to the latest version of avpro video and now the fixes we had added to resolve the jitter issue on videos for firefox mac have started happening again.

the process we use for recording our video - 
1. record the video using webrtc, please check the 1.mp4 file for the recorded video. This video plays fine with avpro in firefox 91.0.1without any jitter
2. now we encode the video using ffmpeg to use libx264 codec and aac for audio, the command used to encode is  - ffmpeg -i videoFilePath -r 24 -vf scale=320:240 -c:v libx264 -c:a aac -strict -2 encodedVideoFilePath.  You can check the file 2.mp4 for the encoded video.
3. The video after encoding plays with jitter on firefox 91.0.1 using avpro, if played normally using the browser the video plays fine. Also if I disable hardware acceleration on the browser the video plays fine. 

Our video playback solution depends on avpro currently and not being able to play the video on firefox is a major issue we are facing right now. Please let me know if any further information is required regarding the same.

1. https://user-images.githubusercontent.com/51085407/130187242-f2edd5e8-fc0d-4092-a9bb-773076a47082.mp4

2. https://user-images.githubusercontent.com/51085407/130187280-137eb316-03dc-4ef0-a282-c3ef6759e52a.mp4
