### ISSUE TITLE
Problem with exoplayer bridge in Unity. Stuttering on high resolutions...

### ISSUE THREAD

**Issue by Yarrrrrrr** [RenderHeads/UnityPlugin-AVProVideo#633]
Hey guys! 
**We have an interesting stuff to investigate.** 
The problem is with exoplayer bridge in Unity. The problem is that on Oculus Quest 2 it looses frames on 8K resolution videos 60 fps. It looks like stuttering on high resolutions/fps.
We have checked it on AVPro version 1.11.7 and 2.0.6. Also we have checked it on our own Exoplayer bridge. (They use exoplayer 2.12.1 and 2.8.4). Result is the same, for some reason exoplayer updates the texture with the different delay. 
We have tried AVPro in Unity 2018.4, 2019.4 and latest 2020 version. The behavior is the same, it's skipping frames. For some reason internal Unity Video player (starting from version 2019) is not skipping frames, but it's to slow for our purposes. Also Skybox VR player for Oculus Quest is not stuttering as well, but they use their own fork of exoplayer.
We have prepared the demonstration video with blinking dots. You can use it to check it on your side.
Also we've attached apk file for Oculus Quest with AVPro demonstration scene playing in video. You can check how it stutters. Just look to left and right after start. Video is mapped to the standard AVPro 360 mesh. When AVPro will skip the frame you won't see the corresponding dot.
At the same time CPU and GPU of Oculus Quest 2 is not overloaded at all so the bottleneck is somewhere else.
**If you have any ideas why it could happen, please share your thoughts! 
Thanks in advance!**

Video:
https://www.dropbox.com/s/a799kpispvyoyz3/vrtest_grid3x2_60fps_8k_hevc_180_180x180_3dh_LR.mp4?dl=0
APK for Quest/Quest2:
https://www.dropbox.com/s/78bn21k43hhu2oi/testavpro.apk?dl=0

**Comment by RenderHeadsSte** [comment]
I went on a debugging session in our Android plugin and back tracked right back to where the frames are delivered from the Android API - how often SurfaceTexture fires back 'void onFrameAvailable(SurfaceTexture surfaceTexture)'.  Logging here shows that the Quest 2 struggles a bit.  Time deltas between frames is sporadic, ranging from every 9ms to every 40ms on occasion.  I averaged the arrival of frames deltas expecting to see ~16.6ms over time.  I do not.  I see ~19.1ms, so akin to a 52Hz video, not 60Hz as we know the source is.  So I fed in a lower resolution 30Hz video, and the average was a near perfect 33.3ms delta time.  I then tried a different Android device - a Xiaomi Mi 10T.  On this I see 16.6ms average time delta AND perfect visual playback.

This all lead me to believe that the issue is down to the Quest 2 struggling to decode and deliver frames.  Scratching my head, I remembered that Oculus devices tend to be throttled in terms of both CPU and GPU, and also the Quest 2 screen runs at 90Hz.  I cranked up the CPU and GPU to max and this indeed helped, now getting an average frame delivery time delta of 17.1ms.  I did no get chance to try changing the refresh to 60Hz so do not know if this would help.

The bottom line is that the Quest 2 struggles to deliver 60Hz 8k content in a Unity environment.  I am not sure why this is because the CPU and GPU were not even close to being fully loaded, so the bottleneck has to lie somewhere else in the pipeline.

I have also ran the same test in the ExoPlayer demo (the GL demo) on the Quest 2.  Performance was slightly better in terms of average delta time for frames received back from the decoder, but there was still visible missing 'dots' on the video playback.

I guess there are more questions here than an outright bug...

Why are frames delivered so sporadically when the CPU/GPU both have headroom, memory bandwidth on the Quest 2 maybe?

Are frames being dropped prior to delivery to onFrameAvailabe(...) ?  If so, are all frames being sent to the decoder, and then the decoder dropping them?  Or is is it the mechanism that feeds the decoder?

**Comment by RenderHeadsSte** [comment]
I also see that you reported this issue to ExoPlayer directly ([here](https://github.com/google/ExoPlayer/issues/8605)).  I have tried all their suggestions, and none of them have made a difference.

Another thing I have tested, is triggering the 'Render' callback thread to fire the Render call in our plugin.  This essentially checks to see if a new frame has been reported as available by the Android subsystem (onFrameAvailable) and processes it accordinlgy.  I monitored how quickly The plugin Render( function was being called and get the results or 'sub milliseconds over and over, then 10/11 milliseconds followed by a frame being delivered, then back to sub milliseconds again'.  This change still showed missing frames visually. 

One thing to maybe try, change your video to be 'top/bottom' rather than 'left/right'...as decoders tend to do better with shorter widths.
