### ISSUE TITLE
403 URL error in Unity 2020.1.17f1

### ISSUE THREAD

**Issue by danmapes** [RenderHeads/UnityPlugin-AVProVideo#638]
Create new 3D project in 2020.1.17f1, import package, kill vulcan, set Internet access require. Open Demo_mediaPlayer scene. Change to Abolute path or URL. Set to https://mixeduprealities.com/videos/FlitTeaser.mp4. Build and run to Galaxy S7. Unity crashes.
Change from Exo to Media player... no crash but 403 error in adb logcat.
File plays, no problems, from streaming assets.
File also plays from Chrome.
Website has valid SSL certificate installed and all read permissions. 
Tried the network_security_config.xml trick, no joy. 

Repeat with 2019.4.17f1. Works with both Exo and Media player. No problem.
I'm good with 2019 for now, but posting this issue for the community.

**Comment by RenderHeadsSte** [comment]
This is due to Unity adopting very aggressive optimisations of plugins and their dependency libs in 2020.

You need to apply the fix found [here](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#unity-20202-and-above).  Looks like it applies to the later releases of 2020.1 as well as 2020.2.x.  We will adjust the documentation to reflect this.

Thanks for the spot and highlighting the issue :)
