### ISSUE TITLE
SRT file not displaying subtitles 

### ISSUE THREAD

**Issue by kahnivore** [RenderHeads/UnityPlugin-AVProVideo#648]
**Describe the bug**
From a file sent in on keeping. Subtitles don't display. But if the exact same file is recreated it does. Investigate to see if this is a bug in SRT parser

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.3
 - AVPro Video version: Core 2.0.6
 - Operating system version: Windows 10

[Vorstellung.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6051037/Vorstellung.zip)

**Comment by IARI** [comment]
I have been able to show subtitles with the file you sent me.
One difference i noticed:
- The file I had sent contains unix file-endings (\n)
- The recreated file you sent back has Windows-style line-endings (\r\n) and one additional empty line at the end.
Possibly that is the source of the problem.

**Comment by AndrewRH** [comment]
This seems to be because the SRT file isn't correctly formatted.  It uses "–->" instead of "-->" so the parser ignores those entries.

**Comment by AndrewRH** [comment]
I believe this issue can be closed now - does this solve your issue @IARI?

Thanks,

**Comment by IARI** [comment]
@AndrewRH thanks.
Yes, since I was indeed able to display subtitles with the other file.
I have not yet been able to double-check the issue with the incorrect character as you pointed out, but this sounds like that would be the explanation, and apologies for the inconvenience of this issue.
I guess i copy-pastes seemingly corect srt content, but somehwere on the way the symbols must have gotten messed up - however since they didnt look incorrect.

I would propose that you introduce some basic kind of exception-handling around the srt parser, such that the unity-editor logs some error, when the srt-parsing fails.

**Comment by AndrewRH** [comment]
Thanks, we have added an exception now which will be included in the next release.

I will close this issue now, but do let us know if there are any other issues.

Thanks,
