### ISSUE TITLE
WebGL iOS error : Expression too complex

### ISSUE THREAD

**Issue by aidanikuz02** [RenderHeads/UnityPlugin-AVProVideo#654]
Hello. I built the Demo_MediaPlayer for WebGL with video URL and seems to work well on my Samsung S10, Android 11, Google Chrome browser but when trying it on iPhone 8 plus, safari i get : "WebGL: ERROR: Expression too complex" and my video doesn't load. What does this error mean? im using the 2.0.7 trial package in Windows with Unity 2020.1.

**Comment by MorrisRH** [comment]
We're investigating the WebGL error, it seems to be related to WebGL 1.0 and not specifically to iOS. Unfortunately it is not the reason for the video failing to play.

We do not support WebGL on mobile at this time as currently Unity also do not support it, see [here](https://docs.unity3d.com/2021.1/Documentation/Manual/webgl-gettingstarted.html). We are also unable to support WebGL on Safari due to Apple's requirements for media playback in the browser. For more information on what we support with regards to WebGL please refer to our documentation [here](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-webgl.html).

**Comment by AndrewRH** [comment]
The "Expression too complex" is due to a shader in the MediaPlayerUI demo scene.  I've attached a fixed version here that will be included in the next release.  Just copy this file into the /AVProVideo/Demos/Common/MediaPlayerUI folder.

[MediaPlayerUI.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6064091/MediaPlayerUI.zip)

Thanks,

**Comment by aidanikuz02** [comment]
> The "Expression too complex" is due to a shader in the MediaPlayerUI demo scene. I've attached a fixed version here that will be included in the next release. Just copy this file into the /AVProVideo/Demos/Common/MediaPlayerUI folder.
> 
> [MediaPlayerUI.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6064091/MediaPlayerUI.zip)
> 
> Thanks,

Great, thanks! Will try it out now.

**Comment by aidanikuz02** [comment]
I replaced the original MediaPlayer UI with this new one but it looks like this now. 
![16146512476124667993645266825627](https://user-images.githubusercontent.com/60679616/109586377-0fe94000-7b40-11eb-881e-6b634908b57d.jpg)

**Comment by kahnivore** [comment]
Hi @aidanikuz02 

Have you tried this on another browser on your iPhone (i.e. one that isn't Safari)?

**Comment by MorrisRH** [comment]
Video playback won't work. We don't support WebGL on iOS at this time.

**Comment by AndrewRH** [comment]
I'm closing this issue as the shader error has been fixed in 2.0.9, and webGL isn't not currently supported by this plugin on iOS
