### ISSUE TITLE
Seeks done while deactivated never trigger StartedSeeking / FinishedSeeking events

### ISSUE THREAD

**Issue by TheloTheGreat** [RenderHeads/UnityPlugin-AVProVideo#683]
On AVPro 2.0.9, on both Windows and Mac, calling MediaPlayer.Control.Seek() while the gameObject is deactivated does a seek operation, but it never triggers StartedSeeking / FinishedSeeking events for that seek. (Seeks done while the gameObject is activated trigger the events as expected.)

To reproduce, on Demo_MediaPlayer, add this to MediaPlayerUI.Update:

```
if (Input.GetKeyDown(KeyCode.A)) {
	_mediaPlayer.gameObject.SetActive(false);
}
if (Input.GetKeyDown(KeyCode.S)) {
	_mediaPlayer.Control.Seek(1);
}
if (Input.GetKeyDown(KeyCode.D)) {
	_mediaPlayer.gameObject.SetActive(true);
}
```

Add this to Start():

```
if (_mediaPlayer) _mediaPlayer.Events.AddListener(OnMediaPlayerEvent);
```

Add this new method:

```
public void OnMediaPlayerEvent(MediaPlayer mp, MediaPlayerEvent.EventType type, ErrorCode errorCode) {
	Debug.Log("OnMediaPlayerEvent: " + type);
}
```

Then launch the demo scene. While the video is playing, press A, then S, then D.

Expected result: The StartedSeeking and FinishedSeeking trigger somewhere in that sequence.
Actual result: The StartedSeeking and FinishedSeeking do not trigger.

**Comment by AndrewRH** [comment]
Hi,

So basically this is the expected behaviour.  The component has undefined behaviour if you use it while it is deactivated.  When it is deactivated the logic is no longer running, so it cannot produce events.  In this case I suspect the seek is happening at the low-level but by the time the object is reactivated the seek has both started and completed so the C# event logic will have no idea of this.

We would consider this type of usage an edge case as the component is not designed to be used while deactivated.  I can however see reasons why this would be desirable.

A workaround may be:
1) Make sure your MediaPlayer component are never within a hierarchy that will be disabled, instead keep them in a global pool elsewhere.
2) Make sure that your MediaPlayer components have had all their command sent to them before they are disabled

This is something we may consider looking at in the future though, so I've added a new issue here for this:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/696

Feel free to add to that thread if you have any further thoughts.

Thanks,
