### ISSUE TITLE
Changing Time.TimeScale not having an effect on video playback 

### ISSUE THREAD

**Issue by lvchy** [RenderHeads/UnityPlugin-AVProVideo#691]
![image](https://user-images.githubusercontent.com/24428364/112088561-05fcaf00-8bcb-11eb-8dcb-dcaad9c76b71.png)

Nice ?

**Comment by lvchy** [comment]
In my version ,the Global setting :  TimeScale has no effect . every unity renderer or animation has been effected . but the avpro video  seems no speed up or down . So i open my assetstore to check if any update has fixed this issue . but no update ,only a retired and repay for me ..

**Comment by kahnivore** [comment]
Hi @lvchy 

There is no need to buy version 2.x if you don't require features specific to 2.x. AVPro Video 1.x still works and we are still supporting it, just not adding any new features. We needed to make breaking API changes in order to add a whole host of new features, which is why we created version 2.x, and it was simply untenable to keep updating two separate code bases. We do also offer generous discounts to all owners of 1.x who want to buy our new product. Please see discounted upgrade paths [here](https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#owners-of-avpro-video-1x). 

In terms of your TimeScale issue, could you please let us know more information so we can help. You need to both enable TimeScale support (by checking the box in your MediaPlayer compopent's Global Settings) to be able to use this in conjunction with Time.timeScale or Time.captureFramerate. If you have done both these things, could you please supply more detail about your problem, or send us a reproducible case to unitysupport@renderheads.com. 

Thanks.

**Comment by lvchy** [comment]
I have already open the global setting  to enable timeScale :
![image](https://user-images.githubusercontent.com/24428364/112118164-0ca11b80-8bf7-11eb-9cd5-afaf38ef9622.png)
But when I change the unity code
![image](https://user-images.githubusercontent.com/24428364/112118414-4ffb8a00-8bf7-11eb-9bc4-3aa97ce461e9.png)
All Unity Shows speed up or down correctlly, only the avpro video seems no change .
Thanks.

**Comment by kahnivore** [comment]
Hi @lvchy 

I see you've set your build target to Android. This would make sense why you're not seeing any effect showing in the editor.

If you build to your target platform you should see the effect taking place in the build. 

Alternatively, if you want to test it in the editor, you'll need to switch your build target to Windows/Mac (whichever platform you're using) and then re-check the TimeScale Support box in the inspector.

Can you confirm this works?

Thanks

**Comment by lvchy** [comment]
@kahnivore  It worked on editor ,thanks a lot ~
I will test on mobile in the future.

**Comment by lvchy** [comment]
Some times it play success ,sometimes the video freezing when play ......

**Comment by kahnivore** [comment]
Hi @lvchy 

Is the freezing related to the time scaling? Can you provide a bit more information about the behaviour? 

Thanks

**Comment by kahnivore** [comment]
It would also be good to test this using one of our demo videos, so we know if it's an issue specific to the video you're using or not.

**Comment by lvchy** [comment]
Hi, @kahnivore  ,Thanks for reply .

The freezing is happen every time when i change Unity's Time.TimeScale to 1.5 or more . and on the video no loop .
Can you send me your email address ,i think i can give your a test demo with my project unity source code and .mp4 files .

**Comment by kahnivore** [comment]
Sure, you can send your test project to unitysupport@renderheads.com.

Thanks.

**Comment by kahnivore** [comment]
Didn't get an email from you @lvchy?

**Comment by RenderHeadsSte** [comment]
Closing issue due to lack of response.
