### ISSUE TITLE
I wondering to know about Multi-site license.

### ISSUE THREAD

**Issue by fakeeyes** [RenderHeads/UnityPlugin-AVProVideo#708]
I already purchase of AVPro Video 1.x and AVPro Video 1.x (Windows)

But it was deprecated.

How can I get new version of AVPro video?

Oh I saw your latest read me file.

So I understand your business policy.

But I wondering to know, What is the license policy about MULTI-SITE for enterprise?

Please let me know -> kimsjar@fakeeyes.co.kr

Best regard
Mason KIM

**Comment by kahnivore** [comment]
Hi there, 

Our Enterprise license is a custom EULA aimed at multiple seats over multiple sites.  We are delivering the Enterprise edition away from the Unity store currently because the Unity EULA only covers one seat.  The aim is to eventually have it on the Unity store.  So in short, if you want a multi-seat, multi-site license that completely covers you from a legal aspect, the Enterprise edition is the only version to offer this.  Additionally, as part of the Enterprise license, you also receive priority support for the product. 

If you would like to enquire further about this feel free to mail us at unitysupport@renderheads.com.

Thanks.
