### ISSUE TITLE
Streaming playback sometimes stops on iOS.

### ISSUE THREAD

**Issue by MB-k-ishida** [RenderHeads/UnityPlugin-AVProVideo#740]
Hello.
I'm trying UnityPlugin-AVProVideo-v2.0.11-Trial.unitypackage.

But, streaming playback sometimes stops on iOS.
After stopping, wait for about 1 minute or call Play () to resume.
This is a phenomenon that occurs only on iOS. Is there any countermeasure?

**Comment by MorrisRH** [comment]
Sounds like your network conditions aren't great and the video stalled. By default the player will try and buffer as much as possible to minimise future stalls. The Stalled and Buffering event types should be triggered which you can listen to in order to figure out when playback can be resumed.

If you can provide a bit more information we may be able to investigate further:
- Unity version
- iPhone or iPad device type
- iOS version
- URL of the movie you're trying to playback (please send this to unitysupport@renderheads.com mentioning this issue if you want to keep it private)
- information about the movie you're trying to playback (dimensions, codecs, bitrates, etc.)

**Comment by MB-k-ishida** [comment]
Thank you for your reply.
I emailed more information to unitysupport@renderheads.com.

**Comment by MorrisRH** [comment]
Thanks for sending though the link. Unfortunately I've yet to reproduce the issue. Playback has stalled on a number of occasions and has recovered without requiring any intervention on my part.

**Comment by MB-k-ishida** [comment]
Is the operation of repeating playback stop and recovery within the normal range?
Even if it's a long span.

**Comment by MorrisRH** [comment]
Assuming the connection to the server hasn't been dropped, the player should always be able to recover from a stall once enough data has been buffered.
