### ISSUE TITLE
Live stream time offset too high HLS

### ISSUE THREAD

**Issue by MB-k-ishida** [RenderHeads/UnityPlugin-AVProVideo#741]
Hi everyone,

Now I'm in trouble because of playing "UnityPlugin-AVProVideo-v2.0.11-Trial" in live causes a huge delay.
All formats are HLS and here is the list of delay times by platform.
・Windows: 46s
・Mac: 50s to 1m30s
・iOS: 26s
・Android: 27s

Especially the delay of Windows and Mac is large, I would like to reduce it to at least iOS and Android level.
Does anyone know a solution?

**Comment by MorrisRH** [comment]
Those delays are quite large. If you can provide a bit more information we may be able to investigate further:
- Unity version
- iPhone or iPad device type
- iOS version
- URL of the movie you're trying to playback (please send this to unitysupport@renderheads.com mentioning this issue if you want to keep it private)
- information about the movie you're trying to playback (dimensions, codecs, bitrates, etc.)

**Comment by MB-k-ishida** [comment]
Thank you for your reply.
I emailed more information to unitysupport@renderheads.com.

**Comment by MorrisRH** [comment]
Thanks for sending through the video link. Unfortunately I'm unable to reproduce the issue. On macOS and iOS the delay between opening the stream and playback beginning was about 4 seconds here. This suggests the issue is with your internet connection, if you're using a cellular connection then these are typically a lot slower than WiFi. It's also worth checking that you're not routing through a VPN or that some kind of network link conditioner is active.

**Comment by RenderHeadsSte** [comment]
Additionally attempted reproduction information. Testing on Android and Windows (Editor - MediaFoundation) I am seeing start-up delays of approximately 6 seconds on both platforms.

**Comment by RenderHeadsSte** [comment]
Maybe you could test your stream on one of the many online HLS players to rule 

[https://bitmovin.com/demos/stream-test](https://bitmovin.com/demos/stream-test)
[https://www.theoplayer.com/ll-hls-test-page](https://www.theoplayer.com/ll-hls-test-page)
[https://flowplayer.com/developers/tools/stream-tester](https://flowplayer.com/developers/tools/stream-tester)

It's possible that the delay you're experiencing is due to DNS issues, which falls outside the scope of our plugin.

**Comment by MB-k-ishida** [comment]
Thank you for your reply.
Our problem is the latency between sending and displaying the video. The video used for the test shows the clock, so please compare the difference with the current time.

---
>https://bitmovin.com/demos/stream-test
HLS could not be played.
It was able to play DASH, but it was delayed by 59s.

**Comment by MB-k-ishida** [comment]
![image](https://user-images.githubusercontent.com/18710886/115833939-9854d480-a44f-11eb-923f-16f9c25ce061.png)
For reference, I'll paste a screenshot of Azure and client time.

**Comment by MB-k-ishida** [comment]
![image](https://user-images.githubusercontent.com/18710886/115845965-6433e080-a45c-11eb-9c48-7fdc37c51dda.png)
When I play the same URL in Unity and Azure Media Player, Unity is delayed by 24 seconds.
Isn't it possible to delay this much?
https://ampdemo.azureedge.net/?url=https%3A%2F%2Fendpoint5-deltadevmediasrv-jpea.streaming.media.azure.net%2Fe2db91fa-14b6-4cb2-8845-1a25b1d0f2a1%2F738a05ee-ca74-4f6a-a3f7-1b598e882db9.ism%2Fmanifest(format%3Dm3u8-aapl)

**Comment by RenderHeadsSte** [comment]
I am not sure I understand the issue here.

When I open the link you last sent it shows the time as 11:32:15.  If I leave it a while (10+ minutes) and hit refresh in my browser, I get it starting at the same time.  I get the same behaviour playing back the video URL in Windows Editor and on Android...if I run, I get the time shown as 11:32:15, leave it a while, re-run...the time is the same - 11:32:15.

**Comment by MB-k-ishida** [comment]
The gap of latency difference between clients when playing LIVE is quite large.
Especially Windows' AVPro has a large delay.

The test result of latency with AVPro is...
Windows　46sec
iOS　　　26sec
Android　27sec

As reference, Azure Media player had 22 seconds latency.

Are there any way to reduce the Windows' delay to around 20 seconds?

Please try to livestream on any platform to compare the latency by using other tools and your Unity asset.

**Comment by MorrisRH** [comment]
I'm afraid that we're just not seeing the issue here. Starting the streams simultaneously on iOS, macOS (unity editor) and with the azure player they are all within a second of each other, as shown here:
![Screenshot 2021-04-30 at 11 02 27](https://user-images.githubusercontent.com/46530460/116680562-b9637b00-a9a3-11eb-9ba2-3270f92aae90.png)

I think part of the problem might be that the stream is no longer 'Live' and is now being treated as a VOD so the player no longer has the requirement to try and play the latest segment (it starts from the beginning each time). For instance, if I start the iOS player 4 minutes after the azure player, there will be 4 minutes difference in the clocks.

**Comment by RenderHeadsSte** [comment]
For completeness.  Here is a picture showing Android and Windows (Editor) that were both run at the same time...

![Image from iOS (8)](https://user-images.githubusercontent.com/46531149/116683791-ff224280-a9a7-11eb-9e2c-535808f31401.jpg)

**Comment by MB-k-ishida** [comment]
Videos with screenshots are on-demand, not live. The date displayed there is a thing of the past.
Please try it live.

**Comment by MorrisRH** [comment]
Could you provide the URL for the live version please, either here or to unitysupport@renderheads.com.

**Comment by MB-k-ishida** [comment]
I sent the URL by e-mail.

**Comment by AndrewRH** [comment]
Thanks, I tested Windows and I saw the same latency that you reported 👍 
There might be a way to improve Windows latency.  Could you please re-enable the stream tomorrow so we can test it?

Thanks,

**Comment by MB-k-ishida** [comment]
OK. We will send you a new URL by email.
Thank you.

**Comment by MB-k-ishida** [comment]
How is the response status of this case?
Please let us know if you need more streaming.

**Comment by AndrewRH** [comment]
We did some tests, and the best we could achieve was 35 seconds on Windows.  To do this we had to:

1) Switch to the WinRT API
2) Make a modification to the plugin
3) Seek to the end of the stream time.  The seeking had to be done just as the new segments were downloaded, otherwise the delay would be 45 seconds, as Windows API seems to only give us new segments every 10 seconds.  Some C# code could be written to handle this part.

Let me know whether switching to WinRT and doing the above is suitable for you, with 35 seconds of delay.  Then we can make those modifications.

You could also try having smaller manifests - currently your manifests are around 200-400KB each for video and audio, and those have to be constantly downloaded, so perhaps having less archive time would help the overall delay.

Thanks,

**Comment by MB-k-ishida** [comment]
Thank you for your answers.
Besides the Windows, are there any ways to shorten the delay for Mac?
It still has 50s to 1m30s delay.

**Comment by MB-k-ishida** [comment]
Hi Andrew, 
Forgot to mention that the windows latency with 35 seconds works for us so please do as you suggested.
Will be waiting for your answer regarding the Mac latency.
Thanks

**Comment by AndrewRH** [comment]
@MB-k-ishida  could you please run the stream again today, in case  we need to test again on macOS.

I will look at adding the updated Windows build to the next release of the plugin.

Did you try running the URL in QuickTime to check the latency?   We only see around 24 seconds of latency on our test with macOS (same on QuickTime)...

Thanks,

@MorrisRH any idea why they are seeing 50 - 100 seconds of latency on macOS?

**Comment by AndrewRH** [comment]
@MB-k-ishida 

Please could you also try adding this method to MediaPlayer.cs

`		void SeekToLiveTime(double offset = 0.0)
		{
			if (_controlInterface != null)
			{
				double liveTime = _controlInterface.GetBufferedTimes().MaxTime;
				if (liveTime > 0.0)
				{
					_controlInterface.Seek(liveTime - offset);
				}
			}
		}
`

You can call it to seek to the live position which could reduce some latency if the playhead has lost the live position due to buffering.  Does that help?

Please also could you run the stream again today, in case we need to test again on macOS.
Thanks,

**Comment by MorrisRH** [comment]
I'm seeing ~30 seconds of latency on macOS and AVPro Video is consistent with the QuickTime player, so from a software perspective there is nothing I can do to improve this.

**Comment by AndrewRH** [comment]
@MB-k-ishida  the live stream you just shared with us seems to have stopped....

**Comment by AndrewRH** [comment]
@MB-k-ishida we've just released 2.1.3 - it has a new option for WinRt to allow for lower live stream latency:
![image](https://user-images.githubusercontent.com/5418126/118279528-28bc8d00-b4c3-11eb-9ade-a3318d06d237.png)

There is also a new method on MediaPlayer component that you can call once streaming as started to move the position as close to the live time as possible:  **SeekToLiveTime()**

I've seen some small improvement with this, but not a lot.

As previously mentioned, you may also see some improvments if you manage to reduce the size of your manifest files.

Let me know if this helps.

Thanks,

**Comment by RenderHeadsSte** [comment]
We will be closing this issue soon due to lack of response (@MB-k-ishida)
