### ISSUE TITLE
Control.GetCurrentTimeMs() + WebGL video is choppy

### ISSUE THREAD

**Issue by coin-jinmeng** [RenderHeads/UnityPlugin-AVProVideo#748]
**Describe the bug**

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.20.f1
 - AVPro Video version:  1.11.7 
 - Operating system version: window 10 home 64bit
 - Device model: chrome 92.0.4489.2 canary (64bit) and chrome 90.0.4430.93 (64bit)
 - Video specs (resolution, frame-rate, codec, file size):  1920 x 1080, 24frame/sec, mp4, 9289KB

**To Reproduce**
1. Update()
`float time = VCRPlayer.inst.PlayingPlayer.Control.GetCurrentTimeMs();
            float dt = VCRPlayer.inst.PlayingPlayer.Info.GetDurationMs();
            float d = Mathf.Clamp(time / dt, 0.0f, 1.0f);
            var curr = TimeSpan.FromSeconds(time * 0.001f);
            var duration = TimeSpan.FromSeconds(dt * 0.001f);
            seekSlider.value = d;
            timeTxt.text = $"{string.Format("{0:D2}:{1:D2}", curr.Minutes, curr.Seconds)}/{string.Format("{0:D2}:{1:D2}", duration.Minutes, duration.Seconds)}";`

2. build webgl
3. play on website.

**Logs**
If applicable, add error logs to help explain your problem.

Event log

Looping
StartedSeeking
StartedBuffering
FinishedSeeking
FinishedBuffering

and video and sound is choppy...

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Hi @coin-jinmeng 

Are you seeing the same problem in the editor as in the WebGL build? 

Could you try this same code with one of our sample videos and let us know if the problem persists?

**Comment by coin-jinmeng** [comment]
> Hi @coin-jinmeng
> 
> Are you seeing the same problem in the editor as in the WebGL build?
> 
> Could you try this same code with one of our sample videos and let us know if the problem persists?

i tried
same code, sample video, but same problems...
![image](https://user-images.githubusercontent.com/68887878/117271990-b251d680-ae95-11eb-870f-4201a8f93fae.png)


One thing I noticed is that this does not happen if I minimize the browser window. Can you help me? Help me, please.

**Comment by AndrewRH** [comment]
Hi I'm not sure what issue you're reporting.  You mentioned that the playback of video isn't smooth and audio is stuttering, but also have pasted events..

Do you mean that if you call the code you pasted each frame, THEN the playback becomes choppy?  (in which case could it not be due to the per-frame logging?)

It also seems like your code is seeking through the video....so is it during this seeking that you're getting the choppy playback?  In which case this is probably because unless you have a key-frame for every frame, seeking will be quite slow, nowhere neat as smooth as normal playback.

Please help us understand the problem better.

Which browser are you seeing this issue in?  Have you tested with other browsers?

Thanks,
