### ISSUE TITLE
How can I get pixel data without the stall?

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#760]
How can I get pixel data of every frame?

I want to stream videos using other streaming solutions on Android and iOS.
Using ExtractFrame() for every frames seems to have performance issue.

Is there a way to receive pixel data immediately without going through ReadPixel?

**Comment by kahnivore** [comment]
Hey @dw8869 

There are some interesting ideas about this on this thread [here](https://forum.unity.com/threads/what-are-the-alternatives-for-readpixels-or-how-to-optimise-its-performance.694006/). 

Let us know if any of these help, otherwise, could you let us know a bit more about your use-case? 

Thanks

**Comment by kahnivore** [comment]
Basically the nature of this is that you're either going to end up with a stall if calling this every frame, or you could implement using an asynchronous method as mentioned on the above thread which will help performance but result in some latency (or similarly calling ReadPixel() only when the gpu is ready to give them to you/is not rendering). It's on our roadmap to implement the latter into ExtractFrame() so users can choose between latency or accuracy. 

Does that make sense?
