### ISSUE TITLE
There are always CPU consuming thread

### ISSUE THREAD

**Issue by RadioBear** [RenderHeads/UnityPlugin-AVProVideo#771]
On Android, When AvPro plays a video, it creates a Native Thread that spends a lot of CPU time, and it also spends CPU time when there is no video playing.

Here is the thread state you see using the top command:
![Thread2](https://user-images.githubusercontent.com/16686672/117754766-96f81a00-b24d-11eb-9f19-7f5583c8b0c0.png)

There's no video playing at that time.

Here is the thread state as seen using the DDMS tool:
![Thread](https://user-images.githubusercontent.com/16686672/117754690-6dd78980-b24d-11eb-8c5a-66949af6cc09.png)

 - Unity version: 2018.4.30
 - AVPro Video version: 1.11.3
 - Operating system version: Android OS

**Comment by RenderHeadsSte** [comment]
Are you able to run the same test scenario using the trial version of AVPro Video v2.x @RadioBear?

**Comment by RadioBear** [comment]
Yes, I have tested AV Pro 2.x without any problems.This issue only appears in version 1.x. @RenderHeadsSte

**Comment by RenderHeadsSte** [comment]
I am afraid I don't think there is.  My hunch is that the thread is spun up by (the older version of) ExoPlayer used in v1.x.  A huge part of the massive reworking that went into v2.x was so we could upgrade (and hopefully continue to upgrade) the version of ExoPlayer we incorporate into AVPro Video.

Here is something worth trying...switch to using the 'MediaPlayer' API path instead of using ExoPlayer.  If the thread goes away, then that is proof it is down to the older version of ExoPlayer used in v1.x.  Of course, your could stick with v1.x and use the MediaPlayer API path if you are not using any specific features of the ExoPlayer API path, and performance is acceptable.

**Comment by RadioBear** [comment]
The problem is still unresolved after trying to switch to the 'MediaPlayer' API.But thank you all the same, we will consider and make a decision whether to upgrade AVPRO video v2.x.

**Comment by RadioBear** [comment]
Another project of our company has been launched in Unity2017 version. For the stability of the project, we will not upgrade to Unity2018 version.So none of these projects can use AvPro Video 2.x.We have to solve this problem in 1.x.Please help. Thank you. @RenderHeadsSte

**Comment by RenderHeadsSte** [comment]
I am surprised that switching to MediaPlayer does not solve the issue.  This would suggest that the issue is not linked to ExoPlayer. Unless something being isnitialised on that side regardless of MediaPlayer being used.  I don't think it is, but maybe one extra step to try would be to delete all the ExoPlayer library files from the Android plugins folder.

Regarding Unity 2017.  AVPro Video v2.x does work with Unity 2017 I believe (see [here](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html)).  There are hoops to jump through if you are using lower versions than 2017.4.17, but it is possible to achieve.  What version of 2017 are your projects using?

**Comment by RadioBear** [comment]
Thank you for your help.We finally figured out where the thread came from. It turned out to be Unity's rendering thread, Unity didn't name it, and the DDMS tool misled us.
