### ISSUE TITLE
In comparison to native oculus video player, some 360 videos have aliasing/noise.

### ISSUE THREAD

**Issue by davidfufu** [RenderHeads/UnityPlugin-AVProVideo#787]
**Describe the issue**
I am using the Sphere Apply To Mesh Method of playing 360 degree videos is used in the Oculus Quest. I am using the base materials and sphere models used in the demo model: Sphere: OctahedronSphere8192,  Material: demo-360. We have compared the builds with the video playing using the native Oculus video player. We have observed that some of the videos will have aliasing/noise/jittering when played  with the AVPro Sphere Apply To Mesh method but will not have these issues when playing in the native Oculus player.

What are possible ways to reduce the noise/jittering? Could I substitute a higher poly sphere asset? What about the filtering setting? Will setting it to Trilinear help?

**Your Setup (please complete the following information):**
 - Unity version:  Unity 2019.4
 - AVPro Video version:  2.1.0
 - Operating system version: 
 - Device model:  Oculus Quest 1
 - Video specs (resolution, frame-rate, codec, file size): HEVC 5k 25bitrate

**Comment by kahnivore** [comment]
Hi @davidfufu 

Would it be possible to send a screen video to show the aliasing/noise/jitter you're experiencing? It might aid us in offering the correct advice. If the following suggestions do not help, please do send an example. 

An important thing to note about aliasing is that it's generally a result of a frequency mismatch caused by scaling. So the best way to solve it is to make sure that nothing is being scaled. Trilinear filtering won't make any difference unless you're using mipmaps. Enabling mipmaps could help with aliasing. Anisotropic filtering is only useful for surfaces that are slanting at extreme angles to the camera, angles you wouldn't have when using a sphere.  It might be that your device is scaling down your footage and that is causing the aliasing. Please have a look for suggested resolutions on Oculus Quest - you could reencode your footage at a lower resolution to see if this solves the issue.

**Comment by AndrewRH** [comment]
There's a small chance that this may be related to issue #791

**Comment by AndrewRH** [comment]
@davidfufu some screenshots would really help :-)
