### ISSUE TITLE
AudioOutput Playing 6 channel audio breaking up in Android.

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#798]
AudioOutput Playing 6 channel audio breaking up in Android.

Unity Android channel is 2 channel. ( not changed )
I want play 6 channel audio file by AudioOutput.
But sound breaking up

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.15f1
 - AVPro Video version: v2.1.0
 - Operating system version: Android OS 11
 - Device model:  SM-G977N

**Videos**
https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4

**Comment by RenderHeadsSte** [comment]
If you are not requiring to pipe the audio back through into Unity, then ensure you have the 'Android->Audio Output' setting set to 'System Direct' and your audio should play back correctly.

If you require the audio to be piped through Unity then there is a lot more for me to type!

**Comment by dw8869** [comment]
@RenderHeadsSte 

I need to audio raw data. That's why i need set to Unity.
How can i fix it?

**Comment by RenderHeadsSte** [comment]
In that case you will need to map out the desire channels.

From my experience, I have never seen an Android device that Unity doesn’t automatically change to stereo audio by run-time regardless of what you set in the Unity settings. So what you end up getting back out of AVPro Video in the grab audio function will be all the channels in the source audio stream. This, as is, is going to be pumped into unity, hence the incorrect nature of what you hear.

You will need to adjust the script at the audio callback point, and ensure you grab all the data you need for that frame...because the buffer unity provides will only be for stereo. Once you have all the audio data for that audio frame, you can map out whatever you desire and feed it back into Unitys provided buffer...and do whatever you want with all the channels data.

Hope that makes sense.

**Comment by dw8869** [comment]
@RenderHeadsSte 

Can you tell me the guide to the stereo for channel 6 ?
and please let me know how the audio channel raw data.
ex) [left center],[left],[center]....

**Comment by RenderHeadsSte** [comment]
Depending where you are looking in our interface chain/components, you want to look at where the audio samples are grabbed back from the plugin, in AndroidMediaPlayer.cs ... the following line is what pulls samples...

float[] outBuffer = m_Video.Call<float[]>("GrabAudio", sampleCount, channelCount);

You will want to adjust channelCount going into that call and then map out the return float buffer (outBuffer) to the Unity audio sample buffer (passed in as buffer).

Sample arrangement is interleaved and in the range -1.0f to 1.0f.  See [here](https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnAudioFilterRead.html) for more information of what Unity expects.
