### ISSUE TITLE
ApplyToMesh's DefaultTexture doesn't get set when using WinRT Video Player (after first OpenMedia call)

### ISSUE THREAD

**Issue by eedmond** [RenderHeads/UnityPlugin-AVProVideo#802]
When starting videos using the WinRT video player, the ApplyToMesh's DefaultTexture does not get rendered. The last frame of the previous video renders until the new video plays. This issue reproduces 100% of the time *after* the first video, which displays the DefaultTexture correctly. Note that this works as expected when using the Media Foundation API.

 - Unity version: 2019.4.23f1
 - AVPro Video version: v2.1.3-Enterprise
 - Operating system version: Windows 10 Version 21H1
 - Device model: Surface Laptop 3
 - Video specs (resolution, frame-rate, codec, file size): Any

**To Reproduce**
1. Use WinRT media player and ApplyToMesh renderer
2. Call mediaPlayer.OpenMedia and let the video run for a few seconds
3. Call mediaPlayer.OpenMedia with a new video and set ApplyToMesh.DefaultTexture to any image.

Expected: The DefaultTexture appears until the video loads
Actual: The last frame of the previous video renders until the new video starts playing

**Videos**
Any video can be used. I was able to easily reproduce this error in the Demo_DisplayComponents sample scene by adding a script that loads a new video (with a thumbnail image) every 4 seconds. The thumbnails are never set.

**Comment by RenderHeadsSte** [comment]
Instead of setting the DefaultTexture object directly, have you tried calling the method:

`_myApplyToMesh.ChangeDefaultTexture( myTexture );`

This will force an update after changing the default texture.

**Comment by eedmond** [comment]
Thanks, Ste! Looking at the DefaultTexture setter, it is calling ChangeDefaultTexture (which is a private method)

**Comment by RenderHeadsSte** [comment]
You are right, sorry, completely miss-read the code.

**Comment by RenderHeadsSte** [comment]
<deleted unhelpful suggestion and response>

**Comment by RenderHeadsSte** [comment]
Note: deleted unhelpful suggestion and response

**Comment by AndrewRH** [comment]
This behaviour is actually by design.  Ideally the other media player APIs would do the same (hold the last texture while loading the next media) and this is something we are working towards.  If you want to show a texture between video loads then I recommend using a separate UI element and show it so you have full control over this behaviour.   The default texture is meant to be shown while there is no valid texture produced by the MediaPlayer component.  Most users though do not want a black/default texture to appear between video loads as they're loading local content which is fast and this would result in a single frame displaying the default texture and look glitchy.

In your case you could disable the ApplyToMesh component when you load a new video, assign your thumbnail texture to the mesh material yourself and then when you receive the FirstFrameReady event reenable the ApplyToMesh component.

I hope this helps.  We are aiming to improve the consistency between APIs and platforms for this behaviour.
