### ISSUE TITLE
AVPro v1: Manually setting the initial stream track

### ISSUE THREAD

**Issue by justin-pierce** [RenderHeads/UnityPlugin-AVProVideo#811]
Our video host puts a 240p stream track first, so on load we see that super low resolution stream first and we'd rather instead load a different track initially. 

 - Unity version: 2020.1.17
 - AVPro Video version: 1.10.1
 - Operating system version: iOS/Android
 - Device model: iPhone 12 Pro / Pixel 2
 - Video specs (resolution, frame-rate, codec, file size): Vimeo HLS Stream

I saw in the docs that there's an option to start on highest res on Android (not really what we want either) and that on iOS, it keeps to the Apple standard of starting with the first track (they seem to recommend starting with a mid bandwidth option but Vimeo doesn't). So I tried controlling it manually. 

What I've tried doing is creating a StreamParser component, parsing the stream, finding the track I want, then calling `mediaPlayer.Control.SetVideoTrack(trackIndex);` after the mediaPlayer.Control initializes -- but it doesn't seem to work. These videos auto play so I'm not exactly sure when I should be setting it. Should it work? Or will we just have to edit the HLS manifest? 

Thanks,

**Comment by kahnivore** [comment]
What do you mean the videos auto play? Have you not set AutoPlay to false?

**Comment by justin-pierce** [comment]
> What do you mean the videos auto play? Have you set AutoPlay to false?

They're intended to auto play -- I only mention it in case it would be necessary to disable auto play, set the desired initial track, then manually play. 

The AVPro setup is generated by code at runtime.

**Comment by RenderHeadsSte** [comment]
'SetVideoTrack' will treat an adaptive group of tracks as a single track, so that is why you are not getting the results you expect I suspect.

For both iOS and Android the starting track is completely at the mercy of the systems under the hood (Apple and ExoPlayer respectively).  There is a possibility on Android we could hint the BandwidthMeter, but this would certainly not be a sure-fire 100% solution and only on the one platform.

Have you tried moving your desired bandwith/resolution stream to the start of the manifest?  There is a possibility this might work on Apple platforms...

**Comment by justin-pierce** [comment]
> Have you tried moving your desired bandwith/resolution stream to the start of the manifest? There is a possibility this might work on Apple platforms...

Yeah this is the workaround we've been playing with so far. Thanks for the info!
