### ISSUE TITLE
Left/Right Trasparency packing on iOS

### ISSUE THREAD

**Issue by dariusjulian** [RenderHeads/UnityPlugin-AVProVideo#815]
I've built an iOS app using the LR transparency and those videos don't show up.  Does LR transparency work in iOS?

**Comment by MorrisRH** [comment]
Yes, LR transparency should be working fine on iOS.

Can I get a little more information from you?:
- Unity version.
- AVPro Video version.
- iOS device type and iOS version,
- Details of the video (dimensions, codec, bitrate, etc.)

Can share your video with us? If so that would be very helpful, please send it to unitysupport@renderheads.com mentioning "GitHub Issue #815" in the subject.

**Comment by kahnivore** [comment]
Hey @dariusjulian 

Let us know if you still need help resolving this issue.

**Comment by dariusjulian** [comment]
Hi!  Thank you for following up.  So far we have been unable to reproduce it.  We're attributing it to a random glitch on the windows/ hardware side and not something with Unity or your asset.
