### ISSUE TITLE
Lit shader will make the video upside-down on Android.

### ISSUE THREAD

**Issue by cdytoby** [RenderHeads/UnityPlugin-AVProVideo#82]
**Describe the bug**

I just need information how to get around this. 

We switched to Lit shader in order to make a video surface “react to light”

When using "AVProVidel/Lit/Transparent Diffuse" shader, the video on Android is upside down, but on iOS it shows correctly. I can confirm by using unity standard shader, the video orientation is correct, but due to the YCbCr setup on iOS, the color would be wrong with standard shader. Can you provide an information where I can fix it? I checked the  “AVProVidel/Lit/Transparent Diffuse” shader file, and I noticed there is no “TRANSFORM_TEX” or “invert y” section. Should I add it? (Also I can’t find “appdata_full” defination in these files)

**Your Setup (please complete the following information):**
 - Unity version: v2017.4.26f1
 - AVPro Video: plugin v1.9.8 scripts v1.9.10
 - Operating system version: Windows 10
 - Device model: Oculus Go/Oculus Quest

**To Reproduce**
(I don't have a test project for now, sorry, will add it at a later date)
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Had a look at this..the non transparent version of the Lit Diffuse shader seems to work fine - perhaps you could use this?

Otherwise, if you need to use the transparent version, it appears there is a bug in there.  I've attached the fixed version here and it will be included in the next version of the plugin.

For iOS you can always disable the YpCbcr option in the PlatForm Specific > iOS settings section if you want to use the Standard shader.

I hope that helps.  I'll close this issue now :)
[AVProVideo-Lit-Transparent-Diffuse.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/3307208/AVProVideo-Lit-Transparent-Diffuse.zip)
