### ISSUE TITLE
Looping video problem

### ISSUE THREAD

**Issue by MB-k-ishida** [RenderHeads/UnityPlugin-AVProVideo#827]
**Describe the issue**
Hello,
I am facing an issue that the loop doesn't start from the beginning on the second loop when streaming video on iOS.
This issue happened every time on iPhone8(13.1.2) and there were no issue on Windows, Android and iPhone10(14.5)

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.17f1
 - AVPro Video version: 2.1.3
 - Operating system version: Windows10
 - Device model: iPhone8(13.1.2)
 - Video specs (resolution, frame-rate, codec, file size): 1280x720 29.9fps format=m3u8-aap

**To Reproduce**

**Logs**

**Screenshots**

**Videos**
I will tell you by email.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MB-k-ishida** [comment]
Thank you for your answer.
I have tried streaming with another short video. By this one only with sound, the video stops on the second loop.
This only happen on iPhone8(13.1.2) and there were no problem on iPhone8(13.5) and iPhone10(14.5).

I will send you the link of the stream later in the other mail.

**Comment by MorrisRH** [comment]
I've tested the URLs you provided on an iPhone 5s running iOS 12.5.1 and an iPhone X running iOS 14.6.

On the iPhone 5s I'm seeing behaviour that matches what you describe for the iPhone 8 (iOS 13.1) and I'm not seeing any issues with the iPhone X.

I think what is happening is that when the loop occurs, because the lowest bitrate variant is audio only it starts playing just audio before upgrading the stream to one of the higher bitrate variants which include video data, effectively missing the first few frames of video.

Unfortunately this is all internal to iOS and we have no control over which variant is initially picked by the system. The only solution I can think of for older versions of iOS would be to not have an audio only variant in your manifest so it will always pick a variant that has video.

**Comment by MB-k-ishida** [comment]
understood. Thank you very much.
