### ISSUE TITLE
Refresh Mic when Unplugged and then Plugged when Unity is in play mode

### ISSUE THREAD

**Issue by lookreelDev** [RenderHeads/UnityPlugin-AVProVideo#834]
**Question**
Hi,

Like to say you made an incredible asset and very reliable.

I am on a important project that needs to be delivered by Monday. I have noticed that my device mic's do not update on AVPro as I unplug and plug in the device. This is an important part of the product when it comes to recording the sound when changing the mic's when running a unity build. I have been looking every where in the code to find this feature. 

I just need a hint into where I can implement such a function.

Regards

George

**Comment by kahnivore** [comment]
Hi @lookreelDev 

Thanks for your support.

Which platform are you building for? And which version of AVPro are you using? And what do you mean by update - do you mean you wish to switch mics?

**Comment by lookreelDev** [comment]
Hi kahnivore

Apologies I wasn't clear. I been under pressure and I rushed the message.

I am using the following version:

Unity 2020.3.11f1
AVPro 4.6.4

When I press play to run the AVPro with the GUI that appears with the detected devices initialised. It runs well. I can change my mic devices that have been initialised. 

However I when I try to plug a new device it doesn't seem to re-initialise the device list to refresh newly detected devices when I am in runtime. 

This is important because I am building an application that requires device change over(especially new devices). I have built a live mic that works in runtime as you switch new devices. 

However for the life of me I am trying to find a function in your code that can achieve re-initialisation of devices in runtime.
Because I am short on a deadline I have not much time to try to figure how I could do this.

Please if you can give me some help.

Much Obliged 

George

**Comment by AndrewRH** [comment]
Hi @lookreelDev I've just realised from the version number that you're talking about the product AVPro Movie Capture, and not AVPro Video (which this Github issues is for).  

We have a separate Github issues for AVPro Movie Capture:
https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture

For best results please post your issue here so, and also include which platforms you need to support.

I think that AVPro Movie Capture only initialised the microphones once, so it doesn't support dynamic microphone connections, but this is something we can look into - but do let us know the platforms you need support with as this will affect how quickly we can look at this.

Thanks,

**Comment by kahnivore** [comment]
Closing as this is not an AVPro Video issue
