### ISSUE TITLE
Custom OES shader not working in 2.1.5

### ISSUE THREAD

**Issue by mikerz** [RenderHeads/UnityPlugin-AVProVideo#847]
**Describe the issue**
A clear and concise description of what the issue is.

It appears that only a few pixels of the texture are loaded up, and they are stretched across the screen, forming stripes. Does not occur on non-OES path.

This affects videos and video streams

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.22f1
 - AVPro Video version: 2.1.5f1-ultra
 - Operating system version: Android on Quest 2, not sure 
 - Device model: Oculus Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 
All videos affect.
One particular video:
3000 x 3000 h265 45 mbps bitrate, file size 460 mb
Also any video stream

**To Reproduce**
1. Play any video with OES path on android

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
What shader are you using?  There was a bug fix recently that will be included in v2.1.6.  It is just a shader error and a fixed version can be found in issue #780

**Comment by mikerz** [comment]
We use our own shader, initially based off of the AVPro ones -- we've not
introduced any shader changes. Reproduces with 2.15 but not earlier
versions (~2.1.0)

**Comment by mikerz** [comment]
Just checked, last version it was definitely working was 2.0.9-b

**Comment by RenderHeadsSte** [comment]
Yeah, changes since then.  Here is a quick grab of changes made to the InsideSphere-AndroidOES shader...

![image](https://user-images.githubusercontent.com/46531149/124248112-6d0af780-db1a-11eb-9cd5-e9bb74c28180.png)
![image](https://user-images.githubusercontent.com/46531149/124248165-798f5000-db1a-11eb-9c0e-05032b18a7c0.png)
![image](https://user-images.githubusercontent.com/46531149/124248185-7e540400-db1a-11eb-882a-c32861d49aad.png)

Not a huge amount, but I would think enough to give your odd behaviour.

If you have _CroppingScalars in your shader(s)...then you will need to make the adjustments to all custom OES shaders.

Happy to take a look at integrating the changes into your shader(s) if you want to email it over to me.

**Comment by mikerz** [comment]
I see, thanks -- will take a look! 

That's probably it; from my point of view it's an API change and not just a shader change, since we're manually having to set the shader properties including CroppingScalars (and soon TextureMatrix)

**Comment by kahnivore** [comment]
Hi @mikerz 

Did you manage to solve this?
