### ISSUE TITLE
Unsupported D3D format 0x58

### ISSUE THREAD

**Issue by RemyRM** [RenderHeads/UnityPlugin-AVProVideo#85]
**Describe the bug**
Whenever a new video starts playing, or there is a resolution change (using HLS) in the video an the error "Unsupported D3D format 0x58" gets thrown when using DX11.

The error only occurs on Windows, but doens't seem to affect quality or playback negatively.

**Your Setup (please complete the following information):**
 - Unity version: 2019.1.0f2, .net 4.x runtime, IL2CPP backend .NET 4.x Api compatibility.
 - AVPro Video version: 1.9.17 (Observed all the way back in 1.9.10 aswel)
 - Operating system version: Windows 10 Pro (64 bit), version 1809 build 17763.557
 - Device model: intel i5 processor, GTX 1060 gpu
 - Video specs (resolution, frame-rate, codec, file size): Any video resolution, frame-rate or size. observed with h.264 codec

**To Reproduce**
1. Open unity 2019.1.0f2 (also observed in 2018.3) with AVPro 1.9.17
2. Set the graphics API to DX11
3. Play any video from the demo scenes

**Logs**
Full stack callstack:
```
Unsupported D3D format 0x58
0x00007FF7897F93CC (Unity) StackWalker::GetCurrentCallstack
0x00007FF7897FC881 (Unity) StackWalker::ShowCallstack
0x00007FF787F68695 (Unity) GetStacktrace
0x00007FF78A216C60 (Unity) DebugStringToFile
0x00007FF788861A9F (Unity) d3d11::GetGraphicsFormatFromDX
0x00007FF788863455 (Unity) TexturesD3D11Base::RegisterNativeTexture
0x00007FF788859906 (Unity) GfxDeviceD3D11Base::RegisterNativeTexture
0x00007FF7888E0C00 (Unity) GfxDeviceWorker::RunCommand
0x00007FF7888E8A5B (Unity) GfxDeviceWorker::RunExt
0x00007FF7888E8E25 (Unity) GfxDeviceWorker::RunGfxDeviceWorker
0x00007FF789496747 (Unity) Thread::RunThreadWrapper
0x00007FFE85137974 (KERNEL32) BaseThreadInitThunk
0x00007FFE8527A271 (ntdll) RtlUserThreadStart
```

**Comment by AndrewRH** [comment]
Hi, 

I've just tested here with 2019.1.0f1 and 1.9.17 but i can't replicate that bug.  We did see this bug before though, but it was fixed in 1.9.14.

I suspect that your plugin didn't upgrade correctly.   Please check the console window to see which versions it reports:

![image](https://user-images.githubusercontent.com/5418126/59853083-12096c00-9368-11e9-8820-0e1c4b016240.png)

It should say 1.9.17 for both script and plugin version.

If then isn't the case, then please try upgrading again.  To make sure that plugin (DLL) files aren't locked you can follow these steps:

1) Close Unity
2) Open Unity
3) Don't click on any objects or run the scene or do anything (this will lock the DLL files)
4) Install the upgraded version

Let me know if this helps at all.

Thanks,

**Comment by RemyRM** [comment]
For some reason my Plugin version appears to be v1.9.8 even
`[AVProVideo] Initialising AVPro Video (script v1.9.17 plugin v1.9.8) on NVIDIA GeForce GTX 1060 6GB/Direct3D 11.0 [level 11.1] (MT True) on WindowsEditor` I will try updating it again.

**Comment by RemyRM** [comment]
Reimporting after making sure my DLL's wern't locked solved the issue. Thanks a bunch Andrew.

**Comment by AndrewRH** [comment]
Pleasure :)
