### ISSUE TITLE
Clear existing buffer [v1]

### ISSUE THREAD

**Issue by johnfriedrich** [RenderHeads/UnityPlugin-AVProVideo#852]
Hello there! 

We are currently on 1.11.4 and are using AvPro on iOS and Android.

When playback stalls due to connection loss and you call play, sometimes the video plays for 1-3 seconds eventhough there is no internet connection. 
I didn't find a ClearBuffer() method to stop that from happening. Is there a workaround to clear the buffer?
As we are supporting multiple players from different brands, we check if the player is stalled by comparing timestamps every few seconds. AvPros behaviour breaks this pretty much

**Comment by kahnivore** [comment]
Hi there,

There is no method to clear the buffer. A bit unsure of what you're trying to do or what the problem is. But essentially the player will play as long as it has frames buffered. Perhaps you could write something to detect if the network drops, or of another one of your players stalls, and then pause our player at that moment?
