### ISSUE TITLE
How could stabilized the AVPro live streaming in the Application on a MacBook?

### ISSUE THREAD

**Issue by YukiEbisawa** [RenderHeads/UnityPlugin-AVProVideo#892]
**Question**
Hi, I have a Question about the following product I bought, 
below I will put the link.

https://assetstore.unity.com/packages/tools/video/avpro-video-ultra-edition-184294

The Question is that when I play a live streaming using Demo_MediaPlayer.unity provided by AVPro on MacBook,
it plays with an unstable quality or the live streaming just stops,
even in a stable internet environment.
Please let me know, how could I stabilize a Live streaming in the application on MacBook?

I have proved with other 3 MacBook's and I had the same result.
When it played in browser in the same internet environment and I had no problem,
it is stable and the quality does not deteriorate.
I have also check the Memory and CPU status.
The CPU had a load around 70%, and the memory had a surplus of about 8G.
I Also try with Window and I have no problems.

I will share below the Spec of the MacBook I used.

MacBook Pro (13inch, 2020, Thunderbolt 3port x 4)
Process	     2.3 GHz Quad-core Intel Core i7
Memory　     32 GB 3733 MHz LPDDR4X
Graphics　   Intel Iris Plus Graphics 1536 MB

**Comment by kahnivore** [comment]
Hi @YukiEbisawa 

Which version of AVPro 2.x Ultra are you using? Are you using the latest - 2.1.8?

What do you mean the streaming just stops? Is there an error thrown at that point? Is this in the editor or in a build? 

Would it be possible to share the streams you are testing with us? You can send them to unitysupport@renderheads.com if they are private. 

Thanks.


Would it be possible to share some of the streams you are testing with?

**Comment by YukiEbisawa** [comment]
Thank for the response @kahnivore 

I'm using the version 2.1.3. I would ask if there were the same problem I’m having and with the version 2.1.8 it will solve this problem.

About "the streaming just stops" sorry, I choose the wrong word it means that the streaming freezes, 
there were no error.
also this problem is occurred in a build.

Yes, it possible to share the streams, could you tell me when could you check it and then I will stream it at that time.
About the time I'm writing from Japan, so I would appreciate it if you could specify it in Japan time.

Thanks

**Comment by kahnivore** [comment]
The first point of call would be upgrading to 2.1.8. Not sure if it will solve your problem but there have been a lot of fixes and improvements made for mac since 2.1.3. 

Can you provide more details about your stream? What extension is it? 

Apple's API's are very pedantic about specs - they have very specific guidelines and don't handle edge cases very well. Browsers have their own low-level implementation so they're less reliant on Apple API's, which is why it could play fine in your browser but not in AVPro. AVPro uses Apple's API for playback. It's also possible that this has to do with your server setup. 

Could you attach the log files so we can see if there are any errors?
