### ISSUE TITLE
 Why is exoplayer needed in Android

### ISSUE THREAD

**Issue by Jekton** [RenderHeads/UnityPlugin-AVProVideo#964]
**Question**
 Why is exoplayer needed in Android? Is it used to decode video?

**Comment by RenderHeadsSte** [comment]
> **Question** Why is exoplayer needed in Android? Is it used to decode video?

From the [ExoPlayer github page](https://github.com/google/ExoPlayer):

"ExoPlayer is an application level media player for Android. It provides an alternative to Android’s MediaPlayer API for playing audio and video both locally and over the Internet. ExoPlayer supports features not currently supported by Android’s MediaPlayer API, including DASH and SmoothStreaming adaptive playbacks. Unlike the MediaPlayer API, ExoPlayer is easy to customize and extend, and can be updated through Play Store application updates."

> can I used other version of exoplayer instead of the jar provided by AVPro Video?

The simple answer is 'no'.  This is because of interface/functional/feature changes between ExoPlayer versions.  The ExoPlayer code used in our Android plugin would likely produce errors and not work.

My question is...why would you want to?

**Comment by Jekton** [comment]
Nice, it looks OK, thank you

**Comment by SecretTonto** [comment]
AVPro 2.2.3 version is being used.
It is confirmed that the version of ExoPlayer in that version is 2.15.0.

In version 2.15.0 of ExoPlayer included in AVPRO 2.2.3,
If you do Live Streaming for a long time, you will stop.

After checking, it seems that the phenomenon has been modified in ExoPlayer 2.15.1.
(Fix bug where the player would get stuck if all download attempts fail and would not raise an error to the application (#9390).)

So AVPro needs the version of ExoPlayer 2.15.1.

Do you have any plans to update the version of ExoPlayer to 2.15.1?

If you don't have an update plan yet, please guide us if there is a way to update the version of ExoPlayer on your own.
