### ISSUE TITLE
Unity Audio stutter 

### ISSUE THREAD

**Issue by michaelj909** [RenderHeads/UnityPlugin-AVProVideo#979]
**Describe the issue**
While the audio is playing perfectly when using system direct audio output, I'm experiencing audio stutters when using unity audio output, both in-editor, and in a windows standalone build. The audio also seems to be gradually getting out of sync with the video by a couple of seconds by the end of the video. I'm also noticing similar stuttering when playing audio files using the MediaPlayer.

Are there any reasons why this might be happening, and any settings (either within the asset or within Unity) that I could tweak to improve unity audio performance?

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.16f1
 - AVPro Video version: 2.1.8
 - Operating system version: Windows 10 Home
 - Device model: Intel i7-4790K 4.00 GHz, 16.00 GB RAM, Nvidia GTX 980
 - Video specs (resolution, frame-rate, codec, file size): 854x480, 30fps, H264 MPEG-4 AVC video, MPEG AAC audio

**To Reproduce**
1. Play linked video from an Absolute File Path (I have my test video in my documents folder, for example)

**Videos**
I've been using the video at [this dropbox link](https://www.dropbox.com/s/rkar2aatpmyolg0/HNNA.mp4) for testing.

**Comment by michaelj909** [comment]
Thanks for the tips - I've noticed spikes in the profiler cause by Garbage Collection, and am investigating that further.

For the record, I've tested with both vsync enabled and disabled, and it didn't seem to affect the stutter. And 'Run in Background' is enabled in my project.

**Comment by Heagin-OhJeongSeok** [comment]
hello. 
We are using the AVPro plugin to create an in-game movie theater.
We have no problem using the direct audio output option as in the question above.
However, if we use the unity audio output option and the Audio Output component, the sound stutters when we run the garbage collection using Resources.UnloadUnusedAssets().
This only happens when I use the unity audio output option and the Audio Output component.
Does anyone have a solution to this problem?

**Comment by Chris-RH** [comment]
Please could you open a new issue for this and provide the required details.
